import { useCallback, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

import { useTranslation } from "../../lib/i18n/useTranslation";
import type { CopyKey } from "../../lib/i18n/copy";
import type { CoachActivity, ComposerLanguage } from "../../lib/types";
import { CoachActionPill } from "./CoachActionPill";

export interface CoachActionStatusProps {
  kind: CoachActivity["kind"];
  label?: string;
  status?: CoachActivity["status"];
  resultLabel?: string;
  detail?: string;
}

const kindToCopyKey: Record<CoachActivity["kind"], CopyKey> = {
  checking_resources: "coachActionCheckingResources",
  aligning_plan: "coachActionAligningPlan",
  scheduling_training: "coachActionSchedulingTraining",
  evaluating_result: "coachActionEvaluatingResult",
  generating_card: "coachActionGeneratingCard",
  reviewing_evidence: "coachActionReviewingEvidence",
  idle: "coachActionIdle",
  search_resources: "coachActionCheckingResources",
  align_plan: "coachActionAligningPlan",
  generate_cards: "coachActionGeneratingCard",
  evaluate: "coachActionEvaluatingResult",
  other: "coachActionIdle",
  search: "coachActionCheckingResources",
  plan_alignment: "coachActionAligningPlan",
  card_generation: "coachActionGeneratingCard",
  evaluation: "coachActionEvaluatingResult",
  resource_upload: "coachActionReviewingEvidence",
  workspace_classification: "coachActionIdle",
};

const kindToDoneCopyKey: Record<CoachActivity["kind"], CopyKey> = {
  checking_resources: "coachActionDoneCheckingResources",
  aligning_plan: "coachActionDoneAligningPlan",
  scheduling_training: "coachActionDoneSchedulingTraining",
  evaluating_result: "coachActionDoneEvaluatingResult",
  generating_card: "coachActionDoneGeneratingCard",
  reviewing_evidence: "coachActionDoneReviewingEvidence",
  idle: "coachActionDoneIdle",
  search_resources: "coachActionDoneCheckingResources",
  align_plan: "coachActionDoneAligningPlan",
  generate_cards: "coachActionDoneGeneratingCard",
  evaluate: "coachActionDoneEvaluatingResult",
  other: "coachActionDoneIdle",
  search: "coachActionDoneCheckingResources",
  plan_alignment: "coachActionDoneAligningPlan",
  card_generation: "coachActionDoneGeneratingCard",
  evaluation: "coachActionDoneEvaluatingResult",
  resource_upload: "coachActionDoneReviewingEvidence",
  workspace_classification: "coachActionDoneIdle",
};

export function CoachActionStatus({
  kind,
  label,
  status = "active",
  resultLabel,
  detail,
}: CoachActionStatusProps) {
  const { t } = useTranslation();
  const [phase, setPhase] = useState<"visible" | "fading" | "removed">("visible");

  const resolvedLabel = label || t(kindToCopyKey[kind]) || kind;
  const resolvedResult = resultLabel || t(kindToDoneCopyKey[kind]) || resolvedLabel;

  useEffect(() => {
    if (status !== "completed") {
      setPhase("visible");
      return;
    }
    setPhase("visible");
    const fadeTimer = window.setTimeout(() => {
      setPhase("fading");
    }, 4000);
    return () => {
      window.clearTimeout(fadeTimer);
    };
  }, [status]);

  const handleAnimationEnd = useCallback(() => {
    if (phase === "fading") {
      setPhase("removed");
    }
  }, [phase]);

  const isActive = status === "active";
  const displayText = isActive || status === "failed" ? resolvedLabel : resolvedResult;
  const activity: CoachActivity = useMemo(() => ({
    id: `coach-action-${kind}`,
    kind,
    status,
    label: displayText,
    detail,
    timestamp: new Date().toISOString(),
  }), [kind, status, displayText, detail]);

  const isRemoved = phase === "removed";

  if (isRemoved) {
    return null;
  }

  return (
    <div
      className={`coach-action-wrapper ${phase === "fading" ? "coach-action-wrapper--fade" : ""}`}
      role="status"
      aria-live="polite"
      onAnimationEnd={handleAnimationEnd}
    >
      <CoachActionPill activity={activity} />
    </div>
  );
}

export interface ConversationCandidateProps {
  type: "flash_candidate" | "practice_candidate" | "evidence_candidate" | "resource_import_candidate" | "plan_change_candidate";
  whyNow?: string;
  targetSkill?: string;
  continueIn?: "chat" | "training" | "plan" | "resources";
  autoGenerated?: boolean;
  language?: ComposerLanguage;
  onContinue?: () => void;
  onDismiss?: () => void;
}

const candidateLabels: Record<string, Record<string, string>> = {
  "zh-CN": {
    flash_candidate: "闪记候选",
    practice_candidate: "实战候选",
    evidence_candidate: "证据候选",
    resource_import_candidate: "资料导入",
    plan_change_candidate: "计划调整",
  },
  "en-US": {
    flash_candidate: "Flash candidate",
    practice_candidate: "Practice candidate",
    evidence_candidate: "Evidence candidate",
    resource_import_candidate: "Resource import",
    plan_change_candidate: "Plan change",
  },
  "es-ES": {
    flash_candidate: "Candidato flash",
    practice_candidate: "Candidato práctica",
    evidence_candidate: "Candidato evidencia",
    resource_import_candidate: "Importar recurso",
    plan_change_candidate: "Cambio plan",
  },
  "fr-FR": {
    flash_candidate: "Candidat flash",
    practice_candidate: "Candidat pratique",
    evidence_candidate: "Candidat évidence",
    resource_import_candidate: "Importer ressource",
    plan_change_candidate: "Changement plan",
  },
  "de-DE": {
    flash_candidate: "Flash-Kandidat",
    practice_candidate: "Übungs-Kandidat",
    evidence_candidate: "Beweis-Kandidat",
    resource_import_candidate: "Ressource importieren",
    plan_change_candidate: "Planänderung",
  },
  "ja-JP": {
    flash_candidate: "フラッシュ候補",
    practice_candidate: "練習候補",
    evidence_candidate: "証拠候補",
    resource_import_candidate: "リソース取込",
    plan_change_candidate: "計画変更",
  },
  "ko-KR": {
    flash_candidate: "플래시 후보",
    practice_candidate: "연습 후보",
    evidence_candidate: "증거 후보",
    resource_import_candidate: "리소스 가져오기",
    plan_change_candidate: "계획 변경",
  },
  "pt-BR": {
    flash_candidate: "Candidato flash",
    practice_candidate: "Candidato prática",
    evidence_candidate: "Candidato evidência",
    resource_import_candidate: "Importar recurso",
    plan_change_candidate: "Mudança plano",
  },
};

const continueLabels: Record<string, Record<string, string>> = {
  "zh-CN": {
    chat: "继续对话",
    training: "去训练",
    plan: "查看计划",
    resources: "查看资料",
  },
  "en-US": {
    chat: "Continue chat",
    training: "Go to training",
    plan: "View plan",
    resources: "View resources",
  },
  "es-ES": {
    chat: "Continuar chat",
    training: "Ir a práctica",
    plan: "Ver plan",
    resources: "Ver recursos",
  },
  "fr-FR": {
    chat: "Continuer chat",
    training: "Aller à pratique",
    plan: "Voir plan",
    resources: "Voir ressources",
  },
  "de-DE": {
    chat: "Chat fortsetzen",
    training: "Zur Übung",
    plan: "Plan ansehen",
    resources: "Ressourcen ansehen",
  },
  "ja-JP": {
    chat: "チャット続ける",
    training: "練習へ",
    plan: "計画見る",
    resources: "リソース見る",
  },
  "ko-KR": {
    chat: "채팅 계속",
    training: "연습으로 가기",
    plan: "계획 보기",
    resources: "리소스 보기",
  },
  "pt-BR": {
    chat: "Continuar chat",
    training: "Ir para prática",
    plan: "Ver plano",
    resources: "Ver recursos",
  },
};

/**
 * @deprecated This component is no longer used. Kept for reference only.
 */
export function ConversationCandidate({
  type,
  whyNow,
  targetSkill,
  continueIn,
  autoGenerated,
  language = "en-US",
  onContinue,
  onDismiss,
}: ConversationCandidateProps) {
  const typeLabel = candidateLabels[language]?.[type] ?? type;
  const continueLabel = continueIn ? (continueLabels[language]?.[continueIn] ?? continueIn) : undefined;

  return (
    <div className="conversation-candidate" role="region" aria-label={typeLabel}>
      <div className="conversation-candidate__header">
        <span className="conversation-candidate__badge">{typeLabel}</span>
        {autoGenerated && (
          <span className="conversation-candidate__auto">
            {language === "zh-CN" ? "自动" : "Auto"}
          </span>
        )}
      </div>
      {whyNow && <p className="conversation-candidate__why">{whyNow}</p>}
      {targetSkill && (
        <p className="conversation-candidate__skill">
          {language === "zh-CN" ? "目标能力" : "Target skill"}: {targetSkill}
        </p>
      )}
      <div className="conversation-candidate__actions">
        {continueLabel && onContinue && (
          <button className="button button--accent button--micro" type="button" onClick={onContinue}>
            {continueLabel}
          </button>
        )}
        {onDismiss && (
          <button className="button button--ghost button--micro" type="button" onClick={onDismiss}>
            {language === "zh-CN" ? "忽略" : "Dismiss"}
          </button>
        )}
      </div>
    </div>
  );
}

export interface BoundaryNoteProps {
  note: string;
  language?: ComposerLanguage;
}

/**
 * @deprecated This component is no longer used. Kept for reference only.
 */
export function BoundaryNote({ note, language = "en-US" }: BoundaryNoteProps) {
  return (
    <div className="boundary-note" role="note">
      <span className="boundary-note__icon" aria-hidden="true">
        {language === "zh-CN" ? "ⓘ" : "ⓘ"}
      </span>
      <span className="boundary-note__text">{note}</span>
    </div>
  );
}
