/** §十五: legacy coach message-part copy in eight languages (no zh/en binary). */

import type { ComposerLanguage } from "../../lib/types";

/**
 * Copy for the legacy part switch renderer (CoachMessageParts.tsx). The
 * zh-CN source string is the record key.
 */
export const COACH_MESSAGE_PARTS_TEXT: Record<string, Record<string, string>> = {
  "核对中": {
    "en-US": "Checking",
    "es-ES": "Comprobando",
    "fr-FR": "Vérification",
    "de-DE": "Prüft",
    "ja-JP": "確認中",
    "ko-KR": "확인 중",
    "pt-BR": "Verificando",
  },
  "受阻": {
    "en-US": "Blocked",
    "es-ES": "Bloqueado",
    "fr-FR": "Bloqué",
    "de-DE": "Blockiert",
    "ja-JP": "ブロック",
    "ko-KR": "막힘",
    "pt-BR": "Bloqueado",
  },
  "已降级": {
    "en-US": "Degraded",
    "es-ES": "Degradado",
    "fr-FR": "Dégradé",
    "de-DE": "Eingeschränkt",
    "ja-JP": "縮退",
    "ko-KR": "저하됨",
    "pt-BR": "Degradado",
  },
  "已核对": {
    "en-US": "Checked",
    "es-ES": "Comprobado",
    "fr-FR": "Vérifié",
    "de-DE": "Geprüft",
    "ja-JP": "確認済み",
    "ko-KR": "확인됨",
    "pt-BR": "Verificado",
  },
  "教练正在核对": {
    "en-US": "Coach is checking",
    "es-ES": "El entrenador está comprobando",
    "fr-FR": "L'entraîneur vérifie",
    "de-DE": "Trainer prüft",
    "ja-JP": "コーチが確認しています",
    "ko-KR": "코치가 확인하는 중",
    "pt-BR": "O treinador está verificando",
  },
  "教练检查受阻": {
    "en-US": "Coach hit a blocker",
    "es-ES": "El entrenador se topó con un bloqueo",
    "fr-FR": "L'entraîneur a rencontré un blocage",
    "de-DE": "Trainer ist blockiert",
    "ja-JP": "コーチがつまずきました",
    "ko-KR": "코치가 막혔습니다",
    "pt-BR": "O treinador encontrou um bloqueio",
  },
  "教练已安全降级": {
    "en-US": "Coach fell back safely",
    "es-ES": "El entrenador recurrió a un modo seguro",
    "fr-FR": "L'entraîneur a basculé en mode sûr",
    "de-DE": "Trainer ist sicher in den Fallback gegangen",
    "ja-JP": "コーチは安全にフォールバックしました",
    "ko-KR": "코치가 안전하게 대체 동작으로 전환했습니다",
    "pt-BR": "O treinador recuou com segurança",
  },
  "教练已核对": {
    "en-US": "Coach checked",
    "es-ES": "El entrenador comprobó",
    "fr-FR": "L'entraîneur a vérifié",
    "de-DE": "Trainer hat geprüft",
    "ja-JP": "コーチが確認しました",
    "ko-KR": "코치가 확인했습니다",
    "pt-BR": "O treinador verificou",
  },
  "展示公式": {
    "en-US": "Display math",
    "es-ES": "Fórmula en bloque",
    "fr-FR": "Formule en bloc",
    "de-DE": "Angezeigte Formel",
    "ja-JP": "ディスプレイ数式",
    "ko-KR": "블록 수식",
    "pt-BR": "Fórmula em destaque",
  },
  "行内公式": {
    "en-US": "Inline math",
    "es-ES": "Fórmula en línea",
    "fr-FR": "Formule en ligne",
    "de-DE": "Formel im Text",
    "ja-JP": "インライン数式",
    "ko-KR": "인라인 수식",
    "pt-BR": "Fórmula embutida",
  },
  "流程图": {
    "en-US": "Diagram",
    "es-ES": "Diagrama",
    "fr-FR": "Diagramme",
    "de-DE": "Diagramm",
    "ja-JP": "ダイアグラム",
    "ko-KR": "다이어그램",
    "pt-BR": "Diagrama",
  },
  "图表渲染失败，先显示原始内容。": {
    "en-US": "Diagram render failed. Showing the raw content instead.",
    "es-ES": "Error al renderizar el diagrama. Se muestra el contenido original.",
    "fr-FR": "Échec du rendu du diagramme. Le contenu brut est affiché à la place.",
    "de-DE": "Diagramm-Rendering fehlgeschlagen. Der Rohinhalt wird angezeigt.",
    "ja-JP": "図の描画に失敗しました。先に元の内容を表示します。",
    "ko-KR": "다이어그램 렌더링에 실패했습니다. 우선 원본 내용을 표시합니다.",
    "pt-BR": "Falha ao renderizar o diagrama. Mostrando o conteúdo original primeiro.",
  },
  "正在渲染…": {
    "en-US": "Rendering…",
    "es-ES": "Renderizando…",
    "fr-FR": "Rendu…",
    "de-DE": "Wird gerendert…",
    "ja-JP": "描画中…",
    "ko-KR": "렌더링 중…",
    "pt-BR": "Renderizando…",
  },
  "行": {
    "en-US": "rows",
    "es-ES": "filas",
    "fr-FR": "lignes",
    "de-DE": "Zeilen",
    "ja-JP": "行",
    "ko-KR": "행",
    "pt-BR": "linhas",
  },
  "列": {
    "en-US": "columns",
    "es-ES": "columnas",
    "fr-FR": "colonnes",
    "de-DE": "Spalten",
    "ja-JP": "列",
    "ko-KR": "열",
    "pt-BR": "colunas",
  },
  "仅预览关键信息": {
    "en-US": "Quick preview only",
    "es-ES": "Solo vista previa de lo clave",
    "fr-FR": "Aperçu rapide uniquement",
    "de-DE": "Nur Kurzvorschau",
    "ja-JP": "要点のみプレビュー",
    "ko-KR": "핵심 미리보기만",
    "pt-BR": "Apenas prévia rápida",
  },
  "没有可显示的行。": {
    "en-US": "No rows available.",
    "es-ES": "No hay filas disponibles.",
    "fr-FR": "Aucune ligne disponible.",
    "de-DE": "Keine Zeilen vorhanden.",
    "ja-JP": "表示できる行はありません。",
    "ko-KR": "표시할 행이 없습니다.",
    "pt-BR": "Nenhuma linha disponível.",
  },
  "可信度": {
    "en-US": "Trust",
    "es-ES": "Confianza",
    "fr-FR": "Confiance",
    "de-DE": "Vertrauen",
    "ja-JP": "信頼度",
    "ko-KR": "신뢰도",
    "pt-BR": "Confiança",
  },
  "下一步：": {
    "en-US": "Next: ",
    "es-ES": "Siguiente: ",
    "fr-FR": "Suivant : ",
    "de-DE": "Weiter: ",
    "ja-JP": "次：",
    "ko-KR": "다음: ",
    "pt-BR": "Próximo: ",
  },
  "决定：": {
    "en-US": "Decision: ",
    "es-ES": "Decisión: ",
    "fr-FR": "Décision : ",
    "de-DE": "Entscheidung: ",
    "ja-JP": "決定：",
    "ko-KR": "결정: ",
    "pt-BR": "Decisão: ",
  },
  "卡点：": {
    "en-US": "Blocker: ",
    "es-ES": "Bloqueo: ",
    "fr-FR": "Blocage : ",
    "de-DE": "Blocker: ",
    "ja-JP": "つまずき：",
    "ko-KR": "막힌 지점: ",
    "pt-BR": "Bloqueio: ",
  },
  "教学提示：": {
    "en-US": "Teaching note: ",
    "es-ES": "Nota didáctica: ",
    "fr-FR": "Note pédagogique : ",
    "de-DE": "Didaktischer Hinweis: ",
    "ja-JP": "教えるポイント：",
    "ko-KR": "학습 팁: ",
    "pt-BR": "Nota de ensino: ",
  },
  "置信度：": {
    "en-US": "Confidence: ",
    "es-ES": "Confianza: ",
    "fr-FR": "Confiance : ",
    "de-DE": "Sicherheit: ",
    "ja-JP": "確度：",
    "ko-KR": "확신도: ",
    "pt-BR": "Confiança: ",
  },
  "训练卡片": {
    "en-US": "Training card",
    "es-ES": "Tarjeta de entrenamiento",
    "fr-FR": "Carte d'entraînement",
    "de-DE": "Trainingskarte",
    "ja-JP": "トレーニングカード",
    "ko-KR": "훈련 카드",
    "pt-BR": "Cartão de treino",
  },
  "计划更新": {
    "en-US": "Plan update",
    "es-ES": "Actualización del plan",
    "fr-FR": "Mise à jour du plan",
    "de-DE": "Plan-Aktualisierung",
    "ja-JP": "プラン更新",
    "ko-KR": "계획 업데이트",
    "pt-BR": "Atualização do plano",
  },
  "测试结果": {
    "en-US": "Test result",
    "es-ES": "Resultado de la prueba",
    "fr-FR": "Résultat du test",
    "de-DE": "Testergebnis",
    "ja-JP": "テスト結果",
    "ko-KR": "테스트 결과",
    "pt-BR": "Resultado do teste",
  },
};

export function coachMessagePartsCopy(language: ComposerLanguage, key: string): string {
  return COACH_MESSAGE_PARTS_TEXT[key]?.[language] ?? key;
}
