/** §十五: coach typed-part renderer copy in eight languages (no zh/en binary). */

import type { ComposerLanguage } from "../../lib/types";

/**
 * Copy used by the typed message-part renderers (parts/index.tsx). The zh-CN
 * source string is the record key — entries whose historical zh text was an
 * English literal use that literal as the key. {id} / {n} / {x} / {op} /
 * {result} / {body} are positional slots and the en-US "{s}" slot keeps the
 * historical plural marker (empty for singular counts).
 */
export const COACH_PARTS_TEXT: Record<string, Record<string, string>> = {
  // Mermaid block chrome
  "Diagram": {
    "en-US": "Diagram",
    "es-ES": "Diagrama",
    "fr-FR": "Diagramme",
    "de-DE": "Diagramm",
    "ja-JP": "ダイアグラム",
    "ko-KR": "다이어그램",
    "pt-BR": "Diagrama",
  },
  "Diagram render failed. Showing the raw content instead.": {
    "en-US": "Diagram render failed. Showing the raw content instead.",
    "es-ES": "Error al renderizar el diagrama. Se muestra el contenido original.",
    "fr-FR": "Échec du rendu du diagramme. Le contenu brut est affiché à la place.",
    "de-DE": "Diagramm-Rendering fehlgeschlagen. Der Rohinhalt wird angezeigt.",
    "ja-JP": "ダイアグラムの描画に失敗しました。元の内容を表示しています。",
    "ko-KR": "다이어그램 렌더링에 실패했습니다. 원본 내용을 대신 표시합니다.",
    "pt-BR": "Falha ao renderizar o diagrama. Exibindo o conteúdo original.",
  },
  "正在渲染…": {
    "en-US": "Rendering…",
    "es-ES": "Renderizando…",
    "fr-FR": "Rendu…",
    "de-DE": "Wird gerendert…",
    "ja-JP": "描画中…",
    "ko-KR": "렌더링 중…",
    "pt-BR": "Renderizando…",
  },

  // Citation part
  "Trust": {
    "en-US": "Trust",
    "es-ES": "Confianza",
    "fr-FR": "Confiance",
    "de-DE": "Vertrauen",
    "ja-JP": "信頼度",
    "ko-KR": "신뢰도",
    "pt-BR": "Confiança",
  },
  "Why it matters: ": {
    "en-US": "Why it matters: ",
    "es-ES": "Por qué importa: ",
    "fr-FR": "Pourquoi c'est important : ",
    "de-DE": "Warum das zählt: ",
    "ja-JP": "重要な理由: ",
    "ko-KR": "중요한 이유: ",
    "pt-BR": "Por que importa: ",
  },

  // Workspace tool-result titles
  "资料删除结果": {
    "en-US": "Resource delete result",
    "es-ES": "Resultado de eliminación del recurso",
    "fr-FR": "Résultat de suppression de la ressource",
    "de-DE": "Ergebnis des Ressourcen-Löschens",
    "ja-JP": "資料削除の結果",
    "ko-KR": "자료 삭제 결과",
    "pt-BR": "Resultado da exclusão do recurso",
  },
  "资料导入结果": {
    "en-US": "Resource import result",
    "es-ES": "Resultado de importación del recurso",
    "fr-FR": "Résultat d'importation de la ressource",
    "de-DE": "Ergebnis des Ressourcen-Imports",
    "ja-JP": "資料取り込みの結果",
    "ko-KR": "자료 가져오기 결과",
    "pt-BR": "Resultado da importação do recurso",
  },
  "工作区写入结果": {
    "en-US": "Workspace write result",
    "es-ES": "Resultado de escritura en el workspace",
    "fr-FR": "Résultat d'écriture dans le workspace",
    "de-DE": "Ergebnis des Workspace-Schreibvorgangs",
    "ja-JP": "ワークスペース書き込みの結果",
    "ko-KR": "워크스페이스 쓰기 결과",
    "pt-BR": "Resultado da escrita no workspace",
  },
  "工作区删除结果": {
    "en-US": "Workspace delete result",
    "es-ES": "Resultado de eliminación del workspace",
    "fr-FR": "Résultat de suppression du workspace",
    "de-DE": "Ergebnis des Workspace-Löschvorgangs",
    "ja-JP": "ワークスペース削除の結果",
    "ko-KR": "워크스페이스 삭제 결과",
    "pt-BR": "Resultado da exclusão do workspace",
  },
  "工作区重命名结果": {
    "en-US": "Workspace rename result",
    "es-ES": "Resultado de renombrado del workspace",
    "fr-FR": "Résultat de renommage du workspace",
    "de-DE": "Ergebnis der Workspace-Umbenennung",
    "ja-JP": "ワークスペース名前変更の結果",
    "ko-KR": "워크스페이스 이름 변경 결과",
    "pt-BR": "Resultado da renomeação do workspace",
  },
  "工作区命令结果": {
    "en-US": "Workspace command result",
    "es-ES": "Resultado del comando del workspace",
    "fr-FR": "Résultat de la commande du workspace",
    "de-DE": "Ergebnis des Workspace-Befehls",
    "ja-JP": "ワークスペースコマンドの結果",
    "ko-KR": "워크스페이스 명령 결과",
    "pt-BR": "Resultado do comando do workspace",
  },
  "工作区清理结果": {
    "en-US": "Workspace cleanup result",
    "es-ES": "Resultado de limpieza del workspace",
    "fr-FR": "Résultat du nettoyage du workspace",
    "de-DE": "Ergebnis der Workspace-Bereinigung",
    "ja-JP": "ワークスペースクリーンアップの結果",
    "ko-KR": "워크스페이스 정리 결과",
    "pt-BR": "Resultado da limpeza do workspace",
  },
  "Workspace result": {
    "en-US": "Workspace result",
    "es-ES": "Resultado del workspace",
    "fr-FR": "Résultat du workspace",
    "de-DE": "Workspace-Ergebnis",
    "ja-JP": "ワークスペースの結果",
    "ko-KR": "워크스페이스 결과",
    "pt-BR": "Resultado do workspace",
  },

  // Workspace tool-result summaries and fact pills
  "已把沙箱副本和 {n} 个派生工件移入当前工作区回收区。": {
    "en-US": "Moved the sandbox copy and {n} derived artifact{s} into the active workspace trash.",
    "es-ES": "La copia de sandbox y {n} artefactos derivados se movieron a la papelera del workspace activo.",
    "fr-FR": "La copie sandbox et {n} artefacts dérivés ont été déplacés vers la corbeille du workspace actif.",
    "de-DE": "Die Sandbox-Kopie und {n} abgeleitete Artefakte wurden in den Papierkorb des aktiven Workspaces verschoben.",
    "ja-JP": "サンドボックスのコピーと {n} 個の派生アーティファクトを現在のワークスペースのゴミ箱へ移動しました。",
    "ko-KR": "샌드박스 사본과 파생 아티팩트 {n}개를 현재 워크스페이스 휴지통으로 옮겼습니다.",
    "pt-BR": "A cópia do sandbox e {n} artefatos derivados foram movidos para a lixeira do workspace ativo.",
  },
  "已把受控资料副本移入当前工作区回收区。": {
    "en-US": "Moved the managed resource copy into the active workspace trash.",
    "es-ES": "La copia gestionada del recurso se movió a la papelera del workspace activo.",
    "fr-FR": "La copie gérée de la ressource a été déplacée vers la corbeille du workspace actif.",
    "de-DE": "Die verwaltete Ressourcenkopie wurde in den Papierkorb des aktiven Workspaces verschoben.",
    "ja-JP": "管理対象の資料コピーを現在のワークスペースのゴミ箱へ移動しました。",
    "ko-KR": "관리되는 자료 사본을 현재 워크스페이스 휴지통으로 옮겼습니다.",
    "pt-BR": "A cópia gerenciada do recurso foi movida para a lixeira do workspace ativo.",
  },
  "已把资料同步到当前工作区边界内，后续索引与预览会围绕受控副本展开。": {
    "en-US": "Synced the resource into the active workspace boundary for governed indexing and preview.",
    "es-ES": "El recurso se sincronizó dentro del límite del workspace activo para una indexación y vista previa gobernadas.",
    "fr-FR": "La ressource a été synchronisée dans la limite du workspace actif pour un indexage et un aperçu gouvernés.",
    "de-DE": "Die Ressource wurde in die Grenze des aktiven Workspaces synchronisiert für gesteuerte Indexierung und Vorschau.",
    "ja-JP": "資料を現在のワークスペース境界内に同期しました。今後の索引とプレビューは管理対象コピーを対象に行われます。",
    "ko-KR": "자료를 현재 워크스페이스 경계 안으로 동기화했습니다. 이후 색인과 미리보기는 관리 사본을 대상으로 진행됩니다.",
    "pt-BR": "O recurso foi sincronizado dentro do limite do workspace ativo para indexação e prévia governadas.",
  },
  "检查点 {id}": {
    "en-US": "Checkpoint {id}",
    "es-ES": "Punto de control {id}",
    "fr-FR": "Point de contrôle {id}",
    "de-DE": "Checkpoint {id}",
    "ja-JP": "チェックポイント {id}",
    "ko-KR": "체크포인트 {id}",
    "pt-BR": "Ponto de verificação {id}",
  },
  "{n} 个 patch 步骤": {
    "en-US": "{n} patch step{s}",
    "es-ES": "{n} pasos de patch",
    "fr-FR": "{n} étapes de patch",
    "de-DE": "{n} Patch-Schritte",
    "ja-JP": "patch ステップ {n} 件",
    "ko-KR": "patch 단계 {n}개",
    "pt-BR": "{n} etapas de patch",
  },
  "{n} 个回收区落点": {
    "en-US": "{n} trash target{s}",
    "es-ES": "{n} destinos de papelera",
    "fr-FR": "{n} cibles de corbeille",
    "de-DE": "{n} Papierkorb-Ziele",
    "ja-JP": "ゴミ箱移動先 {n} 件",
    "ko-KR": "휴지통 대상 {n}곳",
    "pt-BR": "{n} destinos de lixeira",
  },
  "权限 {x}": {
    "en-US": "Permission {x}",
    "es-ES": "Permiso {x}",
    "fr-FR": "Permission {x}",
    "de-DE": "Berechtigung {x}",
    "ja-JP": "権限 {x}",
    "ko-KR": "권한 {x}",
    "pt-BR": "Permissão {x}",
  },
  "账本 {n}": {
    "en-US": "Ledger {n}",
    "es-ES": "Registro {n}",
    "fr-FR": "Registre {n}",
    "de-DE": "Ledger {n}",
    "ja-JP": "台帳 {n}",
    "ko-KR": "장부 {n}",
    "pt-BR": "Registro {n}",
  },
  "检查点总数 {n}": {
    "en-US": "Checkpoints {n}",
    "es-ES": "Puntos de control {n}",
    "fr-FR": "Points de contrôle {n}",
    "de-DE": "Checkpoints {n}",
    "ja-JP": "チェックポイント合計 {n}",
    "ko-KR": "체크포인트 총 {n}",
    "pt-BR": "Pontos de verificação {n}",
  },
  "最近操作 {op} · {result}": {
    "en-US": "Latest op {op} · {result}",
    "es-ES": "Última operación {op} · {result}",
    "fr-FR": "Dernière opération {op} · {result}",
    "de-DE": "Letzter Vorgang {op} · {result}",
    "ja-JP": "最新操作 {op} · {result}",
    "ko-KR": "최근 작업 {op} · {result}",
    "pt-BR": "Última operação {op} · {result}",
  },

  // Tool-result status and details
  "失败": {
    "en-US": "Failed",
    "es-ES": "Fallido",
    "fr-FR": "Échec",
    "de-DE": "Fehlgeschlagen",
    "ja-JP": "失敗",
    "ko-KR": "실패",
    "pt-BR": "Falhou",
  },
  "已确认": {
    "en-US": "Confirmed",
    "es-ES": "Confirmado",
    "fr-FR": "Confirmé",
    "de-DE": "Bestätigt",
    "ja-JP": "確認済み",
    "ko-KR": "확인됨",
    "pt-BR": "Confirmado",
  },
  "待确认": {
    "en-US": "Waiting",
    "es-ES": "En espera",
    "fr-FR": "En attente",
    "de-DE": "Ausstehend",
    "ja-JP": "確認待ち",
    "ko-KR": "대기 중",
    "pt-BR": "Aguardando",
  },
  "Workspace root: ": {
    "en-US": "Workspace root: ",
    "es-ES": "Raíz del workspace: ",
    "fr-FR": "Racine du workspace : ",
    "de-DE": "Workspace-Stamm: ",
    "ja-JP": "ワークスペースルート: ",
    "ko-KR": "워크스페이스 루트: ",
    "pt-BR": "Raiz do workspace: ",
  },
  "Trash root: ": {
    "en-US": "Trash root: ",
    "es-ES": "Raíz de la papelera: ",
    "fr-FR": "Racine de la corbeille : ",
    "de-DE": "Papierkorb-Stamm: ",
    "ja-JP": "ゴミ箱ルート: ",
    "ko-KR": "휴지통 루트: ",
    "pt-BR": "Raiz da lixeira: ",
  },
  "详情": {
    "en-US": "Details",
    "es-ES": "Detalles",
    "fr-FR": "Détails",
    "de-DE": "Details",
    "ja-JP": "詳細",
    "ko-KR": "세부 정보",
    "pt-BR": "Detalhes",
  },
  "工具结果": {
    "en-US": "Tool result",
    "es-ES": "Resultado de la herramienta",
    "fr-FR": "Résultat de l'outil",
    "de-DE": "Tool-Ergebnis",
    "ja-JP": "ツール結果",
    "ko-KR": "도구 결과",
    "pt-BR": "Resultado da ferramenta",
  },
  "动手练习验收": {
    "en-US": "Practice verification",
    "es-ES": "Verificación de práctica",
    "fr-FR": "Vérification de la pratique",
    "de-DE": "Übungsprüfung",
    "ja-JP": "実践確認",
    "ko-KR": "실습 검증",
    "pt-BR": "Verificação de prática",
  },

  // Acceptance feedback
  "已匹配": {
    "en-US": "Matched",
    "es-ES": "Coincidencias",
    "fr-FR": "Correspondances",
    "de-DE": "Getroffen",
    "ja-JP": "一致",
    "ko-KR": "일치",
    "pt-BR": "Correspondidos",
  },
  "个验收信号": {
    "en-US": "acceptance signals",
    "es-ES": "señales de aceptación",
    "fr-FR": "signaux d'acceptation",
    "de-DE": "Abnahmesignale",
    "ja-JP": "件の受け入れシグナル",
    "ko-KR": "개 검수 신호",
    "pt-BR": "sinais de aceitação",
  },
  "下一步：": {
    "en-US": "Next: ",
    "es-ES": "Siguiente: ",
    "fr-FR": "Suivant : ",
    "de-DE": "Weiter: ",
    "ja-JP": "次：",
    "ko-KR": "다음: ",
    "pt-BR": "Próximo: ",
  },

  // Reasoning part
  "Redacted reasoning summary": {
    "en-US": "Redacted reasoning summary",
    "es-ES": "Resumen de razonamiento censurado",
    "fr-FR": "Résumé du raisonnement expurgé",
    "de-DE": "Zusammenfassung des geschwärzten Gedankengangs",
    "ja-JP": "マスキング済みの推論サマリー",
    "ko-KR": "마스킹된 추론 요약",
    "pt-BR": "Resumo de raciocínio censurado",
  },
  "Reasoning summary": {
    "en-US": "Reasoning summary",
    "es-ES": "Resumen de razonamiento",
    "fr-FR": "Résumé du raisonnement",
    "de-DE": "Zusammenfassung des Gedankengangs",
    "ja-JP": "推論サマリー",
    "ko-KR": "추론 요약",
    "pt-BR": "Resumo de raciocínio",
  },
  "Source chain": {
    "en-US": "Source chain",
    "es-ES": "Cadena de fuentes",
    "fr-FR": "Chaîne de sources",
    "de-DE": "Quellenkette",
    "ja-JP": "出典チェーン",
    "ko-KR": "출처 체인",
    "pt-BR": "Cadeia de fontes",
  },
  "Hint ladder & verification": {
    "en-US": "Hint ladder & verification",
    "es-ES": "Escalera de pistas y verificación",
    "fr-FR": "Échelle d'indices et vérification",
    "de-DE": "Hinweisstufen & Prüfung",
    "ja-JP": "ヒント階段と検証",
    "ko-KR": "힌트 단계 및 검증",
    "pt-BR": "Escada de dicas e verificação",
  },
  "Hint ladder": {
    "en-US": "Hint ladder",
    "es-ES": "Escalera de pistas",
    "fr-FR": "Échelle d'indices",
    "de-DE": "Hinweisstufen",
    "ja-JP": "ヒント階段",
    "ko-KR": "힌트 단계",
    "pt-BR": "Escada de dicas",
  },
  "Verification steps": {
    "en-US": "Verification steps",
    "es-ES": "Pasos de verificación",
    "fr-FR": "Étapes de vérification",
    "de-DE": "Prüfschritte",
    "ja-JP": "検証ステップ",
    "ko-KR": "검증 단계",
    "pt-BR": "Etapas de verificação",
  },

  // Training-card part
  "Training card": {
    "en-US": "Training card",
    "es-ES": "Tarjeta de entrenamiento",
    "fr-FR": "Carte d'entraînement",
    "de-DE": "Trainingskarte",
    "ja-JP": "トレーニングカード",
    "ko-KR": "훈련 카드",
    "pt-BR": "Cartão de treino",
  },
  "Surface": {
    "en-US": "Surface",
    "es-ES": "Superficie",
    "fr-FR": "Surface",
    "de-DE": "Oberfläche",
    "ja-JP": "サーフェス",
    "ko-KR": "표면",
    "pt-BR": "Superfície",
  },
  "Source": {
    "en-US": "Source",
    "es-ES": "Fuente",
    "fr-FR": "Source",
    "de-DE": "Quelle",
    "ja-JP": "ソース",
    "ko-KR": "출처",
    "pt-BR": "Fonte",
  },
  "Due": {
    "en-US": "Due",
    "es-ES": "Vence",
    "fr-FR": "Échéance",
    "de-DE": "Fällig",
    "ja-JP": "期限",
    "ko-KR": "기한",
    "pt-BR": "Vence",
  },
  "Interval": {
    "en-US": "Interval",
    "es-ES": "Intervalo",
    "fr-FR": "Intervalle",
    "de-DE": "Intervall",
    "ja-JP": "間隔",
    "ko-KR": "간격",
    "pt-BR": "Intervalo",
  },
  "Stability": {
    "en-US": "Stability",
    "es-ES": "Estabilidad",
    "fr-FR": "Stabilité",
    "de-DE": "Stabilität",
    "ja-JP": "安定度",
    "ko-KR": "안정도",
    "pt-BR": "Estabilidade",
  },
  "Difficulty": {
    "en-US": "Difficulty",
    "es-ES": "Dificultad",
    "fr-FR": "Difficulté",
    "de-DE": "Schwierigkeit",
    "ja-JP": "難易度",
    "ko-KR": "난이도",
    "pt-BR": "Dificuldade",
  },
  "Recall": {
    "en-US": "Recall",
    "es-ES": "Recuerdo",
    "fr-FR": "Rappel",
    "de-DE": "Abruf",
    "ja-JP": "想起",
    "ko-KR": "회상",
    "pt-BR": "Lembrança",
  },
  "FSRS": {
    "en-US": "FSRS",
    "es-ES": "FSRS",
    "fr-FR": "FSRS",
    "de-DE": "FSRS",
    "ja-JP": "FSRS",
    "ko-KR": "FSRS",
    "pt-BR": "FSRS",
  },
  "Deliverable: ": {
    "en-US": "Deliverable: ",
    "es-ES": "Entregable: ",
    "fr-FR": "Livrable : ",
    "de-DE": "Arbeitsergebnis: ",
    "ja-JP": "成果物: ",
    "ko-KR": "산출물: ",
    "pt-BR": "Entregável: ",
  },
  "Verify via: ": {
    "en-US": "Verify via: ",
    "es-ES": "Verificar vía: ",
    "fr-FR": "Vérifier via : ",
    "de-DE": "Prüfen über: ",
    "ja-JP": "検証方法: ",
    "ko-KR": "검증 방법: ",
    "pt-BR": "Verificar via: ",
  },
  "Success signal: ": {
    "en-US": "Success signal: ",
    "es-ES": "Señal de éxito: ",
    "fr-FR": "Signal de succès : ",
    "de-DE": "Erfolgssignal: ",
    "ja-JP": "成功シグナル: ",
    "ko-KR": "성공 신호: ",
    "pt-BR": "Sinal de sucesso: ",
  },
  "Fallback: ": {
    "en-US": "Fallback: ",
    "es-ES": "Alternativa: ",
    "fr-FR": "Repli : ",
    "de-DE": "Fallback: ",
    "ja-JP": "フォールバック: ",
    "ko-KR": "대체 수단: ",
    "pt-BR": "Fallback: ",
  },
  "Then: ": {
    "en-US": "Then: ",
    "es-ES": "Luego: ",
    "fr-FR": "Puis : ",
    "de-DE": "Danach: ",
    "ja-JP": "その後: ",
    "ko-KR": "이후: ",
    "pt-BR": "Depois: ",
  },

  // Plan update and test result parts
  "Plan update": {
    "en-US": "Plan update",
    "es-ES": "Actualización del plan",
    "fr-FR": "Mise à jour du plan",
    "de-DE": "Plan-Aktualisierung",
    "ja-JP": "プラン更新",
    "ko-KR": "계획 업데이트",
    "pt-BR": "Atualização do plano",
  },
  "Test result": {
    "en-US": "Test result",
    "es-ES": "Resultado de la prueba",
    "fr-FR": "Résultat du test",
    "de-DE": "Testergebnis",
    "ja-JP": "テスト結果",
    "ko-KR": "테스트 결과",
    "pt-BR": "Resultado do teste",
  },
};

export function coachPartsCopy(language: ComposerLanguage | undefined, key: string): string {
  return COACH_PARTS_TEXT[key]?.[language ?? "en-US"] ?? key;
}
