/** §十五: coach guidance copy in eight languages (no zh/en binary). */

import type { ComposerLanguage } from "../../lib/types";

/**
 * Guidance sentences and labels. The zh-CN source string is the record key;
 * {n} / {h} / {m} / {d} / {w} / {mo} / {t} are positional slots. The en-US
 * "{s}" slot keeps the historical plural marker (empty for singular counts).
 */
export const COACH_GUIDANCE_TEXT: Record<string, Record<string, string>> = {
  // Streak messages
  "今天还没有练习": {
    "en-US": "No practice yet today",
    "es-ES": "Aún no hay práctica hoy",
    "fr-FR": "Pas encore de pratique aujourd'hui",
    "de-DE": "Heute noch keine Übung",
    "ja-JP": "今日はまだ練習していません",
    "ko-KR": "오늘은 아직 연습하지 않았습니다",
    "pt-BR": "Ainda sem prática hoje",
  },
  "练习已开始": {
    "en-US": "Practice started",
    "es-ES": "La práctica ha comenzado",
    "fr-FR": "La pratique a commencé",
    "de-DE": "Die Übung hat begonnen",
    "ja-JP": "練習を開始しました",
    "ko-KR": "연습을 시작했습니다",
    "pt-BR": "A prática começou",
  },
  "坚持训练，习惯正在养成": {
    "en-US": "Keep training, habits are forming",
    "es-ES": "Sigue entrenando, los hábitos se están formando",
    "fr-FR": "Continuez à vous entraîner, les habitudes se forment",
    "de-DE": "Weiter trainieren, Gewohnheiten bilden sich",
    "ja-JP": "練習を続ければ習慣が身についています",
    "ko-KR": "훈련을 계속하면 습관이 만들어집니다",
    "pt-BR": "Continue treinando, hábitos estão se formando",
  },
  "你已经建立了训练节奏！": {
    "en-US": "You've built a training rhythm!",
    "es-ES": "¡Ya has creado un ritmo de entrenamiento!",
    "fr-FR": "Vous avez établi un rythme d'entraînement !",
    "de-DE": "Du hast einen Trainingsrhythmus aufgebaut!",
    "ja-JP": "トレーニングのリズムが身につきました！",
    "ko-KR": "훈련 리듬이 잡혔습니다!",
    "pt-BR": "Você criou um ritmo de treino!",
  },
  "你的坚持正在产生效果": {
    "en-US": "Your consistency is showing results",
    "es-ES": "Tu constancia está dando resultados",
    "fr-FR": "Votre régularité porte ses fruits",
    "de-DE": "Deine Beständigkeit zeigt Wirkung",
    "ja-JP": "継続が成果を出しています",
    "ko-KR": "꾸준함이 성과를 내고 있습니다",
    "pt-BR": "Sua constância está dando resultados",
  },
  "训练节奏很稳": {
    "en-US": "Training rhythm is steady",
    "es-ES": "El ritmo de entrenamiento es estable",
    "fr-FR": "Le rythme d'entraînement est régulier",
    "de-DE": "Der Trainingsrhythmus ist stabil",
    "ja-JP": "トレーニングのリズムは安定しています",
    "ko-KR": "훈련 리듬이 안정적입니다",
    "pt-BR": "O ritmo de treino está estável",
  },

  // Review-queue messages
  "没有待复习的卡片，休息一下或者挑战新内容": {
    "en-US": "No cards due for review. Take a break or challenge something new",
    "es-ES": "No hay tarjetas para repasar. Descansa o enfrenta algo nuevo",
    "fr-FR": "Aucune carte à réviser. Faites une pause ou relevez un nouveau défi",
    "de-DE": "Keine Karten zur Wiederholung fällig. Mach eine Pause oder fordere etwas Neues",
    "ja-JP": "復習するカードはありません。休むか、新しい内容に挑戦してください",
    "ko-KR": "복습할 카드가 없습니다. 잠시 쉬거나 새로운 내용에 도전해 보세요",
    "pt-BR": "Nenhum cartão para revisar. Faça uma pausa ou desafie algo novo",
  },
  "{n} 张卡片等待复习，保持记忆不丢失": {
    "en-US": "{n} card{s} waiting for review, keep that memory fresh",
    "es-ES": "{n} tarjetas esperando repaso, mantén esa memoria fresca",
    "fr-FR": "{n} cartes en attente de révision, gardez cette mémoire fraîche",
    "de-DE": "{n} Karten warten auf die Wiederholung, halte das Gedächtnis frisch",
    "ja-JP": "{n} 枚のカードが復習待ちです。記憶を鮮明に保ちましょう",
    "ko-KR": "{n}장의 카드가 복습을 기다리고 있습니다. 기억을 잃지 않도록 하세요",
    "pt-BR": "{n} cartões aguardando revisão, mantenha essa memória fresca",
  },
  "你有 {n} 张卡片需要复习，坚持就是胜利": {
    "en-US": "You have {n} card{s} to review. Persistence wins",
    "es-ES": "Tienes {n} tarjetas para repasar. La constancia gana",
    "fr-FR": "Vous avez {n} cartes à réviser. La persévérance gagne",
    "de-DE": "Du hast {n} Karten zu wiederholen. Beharrlichkeit gewinnt",
    "ja-JP": "復習すべきカードが {n} 枚あります。継続は力なり",
    "ko-KR": "복습할 카드가 {n}장 있습니다. 꾸준함이 승리입니다",
    "pt-BR": "Você tem {n} cartões para revisar. Persistência vence",
  },
  "复习队列较长，逐一击破会更有成就感": {
    "en-US": "Review queue is long. Conquer them one by one for a real sense of achievement",
    "es-ES": "La cola de repaso es larga. Véncelas una por una para un logro real",
    "fr-FR": "La file de révision est longue. Vainquez-les une par une pour un vrai sentiment d'accomplissement",
    "de-DE": "Die Wiederholungswarteschlange ist lang. Besiege sie einzeln für ein echtes Erfolgserlebnis",
    "ja-JP": "復習キューが長いです。1 枚ずつ片付けると達成感が高まります",
    "ko-KR": "복습 대기열이 깁니다. 하나씩 정복하면 성취감이 큽니다",
    "pt-BR": "A fila de revisão está longa. Vença-os um por um para uma real sensação de conquista",
  },

  // Time-of-day greetings
  "夜间": {
    "en-US": "Late night",
    "es-ES": "Madrugada",
    "fr-FR": "Nuit tardive",
    "de-DE": "Späte Nacht",
    "ja-JP": "深夜",
    "ko-KR": "새벽",
    "pt-BR": "Madrugada",
  },
  "清晨": {
    "en-US": "Early morning",
    "es-ES": "Temprano en la mañana",
    "fr-FR": "Tôt le matin",
    "de-DE": "Früher Morgen",
    "ja-JP": "早朝",
    "ko-KR": "이른 아침",
    "pt-BR": "Manhã cedinho",
  },
  "上午": {
    "en-US": "Morning",
    "es-ES": "Mañana",
    "fr-FR": "Matinée",
    "de-DE": "Vormittag",
    "ja-JP": "午前",
    "ko-KR": "오전",
    "pt-BR": "Manhã",
  },
  "午间": {
    "en-US": "Noon",
    "es-ES": "Mediodía",
    "fr-FR": "Midi",
    "de-DE": "Mittag",
    "ja-JP": "正午",
    "ko-KR": "정오",
    "pt-BR": "Meio-dia",
  },
  "下午": {
    "en-US": "Afternoon",
    "es-ES": "Tarde",
    "fr-FR": "Après-midi",
    "de-DE": "Nachmittag",
    "ja-JP": "午後",
    "ko-KR": "오후",
    "pt-BR": "Tarde",
  },
  "晚上": {
    "en-US": "Evening",
    "es-ES": "Noche",
    "fr-FR": "Soirée",
    "de-DE": "Abend",
    "ja-JP": "夜",
    "ko-KR": "저녁",
    "pt-BR": "Noite",
  },

  // Contextual guidance items
  "第一步：连接模型": {
    "en-US": "Step 1: Connect a model",
    "es-ES": "Paso 1: Conecta un modelo",
    "fr-FR": "Étape 1 : Connecter un modèle",
    "de-DE": "Schritt 1: Modell verbinden",
    "ja-JP": "ステップ 1: モデルを接続",
    "ko-KR": "1단계: 모델 연결",
    "pt-BR": "Passo 1: Conecte um modelo",
  },
  "填写 provider、模型和 API key。": {
    "en-US": "Set provider, model, and API key.",
    "es-ES": "Configura el proveedor, el modelo y la clave de API.",
    "fr-FR": "Renseignez le fournisseur, le modèle et la clé d'API.",
    "de-DE": "Provider, Modell und API-Schlüssel festlegen.",
    "ja-JP": "provider、モデル、API キーを設定してください。",
    "ko-KR": "provider, 모델, API 키를 설정하세요.",
    "pt-BR": "Defina o provedor, o modelo e a chave de API.",
  },
  "创建一个训练计划": {
    "en-US": "Create a training plan",
    "es-ES": "Crea un plan de entrenamiento",
    "fr-FR": "Créer un plan d'entraînement",
    "de-DE": "Erstelle einen Trainingsplan",
    "ja-JP": "トレーニングプランを作成",
    "ko-KR": "훈련 계획 만들기",
    "pt-BR": "Crie um plano de treino",
  },
  "告诉我目标或当前项目。": {
    "en-US": "Share a goal or current project.",
    "es-ES": "Comparte un objetivo o el proyecto actual.",
    "fr-FR": "Partagez un objectif ou le projet en cours.",
    "de-DE": "Nenne ein Ziel oder das aktuelle Projekt.",
    "ja-JP": "目標や現在のプロジェクトを教えてください。",
    "ko-KR": "목표나 현재 프로젝트를 알려주세요.",
    "pt-BR": "Compartilhe uma meta ou o projeto atual.",
  },
  "生成训练卡片": {
    "en-US": "Generate training cards",
    "es-ES": "Genera tarjetas de entrenamiento",
    "fr-FR": "Générer des cartes d'entraînement",
    "de-DE": "Trainingskarten erstellen",
    "ja-JP": "トレーニングカードを生成",
    "ko-KR": "훈련 카드 생성",
    "pt-BR": "Gere cartões de treino",
  },
  "问一个具体问题开始。": {
    "en-US": "Ask one specific question to begin.",
    "es-ES": "Haz una pregunta concreta para empezar.",
    "fr-FR": "Posez une question précise pour commencer.",
    "de-DE": "Stelle eine konkrete Frage, um zu beginnen.",
    "ja-JP": "具体的な質問をして始めましょう。",
    "ko-KR": "구체적인 질문 하나로 시작하세요.",
    "pt-BR": "Faça uma pergunta específica para começar.",
  },
  "复习提醒": {
    "en-US": "Review reminder",
    "es-ES": "Recordatorio de repaso",
    "fr-FR": "Rappel de révision",
    "de-DE": "Wiederholungserinnerung",
    "ja-JP": "復習リマインダー",
    "ko-KR": "복습 알림",
    "pt-BR": "Lembrete de revisão",
  },
  "可以继续练习": {
    "en-US": "Ready to practice",
    "es-ES": "Listo para practicar",
    "fr-FR": "Prêt à pratiquer",
    "de-DE": "Bereit zum Üben",
    "ja-JP": "練習を続けられます",
    "ko-KR": "연습할 준비가 되었습니다",
    "pt-BR": "Pronto para praticar",
  },
  "今天的复习已完成。": {
    "en-US": "Today's reviews are complete.",
    "es-ES": "Los repasos de hoy están completos.",
    "fr-FR": "Les révisions du jour sont terminées.",
    "de-DE": "Die heutigen Wiederholungen sind erledigt.",
    "ja-JP": "今日の復習は完了しました。",
    "ko-KR": "오늘의 복습을 완료했습니다.",
    "pt-BR": "As revisões de hoje estão completas.",
  },
  "添加学习资料": {
    "en-US": "Add learning materials",
    "es-ES": "Agrega materiales de aprendizaje",
    "fr-FR": "Ajouter des supports d'apprentissage",
    "de-DE": "Lernmaterialien hinzufügen",
    "ja-JP": "学習教材を追加",
    "ko-KR": "학습 자료 추가",
    "pt-BR": "Adicione materiais de aprendizagem",
  },
  "导入代码、文档或网页。": {
    "en-US": "Import code, docs, or web pages.",
    "es-ES": "Importa código, documentos o páginas web.",
    "fr-FR": "Importez du code, des documents ou des pages web.",
    "de-DE": "Code, Dokumente oder Webseiten importieren.",
    "ja-JP": "コード、ドキュメント、Web ページを取り込みましょう。",
    "ko-KR": "코드, 문서, 웹 페이지를 가져오세요.",
    "pt-BR": "Importe código, documentos ou páginas web.",
  },
  "已完成": {
    "en-US": "Completed",
    "es-ES": "Completado",
    "fr-FR": "Terminé",
    "de-DE": "Abgeschlossen",
    "ja-JP": "完了",
    "ko-KR": "완료",
    "pt-BR": "Concluído",
  },
  "待复盘": {
    "en-US": "Needs review",
    "es-ES": "Requiere repaso",
    "fr-FR": "À réviser",
    "de-DE": "Braucht Wiederholung",
    "ja-JP": "要復習",
    "ko-KR": "복습 필요",
    "pt-BR": "Precisa de revisão",
  },
  "技能成长": {
    "en-US": "Skill growth",
    "es-ES": "Crecimiento de habilidades",
    "fr-FR": "Progression des compétences",
    "de-DE": "Fähigkeitsfortschritt",
    "ja-JP": "スキルの成長",
    "ko-KR": "실력 성장",
    "pt-BR": "Crescimento de habilidades",
  },
  "已掌握 {n} 个概念。": {
    "en-US": "{n} concept{s} mastered.",
    "es-ES": "{n} conceptos dominados.",
    "fr-FR": "{n} concepts maîtrisés.",
    "de-DE": "{n} Konzepte gemeistert.",
    "ja-JP": "{n} 個の概念を習得しました。",
    "ko-KR": "{n}개 개념을 마스터했습니다.",
    "pt-BR": "{n} conceitos dominados.",
  },
  "专注时间": {
    "en-US": "Focus time",
    "es-ES": "Tiempo de concentración",
    "fr-FR": "Temps de concentration",
    "de-DE": "Fokuszeit",
    "ja-JP": "集中時間",
    "ko-KR": "집중 시간",
    "pt-BR": "Tempo de foco",
  },
  "你已经投入 {t} 的专注练习。持续的投入会带来质的飞跃。": {
    "en-US": "You've invested {t} of focused practice. Consistent investment leads to breakthroughs.",
    "es-ES": "Has invertido {t} de práctica concentrada. La inversión constante lleva a saltos cualitativos.",
    "fr-FR": "Vous avez investi {t} de pratique concentrée. Un investissement constant mène à des progrès décisifs.",
    "de-DE": "Du hast {t} konzentriertes Üben investiert. Beständig investierte Zeit führt zum Durchbruch.",
    "ja-JP": "これまでに {t} の集中練習を積みました。継続的な積み重ねが飛躍をもたらします。",
    "ko-KR": "{t} 동안 집중적으로 연습했습니다. 꾸준한 투자가 큰 도약을 만듭니다.",
    "pt-BR": "Você investiu {t} de prática focada. O investimento constante leva a saltos qualitativos.",
  },
  "{h} 小时 {m} 分钟": {
    "en-US": "{h}h {m}m",
    "es-ES": "{h} h {m} min",
    "fr-FR": "{h} h {m} min",
    "de-DE": "{h} Std. {m} Min.",
    "ja-JP": "{h} 時間 {m} 分",
    "ko-KR": "{h}시간 {m}분",
    "pt-BR": "{h} h {m} min",
  },
  "{m} 分钟": {
    "en-US": "{m} minutes",
    "es-ES": "{m} minutos",
    "fr-FR": "{m} minutes",
    "de-DE": "{m} Minuten",
    "ja-JP": "{m} 分",
    "ko-KR": "{m}분",
    "pt-BR": "{m} minutos",
  },

  // Motivational messages
  "已连续练习 30 天。": {
    "en-US": "30-day streak.",
    "es-ES": "Racha de 30 días.",
    "fr-FR": "Série de 30 jours.",
    "de-DE": "30-Tage-Serie.",
    "ja-JP": "30 日連続で練習しました。",
    "ko-KR": "30일 연속 연습했습니다.",
    "pt-BR": "Sequência de 30 dias.",
  },
  "已连续练习一周。": {
    "en-US": "One-week streak.",
    "es-ES": "Racha de una semana.",
    "fr-FR": "Série d'une semaine.",
    "de-DE": "Eine-Woche-Serie.",
    "ja-JP": "1 週間連続で練習しました。",
    "ko-KR": "일주일 연속 연습했습니다.",
    "pt-BR": "Sequência de uma semana.",
  },
  "已掌握 50+ 个概念。": {
    "en-US": "50+ concepts mastered.",
    "es-ES": "Más de 50 conceptos dominados.",
    "fr-FR": "Plus de 50 concepts maîtrisés.",
    "de-DE": "50+ Konzepte gemeistert.",
    "ja-JP": "50 以上の概念を習得しました。",
    "ko-KR": "50개 이상 개념을 마스터했습니다.",
    "pt-BR": "Mais de 50 conceitos dominados.",
  },
  "已掌握 10+ 个概念。": {
    "en-US": "10+ concepts mastered.",
    "es-ES": "Más de 10 conceptos dominados.",
    "fr-FR": "Plus de 10 concepts maîtrisés.",
    "de-DE": "10+ Konzepte gemeistert.",
    "ja-JP": "10 以上の概念を習得しました。",
    "ko-KR": "10개 이상 개념을 마스터했습니다.",
    "pt-BR": "Mais de 10 conceitos dominados.",
  },
  "暂无练习记录。": {
    "en-US": "No practice yet.",
    "es-ES": "Aún no hay práctica.",
    "fr-FR": "Pas encore de pratique.",
    "de-DE": "Noch keine Übung.",
    "ja-JP": "まだ練習記録がありません。",
    "ko-KR": "아직 연습 기록이 없습니다.",
    "pt-BR": "Ainda sem prática.",
  },

  // Encouragement messages
  "再试一次。": {
    "en-US": "Try again.",
    "es-ES": "Inténtalo de nuevo.",
    "fr-FR": "Réessaie.",
    "de-DE": "Versuche es erneut.",
    "ja-JP": "もう一度試しましょう。",
    "ko-KR": "다시 시도해 보세요.",
    "pt-BR": "Tente novamente.",
  },
  "再做一遍。": {
    "en-US": "Try one more pass.",
    "es-ES": "Haz otro intento.",
    "fr-FR": "Refais un passage.",
    "de-DE": "Ein weiterer Durchgang.",
    "ja-JP": "もう一周やってみましょう。",
    "ko-KR": "한 번 더 해 보세요.",
    "pt-BR": "Faça mais uma passada.",
  },
  "已通过。": {
    "en-US": "Passed.",
    "es-ES": "Aprobado.",
    "fr-FR": "Réussi.",
    "de-DE": "Bestanden.",
    "ja-JP": "合格です。",
    "ko-KR": "통과했습니다.",
    "pt-BR": "Aprovado.",
  },
  "已掌握这个概念。": {
    "en-US": "Concept mastered.",
    "es-ES": "Concepto dominado.",
    "fr-FR": "Concept maîtrisé.",
    "de-DE": "Konzept gemeistert.",
    "ja-JP": "この概念を習得しました。",
    "ko-KR": "개념을 마스터했습니다.",
    "pt-BR": "Conceito dominado.",
  },
  "继续当前练习。": {
    "en-US": "Continue the current practice.",
    "es-ES": "Continúa la práctica actual.",
    "fr-FR": "Continue la pratique en cours.",
    "de-DE": "Setze die aktuelle Übung fort.",
    "ja-JP": "現在の練習を続けましょう。",
    "ko-KR": "현재 연습을 계속하세요.",
    "pt-BR": "Continue a prática atual.",
  },

  // Relative time
  "刚刚": {
    "en-US": "Just now",
    "es-ES": "Justo ahora",
    "fr-FR": "À l'instant",
    "de-DE": "Gerade eben",
    "ja-JP": "たった今",
    "ko-KR": "방금",
    "pt-BR": "Agora mesmo",
  },
  "{m} 分钟前": {
    "en-US": "{m}m ago",
    "es-ES": "hace {m} min",
    "fr-FR": "il y a {m} min",
    "de-DE": "vor {m} Min.",
    "ja-JP": "{m} 分前",
    "ko-KR": "{m}분 전",
    "pt-BR": "há {m} min",
  },
  "{h} 小时前": {
    "en-US": "{h}h ago",
    "es-ES": "hace {h} h",
    "fr-FR": "il y a {h} h",
    "de-DE": "vor {h} Std.",
    "ja-JP": "{h} 時間前",
    "ko-KR": "{h}시간 전",
    "pt-BR": "há {h} h",
  },
  "{d} 天前": {
    "en-US": "{d}d ago",
    "es-ES": "hace {d} d",
    "fr-FR": "il y a {d} j",
    "de-DE": "vor {d} T.",
    "ja-JP": "{d} 日前",
    "ko-KR": "{d}일 전",
    "pt-BR": "há {d} d",
  },
  "{w} 周前": {
    "en-US": "{w}w ago",
    "es-ES": "hace {w} sem",
    "fr-FR": "il y a {w} sem",
    "de-DE": "vor {w} W.",
    "ja-JP": "{w} 週間前",
    "ko-KR": "{w}주 전",
    "pt-BR": "há {w} sem",
  },
  "{mo} 个月前": {
    "en-US": "{mo}mo ago",
    "es-ES": "hace {mo} meses",
    "fr-FR": "il y a {mo} mois",
    "de-DE": "vor {mo} Mon.",
    "ja-JP": "{mo} か月前",
    "ko-KR": "{mo}개월 전",
    "pt-BR": "há {mo} meses",
  },
};

export function coachGuidanceCopy(language: ComposerLanguage, key: string): string {
  return COACH_GUIDANCE_TEXT[key]?.[language] ?? key;
}
