import { trainerCommandCatalog } from "../../../../shared/src/commands";
import { createEmptyTrainerStreamingState } from "../../../../shared/src/protocol";
import type { BootstrapData } from "./types";

export const mockBootstrapData: BootstrapData = {
  workspaceName: "trainer",
  sessionLabel: "从想法到代码",
  connection: {
    state: "connected",
    provider: {
      name: "MiniMax",
      model: "MiniMax-M3",
      capabilities: {
        chat: true,
        responses: true,
        vision: false,
        embeddings: false,
        tools: false,
        jsonSchema: false,
        structuredOutput: true,
        streaming: true,
      },
    },
  },
  providerConfig: {
    configured: true,
    name: "MiniMax",
    baseUrl: "https://api.minimaxi.com/v1",
    model: "MiniMax-M3",
    apiKeyConfigured: true,
    protocol: "openai_chat_completions_compatible",
    credentialMode: "ui_proxy",
    profileId: "minimax-core",
    profileLabel: "MiniMax Core",
    profileMode: "direct",
    profileCount: 3,
    capabilities: {
      chat: true,
      responses: true,
      vision: false,
      embeddings: false,
      tools: false,
      jsonSchema: false,
      structuredOutput: true,
      streaming: true,
    },
    availableModels: ["MiniMax-M3", "MiniMax-M2.7-highspeed", "MiniMax-M1"],
    resolvedModel: "MiniMax-M3",
    modelListStatus: "ready",
    modelListDetail: "Live models loaded.",
    cacheFetchedAt: "2026-05-02T12:00:00.000Z",
    cacheExpiresAt: "2026-05-03T00:00:00.000Z",
    cacheSource: "live",
    profileHistory: [
      {
        entryId: "history-1",
        fromProfileId: "openai-mini",
        toProfileId: "minimax-core",
        reason: "preview_bootstrap",
        timestamp: "2026-05-02T12:30:00.000Z",
      },
    ],
    providerProfiles: [
      {
        id: "minimax-core",
        label: "MiniMax Core",
        protocol: "openai_chat_completions_compatible",
        mode: "direct",
        credentialMode: "ui_proxy",
        baseUrl: "https://api.minimaxi.com/v1",
        apiKeyRef: "minimax.default",
        model: "MiniMax-M3",
        availableModels: ["MiniMax-M3", "MiniMax-M2.7-highspeed"],
      },
      {
        id: "openai-mini",
        label: "OpenAI Mini",
        protocol: "openai_responses",
        mode: "direct",
        credentialMode: "ui_proxy",
        baseUrl: "https://api.openai.com/v1",
        apiKeyRef: "openai.default",
        model: "gpt-5.1-mini",
        availableModels: ["gpt-5.1-mini", "gpt-5.1"],
      },
      {
        id: "kimi-core",
        label: "Kimi Core",
        protocol: "openai_chat_completions_compatible",
        mode: "direct",
        credentialMode: "ui_proxy",
        baseUrl: "https://api.moonshot.cn/v1",
        apiKeyRef: "kimi.default",
        model: "moonshot-v1-8k",
        availableModels: ["moonshot-v1-8k", "moonshot-v1-32k"],
      },
    ],
    providerDashboard: {
      currentProfile: {
        id: "minimax-core",
        label: "MiniMax Core",
        protocol: "openai_chat_completions_compatible",
        mode: "direct",
        credentialMode: "ui_proxy",
        baseUrl: "https://api.minimaxi.com/v1",
        apiKeyRef: "minimax.default",
        model: "MiniMax-M3",
        availableModels: ["MiniMax-M3", "MiniMax-M2.7-highspeed"],
      },
      templateCount: 6,
      taskBindingCount: 4,
      protocolCatalog: [
        { protocol: "openai_chat_completions_compatible", protocolFamily: "openai", completionLabel: "Chat Completions", endpointHint: "/v1/chat/completions", testMode: "chat" },
        { protocol: "openai_responses", protocolFamily: "openai", completionLabel: "Responses", endpointHint: "/v1/responses", testMode: "responses" },
      ],
      diagnostics: ["Provider profiles refreshed", "Live model list cached"],
    },
    modelErrorCategory: undefined,
    modelStatusCode: undefined,
    modelRetryable: undefined,
  },
  liveContext: {
    activeFile: "/workspace/server/app/llm/provider_service.py",
    activeLanguageId: "python",
    selectionRange: "63:1-85:18",
    selectionPreview: "async def _llm_reply(...): messages = build_coaching_messages(...)",
    diagnosticsSummary: "当前链路有 1 个错误、1 个警告",
    diagnosticErrors: 1,
    diagnosticWarnings: 1,
    documentVersion: 42,
    recentFiles: [
      "/workspace/server/app/llm/provider_service.py",
      "/workspace/server/app/api/routers.py",
      "/workspace/extension/webview/src/app/App.tsx",
    ],
    recentEditedFiles: [
      "/workspace/server/app/api/routers.py",
      "/workspace/extension/src/commands/sessionCommands.ts",
    ],
    relatedFiles: [
      "/workspace/server/app/llm/prompts.py",
      "/workspace/server/app/core/models.py",
    ],
  },
  profile: {
    learnerName: "你",
    goals: [
      "把模糊想法压成清晰的实现步骤",
      "不是只要代码结果，而是借助教练真正理解代码",
    ],
    weeklyHours: 8,
    preferredStyle: "auto",
    answerPolicy: "auto",
    focusAreas: ["实现引导", "项目改造", "工程判断"],
    targetProject: "把当前 Trainer 做成长期代码教练插件",
    preferredRhythm: "一次推进一个很小、可验证的改动切片",
    preferredLearningMode: "先讨论思路，再一起把代码落到文件里",
    onboardingRequest: "先把侧栏体验、连续记忆和计划理解成本压下来",
    projectContext: "当前项目是 VS Code Trainer 插件，前端是 React webview，后端是 FastAPI sidecar。",
  },
  plan: {
    id: "plan-current-thread",
    title: "登录错误提示",
    frozen: false,
    cadence: "每周 4 次专注编码",
    summary: "先改登录失败的提示，对了再补测试。",
    currentStep: "改登录失败的提示。",
    whyNow: "登录失败时提示不对，先改这里。",
    verifyMethod: ["用错的账号登一次，看提示对不对。"],
    nextAfterCurrent: "对了再补测试。",
    stages: [
      {
        id: "s1",
        title: "找到会报错的那段",
        objective: "打开当前文件，找到登录失败时走的那段。",
        status: "done",
      },
      {
        id: "s2",
        title: "改这一处",
        objective: "先改当前文件里这一段，别同时动别的。",
        status: "active",
      },
      {
        id: "s3",
        title: "再补一条登录测试",
        objective: "这一处对了以后，再补一条失败登录的测试。",
        status: "queued",
      },
    ],
    currentStageId: "s2",
  },
  task: {
    id: "task-14",
    title: "改登录失败的提示",
    description:
      "打开当前文件，让提示跟返回码一致。",
    constraints: [
      "不要跳过阅读和规划这一步。",
      "指导必须基于当前仓库，而不是泛泛建议。",
      "必要时要解释每一次代码改动背后的原理。",
    ],
    acceptanceCriteria: [
      "用户知道应该先改哪里，以及为什么从那里开始。",
      "教练能给出明确但不过载的下一步动作。",
      "评审反馈能把实现细节重新连接回工程原理。",
    ],
    nextActionLabel: "继续推进下一步",
  },
  evaluation: {
    headline: "对了再补测试",
    summary: "失败提示还跟返回码对不上，先改这里。",
    passRate: 0.75,
    updatedAt: "刚刚",
    checks: [
      {
        id: "check-1",
        label: "项目上下文",
        status: "pass",
        detail: "当前文件已经打开，可以改这一段错误处理。",
      },
      {
        id: "check-2",
        label: "指导具体度",
        status: "warn",
        detail: "下一步还要收成：改哪一句、怎么跑一次失败登录。",
      },
      {
        id: "check-3",
        label: "原理解释",
        status: "pass",
        detail: "已经能说清为什么提示必须对上返回码。",
      },
      {
        id: "check-4",
        label: "下一步清晰度",
        status: "pending",
        detail: "还没跑过失败登录，不知道提示对不对。",
      },
    ],
    nextStep:
      "用错的账号登一次，看提示对不对。",
  },
  memory: {
    currentFocus: "改登录失败的提示。",
    weakSpots: [
      "改提示时容易只改文案，忘了核对返回码",
      "还没跑一次失败登录就往下改",
    ],
    recentWins: [
      "已经能指出要改当前文件里哪一段",
      "知道提示要跟返回码一致",
    ],
    reviewSummary: "先改这一处，跑一次失败登录，再决定要不要补测试。",
    reviewRhythm: "改完以后，隔天再看一眼提示跟返回码。",
    dueReviews: [
      {
        concept: "错误提示要对上返回码",
        reason: "不看代码，说清错误提示为什么要对上返回码。",
        dueAt: "2026-04-30T12:30:00Z",
        source: "weakness",
        severity: "high",
      },
      {
        concept: "改动边界",
        reason: "回忆为什么先改当前文件这一段，而不是同时动别的文件。",
        dueAt: "2026-05-01T09:00:00Z",
        source: "plan",
        severity: "medium",
      },
    ],
    evidenceQueue: {
      pending: [
        {
          id: "evidence-plan-1",
          summary: "Current plan thread now points at a single file boundary",
          source: "card_result",
          sourceCardId: "card-ui-training-1",
          concepts: ["file boundary", "router slice"],
          outcome: "pass",
          confidence: 0.94,
          timestamp: "2026-04-30T09:20:00Z",
          targetPlanStageId: "s2",
        },
        {
          id: "evidence-plan-2",
          summary: "Workspace context should stay attached to the same thin coaching slice",
          source: "learning_signal",
          concepts: ["workspace context", "coaching slice"],
          outcome: "insight",
          confidence: 0.71,
          timestamp: "2026-04-30T09:24:00Z",
          targetPlanStageId: "s2",
        },
      ],
      deferred: [
        {
          id: "evidence-plan-3",
          summary: "Sandbox resource preview is ready but still waiting for the stable plan thread",
          source: "resource_import",
          concepts: ["sandbox", "resource preview"],
          outcome: "observation",
          confidence: 0.57,
          timestamp: "2026-04-30T09:25:00Z",
          targetPlanStageId: "s3",
          deferredAt: "2026-04-30T09:26:00Z",
          deferralReason: "Wait until the plan thread is stable enough to resume here.",
        },
      ],
      adopted: [
        {
          id: "evidence-plan-4",
          summary: "Five-view IA stays the top-level navigation contract",
          source: "coaching_observation",
          concepts: ["Coach", "Plan", "Resources"],
          outcome: "pass",
          confidence: 0.99,
          timestamp: "2026-04-30T08:50:00Z",
          targetPlanStageId: "s1",
          adopted: true,
          adoptedAt: "2026-04-30T08:55:00Z",
        },
      ],
      rejected: [
        {
          id: "evidence-plan-5",
          summary: "Turning Training into a dashboard was rejected",
          source: "review_queue",
          concepts: ["single-card-first", "dashboard drift"],
          outcome: "fail",
          confidence: 0.91,
          timestamp: "2026-04-29T18:00:00Z",
          targetPlanStageId: "s1",
          rejectedAt: "2026-04-29T18:05:00Z",
          rejectionReason: "Conflicts with the single-card-first contract.",
        },
      ],
      totalCount: 5,
    },
    teachingObservations: [
      "当教练先圈定文件边界，再给下一步，用户更容易进入实现状态。",
      "计划页如果直接表达训练轨迹，理解成本会明显下降。",
      "研究能力最好的呈现方式是融进回复与计划，而不是单独做页面。",
    ],
    activeThread: {
      scenario: "project_adaptation",
      focusArea: "教练主线收束",
      summary: "先把 Trainer 的主线表达压缩成一个更容易续接的教练体验。",
      nextStep: "把对话、计划和连续性记忆接到同一条训练线程里。",
      blocker: "如果信息层级太散，用户会看不清当前到底该做什么。",
      verifiedResult: "",
      updatedAt: "2026-04-30T09:18:00Z",
    },
    workspaceUnderstanding: {
      repoSummary:
        "Trainer 的当前工作区是一个 VS Code 扩展 + FastAPI sidecar 的长周期教练工作台。",
      entryPoints: [
        "/workspace/extension/src/app/App.tsx",
        "/workspace/server/app/api/routers.py",
      ],
      featureLanes: [
        "Coach 负责消息优先的上下文入口，Plan 负责把主线收成可验证的阶段。",
      ],
      riskZones: [
        "不要把首屏做成控制台面板，低理解成本比信息密度更重要。",
      ],
      trainingOpportunities: [
        "先把 workspace path 分类、计划兜底和任务兜底串成一条可恢复链路。",
      ],
      resourceBrief: "Workspace first-look sample for the preview surface.",
      firstLookSummary: {
        folderRole: "existing_engineering",
        projectTypeGuess: "api_service",
        confidence: 0.84,
        whyThisGuess: "The workspace has dependency manifests, source directories, and explicit API/router entry points.",
        entryPoints: [
          "/workspace/server/app/api/routers.py",
          "/workspace/extension/src/core/workbenchData.ts",
        ],
        directoryAnchors: ["server", "extension", "shared"],
        coreModulesOrMaterials: ["routers.py", "workbenchData.ts", "types.ts"],
        riskZones: [
          "The workspace already spans multiple surfaces, so the first slice should stay narrow.",
        ],
        trainingOpportunities: [
          "Use the router boundary as the first verified coaching slice.",
        ],
        unknowns: ["How much of the current workspace is already stabilized."],
        recommendedNextStep: "Start from the router boundary and keep the first coaching slice thin.",
        classificationMethod: "heuristic",
        classifiedAt: "2026-04-30T09:15:00Z",
      },
      updatedAt: "2026-04-30T09:18:00Z",
    },
    selectedResourceDetail: {
      id: "resource-workbench-data",
      title: "workbenchData.ts",
      kind: "code",
      status: "ready",
      summary: "Trainer 的宿主记忆和 workspace boundary 恢复样本。",
      source: "/workspace/extension/src/core/workbenchData.ts",
      canonicalSource: "/workspace/extension/src/core/workbenchData.ts",
      sourceType: "file",
      fileType: "ts",
      projectScope: "current_project",
      trustState: "trusted",
      trustScore: 0.96,
      freshness: "fresh",
      previewTier: "rich",
      previewKind: "code",
      sandboxPath: "/workspace/extension/src/core/workbenchData.ts",
      sandboxOrigin: "sandbox",
      sandboxSyncedAt: "2026-04-30T09:18:00Z",
      sandboxDirty: false,
      updatedAt: "2026-04-30T09:18:00Z",
      sourceItems: ["/workspace/extension/src/core/workbenchData.ts"],
      tags: ["sandbox", "authority", "trainer"],
      warnings: [],
    },
    sandboxPreview: {
      path: "/workspace/extension/src/core/workbenchData.ts",
      relativePath: "knowledge/function-guidance/fetch-json-contract.md",
      title: "fetch-json-contract.md",
      fileKind: "markdown",
      previewTier: "rich",
      previewKind: "markdown",
      languageHint: "md",
      renderedFrom: "sandbox_preview",
      excerpt: "Recover one function contract from hover, signature help, definition, and one real call site.",
      content: "Recover one function contract from hover, signature help, definition, and one real call site.",
      isBinary: false,
      isEditable: true,
      canNativeOpen: true,
      structuredData: {
        root: "/workspace/.trainer-sandbox",
        refreshCommand: "trainer.sandbox.refresh",
      },
      metadata: {
        source: "mock-data",
      },
      assetUri: "file:///workspace/.trainer-sandbox/knowledge/function-guidance/fetch-json-contract.md",
    },
    sandboxState: {
      rootPath: "/workspace/.trainer-sandbox",
      sandboxRootPath: "/workspace/.trainer-sandbox",
      workspaceRootPath: "/workspace",
      activeWorkspaceRoot: "/workspace",
      trashRootPath: "/workspace/.trainer-sandbox/trash",
      managedRoots: ["plan", "cards", "knowledge", "sources", "notes", "outputs"],
      ready: true,
      linkedResourceCount: 1,
      totalFiles: 1,
      totalDirectories: 18,
      totalSizeBytes: 6144,
      lastUpdatedAt: "2026-04-30T09:18:00Z",
      selectedPath: "/workspace/.trainer-sandbox/knowledge/function-guidance/fetch-json-contract.md",
      nodes: [
        { path: "/workspace/.trainer-sandbox/plan", relativePath: "plan", name: "plan", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/cards", relativePath: "cards", name: "cards", nodeKind: "directory", fileKind: "directory", childrenCount: 5 },
        { path: "/workspace/.trainer-sandbox/cards/current", relativePath: "cards/current", name: "current", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/cards/flash", relativePath: "cards/flash", name: "flash", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/cards/practice", relativePath: "cards/practice", name: "practice", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/cards/scenario", relativePath: "cards/scenario", name: "scenario", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/cards/review", relativePath: "cards/review", name: "review", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/knowledge", relativePath: "knowledge", name: "knowledge", nodeKind: "directory", fileKind: "directory", childrenCount: 4 },
        { path: "/workspace/.trainer-sandbox/knowledge/remote", relativePath: "knowledge/remote", name: "remote", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/knowledge/debug", relativePath: "knowledge/debug", name: "debug", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/knowledge/function-guidance", relativePath: "knowledge/function-guidance", name: "function-guidance", nodeKind: "directory", fileKind: "directory", childrenCount: 1 },
        { path: "/workspace/.trainer-sandbox/knowledge/function-guidance/fetch-json-contract.md", relativePath: "knowledge/function-guidance/fetch-json-contract.md", name: "fetch-json-contract.md", nodeKind: "file", fileKind: "markdown", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/knowledge/apis", relativePath: "knowledge/apis", name: "apis", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/sources", relativePath: "sources", name: "sources", nodeKind: "directory", fileKind: "directory", childrenCount: 3 },
        { path: "/workspace/.trainer-sandbox/sources/inbox", relativePath: "sources/inbox", name: "inbox", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/sources/web", relativePath: "sources/web", name: "web", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/sources/folders", relativePath: "sources/folders", name: "folders", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/notes", relativePath: "notes", name: "notes", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
        { path: "/workspace/.trainer-sandbox/outputs", relativePath: "outputs", name: "outputs", nodeKind: "directory", fileKind: "directory", childrenCount: 0 },
      ],
      notes: ["Trainer keeps this workspace sorted as plan / cards / knowledge / sources / notes / outputs."],
      preview: {
        path: "/workspace/.trainer-sandbox/knowledge/function-guidance/fetch-json-contract.md",
        relativePath: "knowledge/function-guidance/fetch-json-contract.md",
        title: "fetch-json-contract.md",
        fileKind: "markdown",
        previewTier: "rich",
        previewKind: "markdown",
        languageHint: "md",
        renderedFrom: "sandbox_state",
        excerpt: "Recover one function contract from hover, signature help, definition, and one real call site.",
        content: "Recover one function contract from hover, signature help, definition, and one real call site.",
        isBinary: false,
        isEditable: true,
        canNativeOpen: true,
        structuredData: {
          root: "/workspace/.trainer-sandbox",
          refreshCommand: "trainer.sandbox.refresh",
        },
        metadata: {
          source: "mock-data",
        },
        assetUri: "file:///workspace/.trainer-sandbox/knowledge/function-guidance/fetch-json-contract.md",
      },
      recentCommands: [
        {
          command: "trainer.sandbox.refresh",
          label: "Refresh sandbox boundary",
          at: "2026-04-30T09:18:00Z",
        },
      ],
      latestCommand: {
        command: "trainer.sandbox.refresh",
        status: "ok",
        at: "2026-04-30T09:18:00Z",
      },
      authority: {
        activeWorkspaceRoot: "/workspace",
        rootUri: "file:///workspace",
        authoritySource: "workspace_authority_service",
        remoteName: "local",
        authorityMode: "local",
        permissionLevel: "read_write",
        permissionLabel: "Read / write",
        allowedOperations: ["read", "write", "preview", "refresh"],
        ledgerEntryCount: 12,
        checkpointCount: 4,
        trashRoot: "/workspace/.trainer-sandbox/trash",
      },
      capabilitySummary: {
        preview: "enabled",
        refresh: "enabled",
        restore: "enabled",
      },
      threatSummary: {
        isolation: "workspace scoped",
        mutability: "controlled",
      },
    },
    memoryEvidence: [
      "登录失败时，提示还跟返回码对不上。",
      "下一步是改登录失败的提示。",
    ],
    workspace: {
      resourceSandbox: {
        configuredPath: "/workspace/.trainer-managed",
        effectivePath: "/workspace/.trainer-managed",
        defaultPath: "/workspace/.trainer-sandbox",
        source: "custom",
        status: "ready",
      },
    },
  },
  workspaceTrainingState: {
    latestTrainingHandoff: {
      candidateId: "candidate-ui-training-1",
      continueIn: "training",
      cardType: "practice",
      cardTitle: "改登录失败的提示",
      learnerDeliverables: [
        "改当前文件里的错误提示文案。",
        "改完能说清改了哪一句。",
      ],
      verificationSteps: [
        "用错的账号登一次。",
        "提示文案和返回码对得上。",
      ],
      returnWith: "把实现结果、验证输出和一个仍未解决的问题带回教练。",
      nextAfterCompletion: "对了再补测试。",
    },
    latestTrainingNextHop: {
      candidateId: "candidate-ui-training-2",
      candidateType: "practice_candidate",
      title: "再补一条登录测试",
      summary: "对了再补测试。",
      whyNow: "这一处还没改完，先别开新任务。",
      continueIn: "training",
      targetKind: "training_card",
      targetId: "card-ui-training-2",
      status: "surfaced",
      nextAfterCompletion: "测试过了再看一眼提示跟返回码。",
    },
    latestTrainingSubmode: "practice",
    latestLearningFocusArea: "登录失败的提示",
    latestLearningFollowup: "改完告诉我结果。",
    latestLearningVerifiedResult: "",
    latestLearningPartialProgress: "文件已经打开，这一处还没改完。",
    selectedCardId: "card-ui-training-1",
    selectedCardType: "practice",
    selectedCardTitle: "改登录失败的提示",
    selectedCardStatus: "active",
    trainingCardCandidates: [
      {
        cardId: "card-ui-training-1",
        type: "practice",
        title: "改登录失败的提示",
        whyNow: "登录失败时提示不对，先改这里。",
        status: "active",
        expectedSymbols: ["TrainingWorkbenchView", "training-proof-card"],
        apiHints: ["TrainingWorkbenchView(props)"],
        /* Training scenario preview:
         * Keep the current card first, narrow the scope, and preserve a clear return path.
         */
        suggestedWorkspaceAction:
          "打开当前文件，改登录失败的提示。",
        scenario:
          "只改登录失败的提示。",
        constraints: [
          "只改当前文件这一段。",
          "先别动别的文件。",
        ],
        problemStatement: "打开当前文件，让提示跟返回码一致。",
        validationMethod: "用错的账号登一次，看提示对不对。",
        successSignal: "用错的账号登一次，看提示对不对。",
        selfCheck: [
          "不打开别的文件，能不能改完这一处？",
          "失败登录时，提示和返回码对得上吗？",
        ],
        filesToTouch: [
          "extension/webview/src/components/training/TrainingWorkbenchView.tsx",
          "extension/webview/src/styles.css",
        ],
        hintLadder: [
          "先找到处理登录失败的那段。",
          "把提示文案改成和返回码一致。",
        ],
        commonMistakes: [
          "只改了文案，没对返回码。",
          "还没跑一次失败登录就去改别的文件。",
        ],
        stuckRecovery: "如果找不到该改哪一段，先在当前文件里搜登录失败的分支。",
        reflectionPrompt: "你改了哪一句，为什么它必须对上返回码？",
      },
    ],
    activeTrainingCardRouting: {
      selectedCardId: "card-ui-training-1",
      selectedCard: {
        cardId: "card-ui-training-1",
        type: "practice",
        title: "改登录失败的提示",
        expectedSymbols: ["TrainingWorkbenchView", "training-proof-card"],
        apiHints: ["TrainingWorkbenchView(props)"],
      },
      whyThisCard: "先改这一处，登录错误就不会再对不上。",
      candidateCount: 2,
      eligibleCount: 1,
    },
    reviewArtifact: {
      id: "review-ui-training-1",
      title: "错误提示有没有对上",
      status: "resolved",
      focusArea: "登录错误提示",
      verifiedResult: "",
      nextSelfImplementationRule: "对了再补测试。",
    },
    scenarioLab: {
      id: "scenario-ui-training-1",
      title: "用错的账号登一次",
      status: "ready",
      learnerDeliverables: ["跑一次失败登录，记下提示和返回码。"],
      verificationSteps: ["提示文案和返回码对得上。"],
      migrateBackGuidance: ["把这次结果带回对话，再决定要不要补测试。"],
    },
    theoryDrill: {
      id: "theory-ui-training-1",
      title: "为什么提示要跟返回码对上",
      status: "in_progress",
      questions: [
        {
          id: "theory-ui-training-q1",
          prompt: "登录失败时，提示为什么要跟返回码一致？",
        },
      ],
    },
    dueReviews: [
      {
        concept: "错误提示要对上返回码",
        reason: "复述为什么失败登录时提示必须对上返回码。",
        source: "plan",
        severity: "high",
      },
    ],
  },
  coachingState: {
    scenario: "project_adaptation",
    answerMode: "guided",
    learnerSignal: "curious",
    summary: "先改登录失败的提示。",
    nextStep: "改完跑一下，看提示对不对。",
    encouragement: "做完这一步再往下。",
    updatedAt: "2026-04-30T09:18:00Z",
  },
  coachTurn: {
    scenario: "project_adaptation",
    learnerSignal: "curious",
    summary: "先把当前这一步做完。",
    nextStep: "改登录失败的提示。",
    encouragement: "做完这一步再往下。",
    activeStage: "改这一处",
    activeTask: "改登录失败的提示",
    dueReviewCount: 2,
    reviewQueueSummary: "有 2 件事做完后值得再看一遍。",
    artifactKinds: ["project_adaptation", "idea_implementation", "principle"],
    suggestedActionTypes: ["task", "plan", "review"],
    backgroundMode: "embedded",
  },
  coachFocus: {
    currentFocus: "登录失败的提示",
    reviewRhythm: "改完以后，隔天再看一眼提示跟返回码。",
    nextStep: "改完跑一下，看提示对不对。",
    activeStage: "改这一处",
    activeTask: "改登录失败的提示",
    scenario: "project_adaptation",
    relationshipStage: "active",
    firstTurnPriority: "",
    strategyPreferenceSummary: "先改当前这一处，再开下一件事。",
    continuitySummary: "改当前文件 -> 跑失败登录 -> 再补测试",
    recentTeachingSignals: [
      "先改当前文件这一段，再开下一件事。",
      "提示必须对上返回码。",
    ],
    teachingObservations: [
      "先圈定当前文件里哪一段，再给下一步，更容易动手。",
      "提示必须对上返回码，否则后面排查会走偏。",
    ],
    recentWins: [
      "已经能指出要改当前文件里哪一段",
    ],
    dueReviewCount: 2,
    language: "zh-CN",
  },
  planRuntimeStatus: {
    currentStage: {
      id: "s2",
      title: "改这一处",
      goal: "先改当前文件里这一段，别同时动别的。",
      status: "active",
    },
    currentMainThread: {
      scenario: "project_adaptation",
      focusArea: "登录失败的提示",
      summary: "先改当前文件里这一段错误处理。",
      nextStep: "改登录失败的提示。",
      currentStep: "改登录失败的提示。",
      whyNow: "登录失败时提示不对，先改这里。",
      verifyMethod: [
        "用错的账号登一次，看提示对不对。",
      ],
      nextAfterCurrent: "对了再补测试。",
    },
    reviewPoints: [
      {
        concept: "错误提示要对上返回码",
        reason: "回看：为什么提示文案要跟返回码对上。",
        severity: "high",
        dueAt: "2026-04-30T12:30:00Z",
        source: "weakness",
      },
      {
        concept: "改动边界",
        reason: "回忆为什么先改当前文件这一段，而不是同时动别的文件。",
        severity: "medium",
        dueAt: "2026-05-01T09:00:00Z",
        source: "plan",
      },
    ],
    coachJudgment: {
      summary: "先把当前这一步做完。",
      teachingGoal: "把这一步做完，确认能跑。",
      supportStrategy: "先把这一处改完，再开下一件事。",
      resumeThread: "下一轮从当前文件这一段接着改。",
    },
    nextTrainingAction:
      "改登录失败的提示。",
    reviewQueueSummary: "有 2 件事做完后值得再看一遍。",
    nextReviewDue: "2026-04-30T12:30:00Z",
    currentStep: "改登录失败的提示。",
    whyNow: "登录失败时提示不对，先改这里。",
    verifyMethod: [
      "用错的账号登一次，看提示对不对。",
    ],
    nextAfterCurrent: "对了再补测试。",
  },
  reviewQueueSummary: "有 2 件事做完后值得再看一遍。",
  nextReviewDue: "2026-04-30T12:30:00Z",
  streamingState: createEmptyTrainerStreamingState(),
  resources: [
    {
      id: "res-1",
      title: "登录错误码对照",
      kind: "markdown",
      status: "ready",
      summary: "登录失败时，常见返回码和对应提示。",
    },
    {
      id: "res-2",
      title: "当前文件错误处理笔记",
      kind: "pdf",
      status: "indexing",
      summary: "当前文件里登录失败分支的改动记录。",
    },
    {
      id: "res-3",
      title: "失败登录检查清单",
      kind: "text",
      status: "ready",
      summary: "改完后用错的账号登一次，看提示对不对。",
    },
  ],
  conversation: [
    {
      id: "m1",
      role: "assistant",
      author: "Trainer",
      body: "我看过当前文件了。先改登录失败的提示。",
      timestamp: "09:15",
    },
    {
      id: "m2",
      role: "user",
      author: "你",
      body: "好，那我先改这一处。你告诉我该动哪一段。",
      timestamp: "09:16",
      attachments: [
        { label: "文件", value: "App.tsx" },
        { label: "相关文件", value: "CoachPlanView.tsx, styles.css" },
      ],
      contextNote: "参考了当前代码上下文",
    },
    {
      id: "m3",
      role: "assistant",
      author: "Trainer",
      body:
        [
          "打开当前文件，改登录失败的提示。",
          "",
          "用错的账号登一次，看提示对不对。",
        ].join("\n"),
      timestamp: "09:17",
      artifacts: [
        {
          kind: "project_adaptation",
          title: "先改登录错误提示",
          summary: "登录失败时，让提示跟返回码一致。",
          bullets: [
            "打开当前文件",
            "改失败提示",
            "用错的账号登一次",
          ],
          focusArea: "登录失败的提示",
          rationale: "登录失败时提示不对，先改这里。",
          verification: [
            "改动能跑",
            "提示和返回码对得上",
          ],
          recommendedAction: "task",
        },
      ],
    },
    {
      id: "m4",
      role: "user",
      author: "你",
      body: "改完了，你帮我看对不对。",
      timestamp: "09:18",
    },
    {
      id: "m5",
      role: "assistant",
      author: "Trainer",
      body:
        [
          "先跑一次失败登录。",
          "",
          "- 用错的账号登一次。",
          "- 看提示对不对。",
          "- 对了再补测试。",
        ].join("\n"),
      timestamp: "09:19",
      artifacts: [
        {
          kind: "idea_implementation",
          title: "这一处怎么验",
          summary: "改完跑一次失败登录，看提示对不对。",
          bullets: [
            "只改当前文件这一段",
            "用错的账号登一次",
            "提示要和返回码对上",
          ],
          focusArea: "登录失败的提示",
          rationale: "这一处还没验过，先别开新任务。",
          verification: [
            "失败登录能跑通",
            "提示和返回码对得上",
          ],
          recommendedAction: "plan",
        },
        {
          kind: "principle",
          title: "为什么提示要跟返回码对上",
          summary: "用户看到的错误，必须能对应到真实失败原因。",
          bullets: [
            "文案对不上返回码，后面排查会走偏",
            "先改这一处，再补测试",
          ],
          focusArea: "错误处理",
          verification: [
            "你能用一句话说清改了哪一句",
          ],
        },
      ],
    },
  ],
  suggestedActions: [
    {
      id: "suggest-1",
      label: "继续改这一处",
      action: "task",
      prompt: "继续看登录失败的提示，先告诉我该改哪一句。",
      focusArea: "登录失败的提示",
      rationale: "这一处还没改完。",
    },
    {
      id: "suggest-2",
      label: "看下一步",
      action: "plan",
      prompt: "这一处改完以后，下一步是补测试还是先跑一次失败登录？",
      focusArea: "登录错误提示",
      rationale: "先确认这一处改完没有。",
    },
    {
      id: "suggest-3",
      label: "检查当前改动",
      action: "review",
      prompt: "看当前文件里的失败提示，跟返回码一致了吗？",
      focusArea: "错误处理",
      rationale: "先核对这一处，再开下一件事。",
    },
  ],
  research: {
    project: {
      id: "research-1",
      title: "后台教练分析",
      description:
        "后台分析帮助教练比对实践、收集依据、收敛更强的实现建议，但不会再成为独立主界面。",
      themes: [
        {
          id: "theme-1",
          title: "想法到代码的引导模式",
          description:
            "比较优秀代码教练如何在真实仓库里把模糊需求压成代码级步骤。",
          duration_weeks: 2,
          status: "active",
          schedule: {
            start_date: "2026-04-28",
            end_date: "2026-05-12",
            cadence: "daily",
            checkpoints: [
              { id: "cp-1", label: "对比 3 条教练工作流", due_date: "2026-05-01", completed: false },
            ],
          },
          threads: [
            {
              id: "thread-1",
              angle: "比较：当用户只有想法没有规格时，教练应该怎样回应。",
              depth: "deep",
              status: "active",
              findings_count: 4,
            },
            {
              id: "thread-2",
              angle: "判断哪些能力应该沉在后端，哪些信息才值得出现在界面上。",
              depth: "medium",
              status: "planning",
              findings_count: 2,
            },
          ],
          artifacts_count: 3,
          created_at: "2026-04-28T09:00:00Z",
          updated_at: "2026-04-30T09:12:00Z",
        },
        {
          id: "theme-2",
          title: "项目改造引导",
          description:
            "整理如何引导用户按自己的目标去改造一个现有项目。",
          duration_weeks: 1,
          status: "planning",
          schedule: {
            start_date: "2026-05-05",
            end_date: "2026-05-12",
            cadence: "weekly",
            checkpoints: [],
          },
          threads: [
            {
              id: "thread-3",
              angle: "定义教练如何从一个完成项目里提炼训练题和改造想法。",
              depth: "shallow",
              status: "planning",
              findings_count: 1,
            },
          ],
          artifacts_count: 1,
          created_at: "2026-04-29T09:00:00Z",
          updated_at: "2026-04-30T08:40:00Z",
        },
      ],
      agent_state: {
        current_role: "critic",
        thinking_log: [
          {
            id: "think-1",
            role: "researcher",
            question: "什么样的代码教练会让人感觉真的有用，而不是泛泛而谈？",
            conclusion: "最能建立信任的，是基于当前仓库给出具体下一步，而不是泛建议。",
            created_at: "2026-04-30T08:30:00Z",
          },
          {
            id: "think-2",
            role: "critic",
            question: "最容易破坏用户信任的是什么？",
            conclusion: "一个看起来很高级但指导很浅的界面，比一个安静但真正懂上下文的教练更糟。",
            created_at: "2026-04-30T08:55:00Z",
          },
        ],
        pending_questions: ["后台分析里到底有多少内容应该直接折进教练回复？"],
        self_review_count: 2,
        current_iteration: 3,
        max_review_rounds: 4,
      },
      gate: {
        messages: [
          {
            id: "rm1",
            role: "assistant",
            author: "研究代理",
            body:
              "目前最清晰的结论是：最好的教练不会把研究做成单独模式，而是把它折进更锋利的指导、更清晰的计划和更准确的评审里。",
            timestamp: "09:05",
          },
          {
            id: "rm2",
            role: "assistant",
            author: "批判者",
            body:
              "任何分析在露出之前，都应该先问一句：它现在真的帮助用户行动了吗，还是只是增加概念负担？",
            timestamp: "09:08",
          },
        ],
        pending_approvals: ["确认把研究结果折进主教练回复，而不是重新做成单独研究流。"],
        notifications: ["当前产品决策完成后，有 1 个后台分析主题可以继续推进。"],
      },
      active_themes_count: 1,
      created_at: "2026-04-28T08:00:00Z",
      updated_at: "2026-04-30T09:12:00Z",
    },
    scheduleStatus: {
      themes: [
        {
          theme_id: "theme-1",
          theme_title: "能力映射漂移",
          status: "active",
          duration_weeks: 2,
          progress_percentage: 38,
          time_elapsed_percentage: 21,
          next_checkpoint: {
            id: "cp-1",
            label: "检查 3 个 provider 的差异",
            due_date: "2026-05-01",
            completed: false,
          },
          overdue_checkpoints: [],
          threads_count: 2,
          artifacts_count: 3,
        },
        {
          theme_id: "theme-2",
          theme_title: "校验体验",
          status: "planning",
          duration_weeks: 1,
          progress_percentage: 5,
          time_elapsed_percentage: 0,
          next_checkpoint: null,
          overdue_checkpoints: [],
          threads_count: 1,
          artifacts_count: 1,
        },
      ],
      themes_needing_advance: ["theme-1"],
      total_checkpoints: 1,
      completed_checkpoints: 0,
    },
  },
  commands: trainerCommandCatalog.map((command) => ({ ...command })),
};
