import { trainerCommands } from '../../../shared/src/commands';

export const EXTENSION_ID = 'trainer';
export const OUTPUT_CHANNEL_NAME = 'Trainer';
export const WORKBENCH_VIEW_TYPE = 'trainer.workbench';
export const TRAINER_SIDEBAR_VIEW_ID = 'trainer.sidebar';

export const COMMAND_IDS = {
  openWorkbench: trainerCommands.openWorkbench,
  configureProvider: trainerCommands.configureProvider,
  saveProvider: trainerCommands.saveProvider,
  clearProvider: trainerCommands.clearProvider,
  testProvider: trainerCommands.testProvider,
  refreshProviderModels: trainerCommands.refreshProviderModels,
  primeProviderModels: 'trainer.provider.primeModels',
  useProviderTemplate: trainerCommands.useProviderTemplate,
  switchProviderProfile: trainerCommands.switchProviderProfile,
  switchProviderModel: trainerCommands.switchProviderModel,
  saveProviderProfile: trainerCommands.saveProviderProfile,
  refreshProviderProfiles: trainerCommands.refreshProviderProfiles,
  openWorkspaceConfig: trainerCommands.openWorkspaceConfig,
  restartSidecar: trainerCommands.restartSidecar,
  stopSidecar: trainerCommands.stopSidecar,
  sendMessage: trainerCommands.sendMessage,
  sendStreamMessage: 'trainer.session.sendStreamMessage',
  cancelStreamMessage: trainerCommands.cancelStreamMessage,
  resumeLatestCoachCheckpoint: trainerCommands.resumeLatestCoachCheckpoint,
  replayLatestCoachCheckpoint: trainerCommands.replayLatestCoachCheckpoint,
  coachRemoteBoundary: trainerCommands.coachRemoteBoundary,
  coachDebugLoop: trainerCommands.coachDebugLoop,
  coachFunctionContract: trainerCommands.coachFunctionContract,
  coachConceptMastery: trainerCommands.coachConceptMastery,
  coachVocabularyRecall: trainerCommands.coachVocabularyRecall,
  coachMathDerivation: trainerCommands.coachMathDerivation,
  coachWritingRevision: trainerCommands.coachWritingRevision,
  coachReadingTransfer: trainerCommands.coachReadingTransfer,
  generatePlan: trainerCommands.generatePlan,
  stageMaterialGenerate: trainerCommands.stageMaterialGenerate,
  updatePlan: trainerCommands.updatePlan,
  createGlobalPlan: trainerCommands.createGlobalPlan,
  linkCurrentProjectPlan: trainerCommands.linkCurrentProjectPlan,
  taskSpecify: trainerCommands.taskSpecify,
  nextTask: trainerCommands.nextTask,
  uploadResource: trainerCommands.uploadResource,
  indexResources: trainerCommands.indexResources,
  searchResources: trainerCommands.searchResources,
  deleteResource: trainerCommands.deleteResource,
  confirmResourceOrganization: trainerCommands.confirmResourceOrganization,
  cancelResourceOrganization: trainerCommands.cancelResourceOrganization,
  restoreResource: trainerCommands.restoreResource,
  refreshResourceTrash: trainerCommands.refreshResourceTrash,
  openResource: trainerCommands.openResource,
  previewSandbox: trainerCommands.previewSandbox,
  createSandboxFile: trainerCommands.createSandboxFile,
  createSandboxDirectory: trainerCommands.createSandboxDirectory,
  renameSandboxPath: trainerCommands.renameSandboxPath,
  deleteSandboxPath: trainerCommands.deleteSandboxPath,
  deleteSandboxPaths: trainerCommands.deleteSandboxPaths,
  restoreSandboxPath: trainerCommands.restoreSandboxPath,
  refreshSandbox: trainerCommands.refreshSandbox,
  revealSandboxPath: trainerCommands.revealSandboxPath,
  chooseSandboxRoot: trainerCommands.chooseSandboxRoot,
  resetSandboxRoot: trainerCommands.resetSandboxRoot,
  chooseManagedDataFolder: trainerCommands.chooseManagedDataFolder,
  resetManagedDataFolder: trainerCommands.resetManagedDataFolder,
  chooseTrainerWorkspaceRoot: trainerCommands.chooseTrainerWorkspaceRoot,
  migrateTrainerWorkspaceRoot: trainerCommands.migrateTrainerWorkspaceRoot,
  backupTrainerWorkspace: trainerCommands.backupTrainerWorkspace,
  restoreTrainerWorkspaceBackup: trainerCommands.restoreTrainerWorkspaceBackup,
  adoptWorkspaceProject: trainerCommands.adoptWorkspaceProject,
  chooseWorkspaceProject: trainerCommands.chooseWorkspaceProject,
  browseWorkspaceProject: trainerCommands.browseWorkspaceProject,
  ignoreWorkspaceProject: trainerCommands.ignoreWorkspaceProject,
  deleteWorkspaceProject: trainerCommands.deleteWorkspaceProject,
  retryWorkspaceAdmission: trainerCommands.retryWorkspaceAdmission,
  continueWorkspaceAdmission: trainerCommands.continueWorkspaceAdmission,
  abandonWorkspaceAdmission: trainerCommands.abandonWorkspaceAdmission,
  evaluateCurrentFile: trainerCommands.evaluateCurrentFile,
  evaluateSelection: trainerCommands.evaluateSelection,
  refreshMemory: trainerCommands.refreshMemory,
  recordUserFeedback: trainerCommands.recordUserFeedback,
  refreshWorkspaceAuthority: trainerCommands.refreshWorkspaceAuthority,
  saveCoachSettings: trainerCommands.saveCoachSettings,
  grantMemoryShare: trainerCommands.grantMemoryShare,
  revokeMemoryShare: trainerCommands.revokeMemoryShare,
  evidenceEnqueue: trainerCommands.evidenceEnqueue,
  evidenceAdopt: trainerCommands.evidenceAdopt,
  evidenceReject: trainerCommands.evidenceReject,
  evidenceDefer: trainerCommands.evidenceDefer,
  evidenceRefreshQueue: trainerCommands.evidenceRefreshQueue,
  trainingCardStatusTransition: trainerCommands.trainingCardStatusTransition,
  trainingGenerateCard: trainerCommands.trainingGenerateCard,
  trainingFlashcardCreate: trainerCommands.trainingFlashcardCreate,
  trainingFlashcardAnswer: trainerCommands.trainingFlashcardAnswer,
  trainingTheoryDrillAnswer: trainerCommands.trainingTheoryDrillAnswer,
  trainingPracticeReturn: trainerCommands.trainingPracticeReturn,
  trainingReflect: trainerCommands.trainingReflect,
  trainingReturn: trainerCommands.trainingReturn,
  trainingReliabilityControl: trainerCommands.trainingReliabilityControl,
  trainingDependencySkillMapAction: trainerCommands.trainingDependencySkillMapAction,
  trainingReviewQueueAction: trainerCommands.trainingReviewQueueAction,
  trainingReviewArtifactAction: trainerCommands.trainingReviewArtifactAction,
  trainingScenarioLabAction: trainerCommands.trainingScenarioLabAction,
  // Internal recovery/training compatibility commands
  trainingRestoreOrchestration: 'trainer.trainingRestore.orchestrate',
  debugRestoreView: 'trainer.debug.restoreView',
  theoryDrillSubmitAnswer: trainerCommands.theoryDrillSubmitAnswer,
  reviewQueueAction: trainerCommands.reviewQueueAction,
  scenarioLabAction: trainerCommands.scenarioLabAction,
  // Research commands kept for internal compatibility
  createResearch: trainerCommands.createResearch,
  addResearchTheme: trainerCommands.addResearchTheme,
  activateResearchTheme: trainerCommands.activateResearchTheme,
  advanceResearch: trainerCommands.advanceResearch,
  researchMessage: trainerCommands.researchMessage,
  researchStreamMessage: 'trainer.research.messageStream',
  approveResearchDecision: trainerCommands.approveResearchDecision,
  getResearchStatus: trainerCommands.getResearchStatus,
} as const;

export const CONTEXT_KEYS = {
  providerConfigured: 'trainer.providerConfigured',
  workspaceTrusted: 'trainer.workspaceTrusted',
  sidecarReady: 'trainer.sidecarReady',
} as const;

export const STORAGE_KEYS = {
  providerConfig: 'trainer.provider.config',
  providerModelCache: 'trainer.provider.modelCache',
  providerProfileRegistry: 'trainer.provider.profileRegistry',
  providerActiveProfileId: 'trainer.provider.activeProfileId',
  providerProfileSwitchHistory: 'trainer.provider.profileSwitchHistory',
  sessionByWorkspacePrefix: 'trainer.session.byWorkspace',
  managedDataFolderByWorkspacePrefix: 'trainer.managedDataFolder.byWorkspace',
  pendingTransferPromotionScope: 'trainer.transfer.pendingPromotionScope',
} as const;

export const SECRET_KEYS = {
  providerApiKeyPrefix: 'trainer.provider.apiKey',
} as const;

export const SIDECAR_DEFAULTS = {
  host: '127.0.0.1',
  portStart: 34891,
  portEnd: 34911,
  healthPath: '/health',
  startupTimeoutMs: 20_000,
  requestTimeoutMs: 15_000,
  providerRequestTimeoutMs: 90_000,
  maxRequestTimeoutMs: 90_000,
} as const;
