/**
 * §十五: language-integrity fact labels, unified into the eight-language
 * record keyed by the zh source (§二十八: these are coaching-quality
 * signals, not debug status — the learner sees them on Settings first
 * screen).
 */

export const LANGUAGE_INTEGRITY_TEXT: Record<string, Partial<Record<string, string>>> = {
  "对话": {
    "en-US": "Chat",
    "es-ES": "Chat",
    "fr-FR": "Chat",
    "de-DE": "Chat",
    "ja-JP": "対話",
    "ko-KR": "대화",
    "pt-BR": "Conversa",
  },
  "流式": {
    "en-US": "Streaming",
    "es-ES": "Streaming",
    "fr-FR": "Streaming",
    "de-DE": "Streaming",
    "ja-JP": "ストリーミング",
    "ko-KR": "스트리밍",
    "pt-BR": "Streaming",
  },
  "声明工具": {
    "en-US": "Declared tools",
    "es-ES": "Herramientas declaradas",
    "fr-FR": "Outils déclarées",
    "de-DE": "Deklarierte Tools",
    "ja-JP": "宣言ツール",
    "ko-KR": "선언된 도구",
    "pt-BR": "Ferramentas declaradas",
  },
  "结构化": {
    "en-US": "Structured",
    "es-ES": "Estructurado",
    "fr-FR": "Structuré",
    "de-DE": "Strukturiert",
    "ja-JP": "構造化",
    "ko-KR": "구조화",
    "pt-BR": "Estruturado",
  },
  "待设置": {
    "en-US": "Setup",
    "es-ES": "Configurar",
    "fr-FR": "À configurer",
    "de-DE": "Einrichten",
    "ja-JP": "未設定",
    "ko-KR": "설정 필요",
    "pt-BR": "Configurar",
  },
  "先保存一组 connection，然后再跑 zh-CN 输入检查。": {
    "en-US": "Save a connection first, then run a zh-CN integrity check.",
    "es-ES": "Guarda primero una conexión y luego ejecuta la prueba de entrada zh-CN.",
    "fr-FR": "Enregistrez d'abord une connexion, puis lancez le test d'entrée zh-CN.",
    "de-DE": "Speichere zuerst eine Verbindung und führe dann den zh-CN-Eingabetest aus.",
    "ja-JP": "まず接続を保存してから、zh-CN 入力チェックを実行してください。",
    "ko-KR": "먼저 연결을 저장한 뒤 zh-CN 입력 검사를 실행하세요.",
    "pt-BR": "Salve primeiro uma conexão e depois execute a verificação de entrada zh-CN.",
  },
  "缺 API key": {
    "en-US": "Add API key",
    "es-ES": "Falta la API key",
    "fr-FR": "Ajoutez la clé API",
    "de-DE": "API-Key fehlt",
    "ja-JP": "API キーを追加",
    "ko-KR": "API 키 추가",
    "pt-BR": "Adicione a API key",
  },
  "补上 API key 后，再验证 zh-CN 输入是否完整。": {
    "en-US": "Add an API key before checking zh-CN input integrity.",
    "es-ES": "Añade la API key y luego verifica la integridad de la entrada zh-CN.",
    "fr-FR": "Ajoutez la clé API puis vérifiez l'intégrité de l'entrée zh-CN.",
    "de-DE": "Füge den API-Key hinzu und prüfe dann die zh-CN-Eingabevollständigkeit.",
    "ja-JP": "API キーを追加してから、zh-CN 入力の整合性を検証してください。",
    "ko-KR": "API 키를 추가한 뒤 zh-CN 입력 완전성을 검증하세요.",
    "pt-BR": "Adicione a API key e depois verifique a integridade da entrada zh-CN.",
  },
  "请先换服务": {
    "en-US": "Chinese blocked",
    "es-ES": "Chino bloqueado",
    "fr-FR": "Chinois bloqué",
    "de-DE": "Chinesisch blockiert",
    "ja-JP": "中国語ブロック",
    "ko-KR": "중국어 차단",
    "pt-BR": "Chinês bloqueado",
  },
  "这条连接在发送中文时出了问题。请更换模型服务或访问地址，或者暂时用英文继续。": {
    "en-US": "This connection corrupts zh-CN input before the model sees it. Switch provider or gateway, or use English for now.",
    "es-ES": "Esta conexión corrompe la entrada zh-CN. Cambia el servicio o la dirección, o continúa en inglés.",
    "fr-FR": "Cette connexion corrompt l'entrée zh-CN. Changez de service ou d'adresse, ou continuez en anglais.",
    "de-DE": "Diese Verbindung beschädigt zh-CN-Eingaben. Wechsle den Dienst oder die Adresse, oder fahre auf Englisch fort.",
    "ja-JP": "この接続は zh-CN 入力を破損させます。サービスかアドレスを変更するか、英語で続行してください。",
    "ko-KR": "이 연결은 zh-CN 입력을 손상시킵니다. 서비스나 주소를 변경하거나 영어로 계속하세요.",
    "pt-BR": "Esta conexão corrompe a entrada zh-CN. Troque o serviço ou endereço, ou continue em inglês.",
  },
  "待验证": {
    "en-US": "Needs zh-CN test",
    "es-ES": "Requiere prueba zh-CN",
    "fr-FR": "Test zh-CN requis",
    "de-DE": "zh-CN-Test erforderlich",
    "ja-JP": "zh-CN 検証が必要",
    "ko-KR": "zh-CN 검증 필요",
    "pt-BR": "Requer teste zh-CN",
  },
  "连接可以使用，但中文内容还没有验证完成。请先重新测试；必要时可暂时用英文继续。": {
    "en-US": "The connection is reachable, but zh-CN input is not fully verified yet. English fallback is safer until you retest.",
    "es-ES": "La conexión funciona pero la entrada zh-CN no está verificada. Vuelve a probar; si es necesario continúa en inglés.",
    "fr-FR": "La connexion fonctionne mais l'entrée zh-CN n'est pas vérifiée. Retestez ; si nécessaire continuez en anglais.",
    "de-DE": "Die Verbindung funktioniert, aber zh-CN-Eingaben sind nicht überprüft. Teste erneut; bei Bedarf auf Englisch fortsetzen.",
    "ja-JP": "接続は可能ですが zh-CN 入力は未検証です。再テストしてください。必要なら英語で続行できます。",
    "ko-KR": "연결은 가능하지만 zh-CN 입력이 검증되지 않았습니다. 다시 테스트하세요. 필요시 영어로 계속할 수 있습니다.",
    "pt-BR": "A conexão funciona mas a entrada zh-CN não foi verificada. Teste novamente; se necessário continue em inglês.",
  },
  "已验证": {
    "en-US": "Verified",
    "es-ES": "Verificado",
    "fr-FR": "Vérifié",
    "de-DE": "Verifiziert",
    "ja-JP": "検証済み",
    "ko-KR": "검증됨",
    "pt-BR": "Verificado",
  },
  "最近一次测试已经确认 zh-CN 输入能完整到达模型。": {
    "en-US": "The latest test confirmed zh-CN input reaches the model intact.",
    "es-ES": "La última prueba confirmó que la entrada zh-CN llega completa al modelo.",
    "fr-FR": "Le dernier test a confirmé que l'entrée zh-CN atteint complètement le modèle.",
    "de-DE": "Der letzte Test bestätigte, dass zh-CN-Eingaben das Modell vollständig erreichen.",
    "ja-JP": "最新のテストで zh-CN 入力がモデルに完全に到達することを確認しました。",
    "ko-KR": "최근 테스트에서 zh-CN 입력이 모델에 완전히 도달함을 확인했습니다.",
    "pt-BR": "O último teste confirmou que a entrada zh-CN chega completamente ao modelo.",
  },
  "检查中": {
    "en-US": "Checking",
    "es-ES": "Verificando",
    "fr-FR": "Vérification",
    "de-DE": "Wird geprüft",
    "ja-JP": "確認中",
    "ko-KR": "확인 중",
    "pt-BR": "Verificando",
  },
  "等这组 provider 完成 model 确认后，再跑 zh-CN 输入检查。": {
    "en-US": "Wait for model discovery to finish, then rerun the zh-CN check.",
    "es-ES": "Espera a que el proveedor complete la confirmación del modelo, luego ejecuta la prueba zh-CN.",
    "fr-FR": "Attendez que le fournisseur termine la confirmation du modèle, puis lancez le test zh-CN.",
    "de-DE": "Warte bis der Anbieter die Modell-Bestätigung abgeschlossen hat, dann führe den zh-CN-Test aus.",
    "ja-JP": "プロバイダーがモデル確認を完了してから、zh-CN 入力チェックを実行してください。",
    "ko-KR": "공급자가 모델 확인을 완료하면 zh-CN 입력 검사를 실행하세요.",
    "pt-BR": "Aguarde o provedor concluir a confirmação do modelo, depois execute a verificação zh-CN.",
  },
  "待恢复": {
    "en-US": "Unavailable",
    "es-ES": "No disponible",
    "fr-FR": "Indisponible",
    "de-DE": "Nicht verfügbar",
    "ja-JP": "利用不可",
    "ko-KR": "사용 불가",
    "pt-BR": "Indisponível",
  },
  "先把 chat connection 恢复到可用，然后再检查 zh-CN 输入完整性。": {
    "en-US": "Recover the chat connection first, then verify zh-CN input integrity.",
    "es-ES": "Recupera la conexión de chat primero, luego verifica la integridad de la entrada zh-CN.",
    "fr-FR": "Rétablissez d'abord la connexion de chat, puis vérifiez l'intégrité de l'entrée zh-CN.",
    "de-DE": "Stelle zuerst die Chat-Verbindung wieder her, dann prüfe die zh-CN-Eingabevollständigkeit.",
    "ja-JP": "まずチャット接続を復旧してから、zh-CN 入力の整合性を確認してください。",
    "ko-KR": "먼저 채팅 연결을 복구한 뒤 zh-CN 입력 완전성을 확인하세요.",
    "pt-BR": "Recupere primeiro a conexão de chat, depois verifique a integridade da entrada zh-CN.",
  },
  "未测 zh-CN": {
    "en-US": "zh-CN not tested",
    "es-ES": "zh-CN sin probar",
    "fr-FR": "zh-CN non testé",
    "de-DE": "zh-CN ungetestet",
    "ja-JP": "zh-CN 未テスト",
    "ko-KR": "zh-CN 미테스트",
    "pt-BR": "zh-CN não testado",
  },
  "这条 connection 已通过测试，但最近一次还不是 zh-CN 输入。如果你要用中文教练，请再跑一次 zh-CN 测试。": {
    "en-US": "This connection passed a test, but not with zh-CN input. Run one zh-CN test before relying on Chinese coaching.",
    "es-ES": "This connection passed a test, but not with zh-CN input. Run one zh-CN test before relying on Chinese coaching.",
    "fr-FR": "This connection passed a test, but not with zh-CN input. Run one zh-CN test before relying on Chinese coaching.",
    "de-DE": "This connection passed a test, but not with zh-CN input. Run one zh-CN test before relying on Chinese coaching.",
    "ja-JP": "This connection passed a test, but not with zh-CN input. Run one zh-CN test before relying on Chinese coaching.",
    "ko-KR": "This connection passed a test, but not with zh-CN input. Run one zh-CN test before relying on Chinese coaching.",
    "pt-BR": "This connection passed a test, but not with zh-CN input. Run one zh-CN test before relying on Chinese coaching.",
  },
  "待测试": {
    "en-US": "Run test",
    "es-ES": "Ejecutar prueba",
    "fr-FR": "Lancer le test",
    "de-DE": "Test starten",
    "ja-JP": "テスト実行",
    "ko-KR": "테스트 실행",
    "pt-BR": "Executar teste",
  },
  "连接已可用，但 zh-CN 输入还没有真正验证过。": {
    "en-US": "The connection can work, but zh-CN input has not been verified yet.",
    "es-ES": "La conexión funciona, pero la entrada zh-CN aún no ha sido realmente verificada.",
    "fr-FR": "La connexion fonctionne, mais l'entrée zh-CN n'a pas encore été réellement vérifiée.",
    "de-DE": "Die Verbindung funktioniert, aber zh-CN-Eingaben wurden noch nicht wirklich überprüft.",
    "ja-JP": "接続は可能ですが、zh-CN 入力はまだ実際に検証されていません。",
    "ko-KR": "연결은 가능하지만 zh-CN 입력이 아직 실제로 검증되지 않았습니다.",
    "pt-BR": "A conexão funciona, mas a entrada zh-CN ainda não foi realmente verificada.",
  },
};

/** Resolves the active-language text for a language-integrity label. */
export function languageIntegrityText(
  language: string,
  zh: string,
  en: string,
): string {
  const entry = LANGUAGE_INTEGRITY_TEXT[zh];
  return entry?.[language] ?? en;
}
