/**
 * §十五: Settings zh/en ternary strings, unified into one eight-language
 * record keyed by [zh, en] (both call-site arguments — this keeps the two
 * `可发送` sites with different English resolvable). `settingsText`
 * resolves the active language with an en fallback; technical vocabulary
 * (protocol/catalog nouns) deliberately stays English across locales.
 */
import type { ComposerLanguage } from "../../lib/types";


export const SETTINGS_TEXT: Record<string, Partial<Record<ComposerLanguage, string>>> = {
  "先选择协议，再填写服务根地址。未知网关不会被默认成 OpenAI 兼容。\u0000Select a protocol before entering the service root. Unknown gateways are not assumed OpenAI-compatible.": {
    "en-US": "Select a protocol before entering the service root. Unknown gateways are not assumed OpenAI-compatible.",
    "es-ES": "Elige un protocolo antes de escribir la raíz del servicio. Los gateways desconocidos no se asumen OpenAI-compatible.",
    "fr-FR": "Choisissez un protocole avant de saisir la racine du service. Les gateways inconnus ne sont pas considérés OpenAI-compatible.",
    "de-DE": "Wähle zuerst ein Protokoll, bevor du die Service-Root eingibst. Unbekannte Gateways gelten nicht als OpenAI-kompatibel.",
    "ja-JP": "プロトコルを選んでからサービスルートを入力してください。未知のゲートウェイは OpenAI 互換とみなしません。",
    "ko-KR": "서비스 루트를 입력하기 전에 프로토콜을 선택하세요. 알 수 없는 게이트웨이는 OpenAI 호환으로 간주하지 않습니다.",
    "pt-BR": "Escolha um protocolo antes de digitar a raiz do serviço. Gateways desconhecidos não são tratados como OpenAI-compatível.",
  },
  "未声明\u0000Not declared": {
    "en-US": "Not declared",
    "es-ES": "Sin declarar",
    "fr-FR": "Non déclaré",
    "de-DE": "Nicht deklariert",
    "ja-JP": "未宣言",
    "ko-KR": "선언 안 됨",
    "pt-BR": "Não declarado",
  },
  "已识别 New API 网关。目录里的 endpoint 类型只是声明，要以测试结果为准。\u0000New API gateway identified. Catalog endpoint types are claims; use the live test.": {
    "en-US": "New API gateway identified. Catalog endpoint types are claims; use the live test.",
    "es-ES": "Gateway New API identificado. Los tipos de endpoint del catálogo son declaraciones; usa la prueba real.",
    "fr-FR": "Gateway New API identifié. Les types d'endpoint du catalogue sont des déclarations ; fiez-vous au test réel.",
    "de-DE": "New-API-Gateway erkannt. Die Endpoint-Typen im Katalog sind Angaben; verlasse dich auf den Live-Test.",
    "ja-JP": "New API ゲートウェイを認識しました。カタログの endpoint 型は申告であり、実テストを基準にしてください。",
    "ko-KR": "New API 게이트웨이를 확인했습니다. 카탈로그의 endpoint 유형은 신고일 뿐, 실제 테스트를 기준으로 하세요.",
    "pt-BR": "Gateway New API identificado. Os tipos de endpoint do catálogo são declarações; use o teste real.",
  },
  "未选择协议\u0000Protocol unverified": {
    "en-US": "Protocol unverified",
    "es-ES": "Protocolo sin verificar",
    "fr-FR": "Protocole non vérifié",
    "de-DE": "Protokoll unbeprüft",
    "ja-JP": "プロトコル未検証",
    "ko-KR": "프로토콜 미검증",
    "pt-BR": "Protocolo não verificado",
  },
  "可发送\u0000Ready": {
    "en-US": "Ready",
    "es-ES": "Ready",
    "fr-FR": "Ready",
    "de-DE": "Ready",
    "ja-JP": "Ready",
    "ko-KR": "Ready",
    "pt-BR": "Pronto",
  },
  "需补密钥\u0000Add API key": {
    "en-US": "Add API key",
    "es-ES": "Falta la API key",
    "fr-FR": "Ajoutez la clé API",
    "de-DE": "API-Key fehlt",
    "ja-JP": "API キーを追加",
    "ko-KR": "API 키 추가",
    "pt-BR": "Adicione a API key",
  },
  "需检查\u0000Needs attention": {
    "en-US": "Needs attention",
    "es-ES": "Necesita atención",
    "fr-FR": "À vérifier",
    "de-DE": "Braucht Aufmerksamkeit",
    "ja-JP": "要確認",
    "ko-KR": "점검 필요",
    "pt-BR": "Precisa de atenção",
  },
  "待配置\u0000Setup": {
    "en-US": "Setup",
    "es-ES": "Configurar",
    "fr-FR": "À configurer",
    "de-DE": "Einrichten",
    "ja-JP": "未設定",
    "ko-KR": "설정 필요",
    "pt-BR": "Configurar",
  },
  "请检查连接设置后重试。\u0000Check the connection settings and try again.": {
    "en-US": "Check the connection settings and try again.",
    "es-ES": "Revisa la configuración de conexión e inténtalo de nuevo.",
    "fr-FR": "Vérifiez les paramètres de connexion et réessayez.",
    "de-DE": "Prüfe die Verbindungseinstellungen und versuche es erneut.",
    "ja-JP": "接続設定を確認して、もう一度お試しください。",
    "ko-KR": "연결 설정을 확인한 뒤 다시 시도하세요.",
    "pt-BR": "Verifique as configurações de conexão e tente novamente.",
  },
  "已生成\u0000Available": {
    "en-US": "Available",
    "es-ES": "Disponible",
    "fr-FR": "Disponible",
    "de-DE": "Verfügbar",
    "ja-JP": "生成済み",
    "ko-KR": "생성됨",
    "pt-BR": "Disponível",
  },
  "新 API key\u0000New API key": {
    "en-US": "New API key",
    "es-ES": "Nueva API key",
    "fr-FR": "Nouvelle clé API",
    "de-DE": "Neuer API-Key",
    "ja-JP": "新しい API キー",
    "ko-KR": "새 API 키",
    "pt-BR": "Nova API key",
  },
  "连接已保存，还需要 API key。\u0000Connection saved; API key missing.": {
    "en-US": "Connection saved; API key missing.",
    "es-ES": "Conexión guardada; falta la API key.",
    "fr-FR": "Connexion enregistrée ; clé API manquante.",
    "de-DE": "Verbindung gespeichert; API-Key fehlt.",
    "ja-JP": "接続は保存済みです。API キーが必要です。",
    "ko-KR": "Connection saved; API key missing.",
    "pt-BR": "Conexão salva; falta a API key.",
  },
  "这个工作区还没有启用连接。下方有可以直接使用的连接配置。\u0000There is no active provider applied yet. Reusable profiles are still available below.": {
    "en-US": "There is no active provider applied yet. Reusable profiles are still available below.",
    "es-ES": "Todavía no hay un proveedor activo. Abajo hay perfiles reutilizables.",
    "fr-FR": "Aucun fournisseur actif pour l'instant. Des profils réutilisables sont disponibles ci-dessous.",
    "de-DE": "Es ist noch kein Anbieter aktiv. Wiederverwendbare Profile findest du unten.",
    "ja-JP": "まだ有効なプロバイダーがありません。下に再利用可能なプロファイルがあります。",
    "ko-KR": "아직 활성화된 공급자가 없습니다. 아래에 재사용 가능한 프로필이 있습니다.",
    "pt-BR": "Ainda não há provedor ativo. Perfis reutilizáveis estão disponíveis abaixo.",
  },
  "Trainer 会按 model 记住 Context window 和 Max output。切到某个 model 时，会自动带回它自己的 limits。\u0000Trainer keeps Context window and Max output per model and restores them when you switch models.": {
    "en-US": "Trainer keeps Context window and Max output per model and restores them when you switch models.",
    "es-ES": "Trainer keeps Context window and Max output per model and restores them when you switch models.",
    "fr-FR": "Trainer keeps Context window and Max output per model and restores them when you switch models.",
    "de-DE": "Trainer keeps Context window and Max output per model and restores them when you switch models.",
    "ja-JP": "Trainer keeps Context window and Max output per model and restores them when you switch models.",
    "ko-KR": "Trainer keeps Context window and Max output per model and restores them when you switch models.",
    "pt-BR": "Trainer keeps Context window and Max output per model and restores them when you switch models.",
  },
  "用这个 model\u0000Use model": {
    "en-US": "Use model",
    "es-ES": "Use model",
    "fr-FR": "Use model",
    "de-DE": "Use model",
    "ja-JP": "Use model",
    "ko-KR": "Use model",
    "pt-BR": "Use model",
  },
  "当前\u0000Current": {
    "en-US": "Current",
    "es-ES": "Current",
    "fr-FR": "Current",
    "de-DE": "Current",
    "ja-JP": "Current",
    "ko-KR": "Current",
    "pt-BR": "Current",
  },
  "先拉取模型列表，或者直接输入一个 model。\u0000Fetch models first,or type a model name directly.": {
    "en-US": "Fetch models first, or type a model name directly.",
    "es-ES": "Fetch models first, or type a model name directly.",
    "fr-FR": "Fetch models first, or type a model name directly.",
    "de-DE": "Fetch models first, or type a model name directly.",
    "ja-JP": "Fetch models first, or type a model name directly.",
    "ko-KR": "Fetch models first, or type a model name directly.",
    "pt-BR": "Fetch models first, or type a model name directly.",
  },
  "Trainer 会按这些已保存的 model 细节来做自动切换、profile 切换和 live refresh。\u0000Trainer uses these saved model details when it switches models,swaps profiles,and refreshes live catalogs.": {
    "en-US": "Trainer uses these saved model details when it switches models, swaps profiles, and refreshes live catalogs.",
    "es-ES": "Trainer uses these saved model details when it switches models, swaps profiles, and refreshes live catalogs.",
    "fr-FR": "Trainer uses these saved model details when it switches models, swaps profiles, and refreshes live catalogs.",
    "de-DE": "Trainer uses these saved model details when it switches models, swaps profiles, and refreshes live catalogs.",
    "ja-JP": "Trainer uses these saved model details when it switches models, swaps profiles, and refreshes live catalogs.",
    "ko-KR": "Trainer uses these saved model details when it switches models, swaps profiles, and refreshes live catalogs.",
    "pt-BR": "Trainer uses these saved model details when it switches models, swaps profiles, and refreshes live catalogs.",
  },
  "Model aliases\u0000Model aliases": {
    "en-US": "Model aliases",
    "es-ES": "Model aliases",
    "fr-FR": "Model aliases",
    "de-DE": "Model aliases",
    "ja-JP": "Model aliases",
    "ko-KR": "Model aliases",
    "pt-BR": "Model aliases",
  },
  "Task bindings\u0000Task bindings": {
    "en-US": "Task bindings",
    "es-ES": "Task bindings",
    "fr-FR": "Task bindings",
    "de-DE": "Task bindings",
    "ja-JP": "Task bindings",
    "ko-KR": "Task bindings",
    "pt-BR": "Task bindings",
  },
  "Allowed models\u0000Allowed models": {
    "en-US": "Allowed models",
    "es-ES": "Allowed models",
    "fr-FR": "Allowed models",
    "de-DE": "Allowed models",
    "ja-JP": "Allowed models",
    "ko-KR": "Allowed models",
    "pt-BR": "Allowed models",
  },
  "Blocked models\u0000Blocked models": {
    "en-US": "Blocked models",
    "es-ES": "Blocked models",
    "fr-FR": "Blocked models",
    "de-DE": "Blocked models",
    "ja-JP": "Blocked models",
    "ko-KR": "Blocked models",
    "pt-BR": "Blocked models",
  },
  "Embedding model\u0000Embedding model": {
    "en-US": "Embedding model",
    "es-ES": "Embedding model",
    "fr-FR": "Embedding model",
    "de-DE": "Embedding model",
    "ja-JP": "Embedding model",
    "ko-KR": "Embedding model",
    "pt-BR": "Embedding model",
  },
  "Request defaults\u0000Request defaults": {
    "en-US": "Request defaults",
    "es-ES": "Request defaults",
    "fr-FR": "Request defaults",
    "de-DE": "Request defaults",
    "ja-JP": "Request defaults",
    "ko-KR": "Request defaults",
    "pt-BR": "Request defaults",
  },
  "Catalog source\u0000Catalog source": {
    "en-US": "Catalog source",
    "es-ES": "Catalog source",
    "fr-FR": "Catalog source",
    "de-DE": "Catalog source",
    "ja-JP": "Catalog source",
    "ko-KR": "Catalog source",
    "pt-BR": "Catalog source",
  },
  "Cache TTL\u0000Cache TTL": {
    "en-US": "Cache TTL",
    "es-ES": "Cache TTL",
    "fr-FR": "Cache TTL",
    "de-DE": "Cache TTL",
    "ja-JP": "Cache TTL",
    "ko-KR": "Cache TTL",
    "pt-BR": "Cache TTL",
  },
  "路由规则\u0000Routing rules": {
    "en-US": "Routing rules",
    "es-ES": "Routing rules",
    "fr-FR": "Routing rules",
    "de-DE": "Routing rules",
    "ja-JP": "Routing rules",
    "ko-KR": "Routing rules",
    "pt-BR": "Routing rules",
  },
  "这里放会影响 provider profile 行为的高级字段。默认收起，不抢首屏。\u0000These fields shape provider profile behavior. They stay collapsed by default so Settings keeps its first screen calm.": {
    "en-US": "These fields shape provider profile behavior. They stay collapsed by default so Settings keeps its first screen calm.",
    "es-ES": "Estos campos moldean el comportamiento del perfil. Colapsados por defecto para mantener la calma.",
    "fr-FR": "Ces champs façonnent le comportement du profil. Repliés par défaut pour garder un premier écran calme.",
    "de-DE": "Diese Felder beeinflussen das Profil-Verhalten. Standardmäßig eingeklappt, damit die erste Ansicht ruhig bleibt.",
    "ja-JP": "プロファイルの動作に関わる高度なフィールドです。既定では折りたたまれています。",
    "ko-KR": "프로필 동작에 영향을 주는 고급 필드입니다. 기본적으로 접혀 있습니다.",
    "pt-BR": "Estes campos moldam o comportamento do perfil. Recolhidos por padrão para manter a primeira tela calma.",
  },
  "Credential mode\u0000Credential mode": {
    "en-US": "Credential mode",
    "es-ES": "Credential mode",
    "fr-FR": "Credential mode",
    "de-DE": "Credential mode",
    "ja-JP": "Credential mode",
    "ko-KR": "Credential mode",
    "pt-BR": "Credential mode",
  },
  "UI proxy\u0000UI proxy": {
    "en-US": "UI proxy",
    "es-ES": "UI proxy",
    "fr-FR": "UI proxy",
    "de-DE": "UI proxy",
    "ja-JP": "UI proxy",
    "ko-KR": "UI proxy",
    "pt-BR": "UI proxy",
  },
  "Workspace secret\u0000Workspace secret": {
    "en-US": "Workspace secret",
    "es-ES": "Workspace secret",
    "fr-FR": "Workspace secret",
    "de-DE": "Workspace secret",
    "ja-JP": "Workspace secret",
    "ko-KR": "Workspace secret",
    "pt-BR": "Workspace secret",
  },
  "用逗号或换行分隔。留空表示不限制。\u0000Separate models with commas or new lines. Leave blank to allow any model.": {
    "en-US": "Separate models with commas or new lines. Leave blank to allow any model.",
    "es-ES": "Separa los modelos con comas o saltos de línea. Deja vacío para permitir cualquiera.",
    "fr-FR": "Séparez les modèles par des virgules ou des sauts de ligne. Laissez vide pour tout autoriser.",
    "de-DE": "Trenne Modelle mit Kommas oder Zeilenumbrüchen. Leer lassen für beliebige Modelle.",
    "ja-JP": "モデルはカンマか改行で区切ります。空欄ならすべて許可。",
    "ko-KR": "모델을 쉼표나 줄바꿈으로 구분하세요. 비우면 모두 허용됩니다.",
    "pt-BR": "Separe os modelos com vírgulas ou novas linhas. Deixe vazio para permitir qualquer um.",
  },
  "这些 model 会被 profile 直接挡住。\u0000These models stay blocked for this profile.": {
    "en-US": "These models stay blocked for this profile.",
    "es-ES": "Estos modelos quedan bloqueados para este perfil.",
    "fr-FR": "Ces modèles restent bloqués pour ce profil.",
    "de-DE": "Diese Modelle bleiben für dieses Profil blockiert.",
    "ja-JP": "これらのモデルはこのプロファイルでブロックされます。",
    "ko-KR": "이 모델들은 이 프로필에서 차단됩니다.",
    "pt-BR": "Esses modelos ficam bloqueados para este perfil.",
  },
  "可选，例如 text-embedding-3-small\u0000Optional,for example text-embedding-3-small": {
    "en-US": "Optional, for example text-embedding-3-small",
    "es-ES": "Opcional, por ejemplo text-embedding-3-small",
    "fr-FR": "Optionnel, par exemple text-embedding-3-small",
    "de-DE": "Optional, zum Beispiel text-embedding-3-small",
    "ja-JP": "任意。例: text-embedding-3-small",
    "ko-KR": "선택, 예: text-embedding-3-small",
    "pt-BR": "Opcional, por exemplo text-embedding-3-small",
  },
  "单位是秒。\u0000Measured in seconds.": {
    "en-US": "Measured in seconds.",
    "es-ES": "Se mide en segundos.",
    "fr-FR": "Mesuré en secondes.",
    "de-DE": "Angabe in Sekunden.",
    "ja-JP": "単位は秒です。",
    "ko-KR": "단위는 초입니다.",
    "pt-BR": "Medido em segundos.",
  },
  "手动加入 model\u0000Add model manually": {
    "en-US": "Add model manually",
    "es-ES": "Añadir modelo manualmente",
    "fr-FR": "Ajouter un modèle manuellement",
    "de-DE": "Modell manuell hinzufügen",
    "ja-JP": "モデルを手動で追加",
    "ko-KR": "모델 직접 추가",
    "pt-BR": "Adicionar modelo manualmente",
  },
  "例如 kimi-k3\u0000For example kimi-k3": {
    "en-US": "For example kimi-k3",
    "es-ES": "Por ejemplo kimi-k3",
    "fr-FR": "Par exemple kimi-k3",
    "de-DE": "Zum Beispiel kimi-k3",
    "ja-JP": "例: kimi-k3",
    "ko-KR": "예: kimi-k3",
    "pt-BR": "Por exemplo kimi-k3",
  },
  "加入当前 catalog\u0000Add to current catalog": {
    "en-US": "Add to current catalog",
    "es-ES": "Añadir al catálogo actual",
    "fr-FR": "Ajouter au catalogue actuel",
    "de-DE": "Zum aktuellen Katalog hinzufügen",
    "ja-JP": "現在のカタログに追加",
    "ko-KR": "현재 카탈로그에 추가",
    "pt-BR": "Adicionar ao catálogo atual",
  },
  "即使 provider 还没列出它，也可以先把 model 放进当前 catalog。至少填一个 limit 后，它就会被记住。\u0000You can stage a model here even before the provider lists it. Save at least one limit to keep it in the catalog.": {
    "en-US": "You can stage a model here even before the provider lists it. Save at least one limit to keep it in the catalog.",
    "es-ES": "Puedes añadir un modelo antes de que el proveedor lo liste. Guarda al menos un límite.",
    "fr-FR": "Vous pouvez ajouter un modèle avant que le fournisseur le liste. Enregistrez au moins une limite.",
    "de-DE": "Du kannst ein Modell hier anlegen, bevor der Anbieter es listet. Speichere mindestens ein Limit.",
    "ja-JP": "プロバイダーが列挙する前にモデルを登録できます。limit を 1 つ以上保存すると記憶されます。",
    "ko-KR": "공급자가 아직 나열하지 않아도 모델을 미리 등록할 수 있습니다. limit을 하나 이상 저장하세요.",
    "pt-BR": "Você pode adicionar um modelo antes de o provedor listá-lo. Salve pelo menos um limite.",
  },
  "用 JSON object 细化 provider 请求。Trainer 会在发送时合并这些默认值。\u0000Use a JSON object to refine provider requests. Trainer merges these defaults into outgoing requests.": {
    "en-US": "Use a JSON object to refine provider requests. Trainer merges these defaults into outgoing requests.",
    "es-ES": "Use a JSON object to refine provider requests. Trainer merges these defaults into outgoing requests.",
    "fr-FR": "Use a JSON object to refine provider requests. Trainer merges these defaults into outgoing requests.",
    "de-DE": "Use a JSON object to refine provider requests. Trainer merges these defaults into outgoing requests.",
    "ja-JP": "Use a JSON object to refine provider requests. Trainer merges these defaults into outgoing requests.",
    "ko-KR": "Use a JSON object to refine provider requests. Trainer merges these defaults into outgoing requests.",
    "pt-BR": "Use a JSON object to refine provider requests. Trainer merges these defaults into outgoing requests.",
  },
  "保持为一个 JSON object。适合设置 reasoning、temperature 或其他 provider 字段。\u0000Keep this as a JSON object. Use it for reasoning,temperature,or provider-specific request fields.": {
    "en-US": "Keep this as a JSON object. Use it for reasoning, temperature, or provider-specific request fields.",
    "es-ES": "Keep this as a JSON object. Use it for reasoning, temperature, or provider-specific request fields.",
    "fr-FR": "Keep this as a JSON object. Use it for reasoning, temperature, or provider-specific request fields.",
    "de-DE": "Keep this as a JSON object. Use it for reasoning, temperature, or provider-specific request fields.",
    "ja-JP": "Keep this as a JSON object. Use it for reasoning, temperature, or provider-specific request fields.",
    "ko-KR": "Keep this as a JSON object. Use it for reasoning, temperature, or provider-specific request fields.",
    "pt-BR": "Keep this as a JSON object. Use it for reasoning, temperature, or provider-specific request fields.",
  },
  "Request defaults 必须是可解析的 JSON。\u0000Request defaults must be valid JSON.": {
    "en-US": "Request defaults must be valid JSON.",
    "es-ES": "Request defaults must be valid JSON.",
    "fr-FR": "Request defaults must be valid JSON.",
    "de-DE": "Request defaults must be valid JSON.",
    "ja-JP": "Request defaults must be valid JSON.",
    "ko-KR": "Request defaults must be valid JSON.",
    "pt-BR": "Request defaults must be valid JSON.",
  },
  "Request defaults 必须是 JSON object，不能是 array 或 string。\u0000Request defaults must stay a JSON object,not an array or string.": {
    "en-US": "Request defaults must stay a JSON object, not an array or string.",
    "es-ES": "Request defaults must stay a JSON object, not an array or string.",
    "fr-FR": "Request defaults must stay a JSON object, not an array or string.",
    "de-DE": "Request defaults must stay a JSON object, not an array or string.",
    "ja-JP": "Request defaults must stay a JSON object, not an array or string.",
    "ko-KR": "Request defaults must stay a JSON object, not an array or string.",
    "pt-BR": "Request defaults must stay a JSON object, not an array or string.",
  },
  "清除 limits\u0000Clear limits": {
    "en-US": "Clear limits",
    "es-ES": "Clear limits",
    "fr-FR": "Clear limits",
    "de-DE": "Clear limits",
    "ja-JP": "Clear limits",
    "ko-KR": "Clear limits",
    "pt-BR": "Clear limits",
  },
  "已识别连接信息:服务地址和密钥已自动填入。接下来点「获取模型」选一个模型,然后保存即可。\u0000Recognized the connection info: base URL and API key are filled in. Next,fetch models,pick one,and save.": {
    "en-US": "Recognized the connection info: base URL and API key are filled in. Next, fetch models, pick one, and save.",
    "es-ES": "Información reconocida: URL y clave rellenadas. Después, obtén los modelos, elige uno y guarda.",
    "fr-FR": "Informations reconnues : URL et clé remplies. Ensuite, récupérez les modèles, choisissez-en un et enregistrez.",
    "de-DE": "Verbindungsdaten erkannt: URL und Key eingetragen. Danach Modelle laden, eines wählen und speichern.",
    "ja-JP": "接続情報を認識しました。URL とキーを入力済み。次にモデルを取得して選び、保存してください。",
    "ko-KR": "연결 정보를 인식했습니다. URL과 키가 채워졌습니다. 다음으로 모델을 가져와 선택하고 저장하세요.",
    "pt-BR": "Informações reconhecidas: URL e chave preenchidas. Depois, busque os modelos, escolha um e salve.",
  },
  "这里粘贴的是服务地址,已帮你移到「服务根地址」。密钥请粘到「API 密钥」。\u0000That looks like a service address — moved it to Base URL. Paste the key into API key.": {
    "en-US": "That looks like a service address — moved it to Base URL. Paste the key into API key.",
    "es-ES": "Eso parece una dirección de servicio: la movimos a Base URL. Pega la clave en API key.",
    "fr-FR": "Cela ressemble à une adresse de service : déplacée vers Base URL. Collez la clé dans API key.",
    "de-DE": "Das sieht nach einer Service-Adresse aus — nach Base URL verschoben. Den Key bei API key einfügen.",
    "ja-JP": "これはサービスアドレスのようです — Base URL に移動しました。キーは API キーに貼り付けてください。",
    "ko-KR": "서비스 주소로 보입니다 — Base URL로 옮겼습니다. 키는 API 키에 붙여넣으세요.",
    "pt-BR": "Isso parece um endereço de serviço — movido para Base URL. Cole a chave em API key.",
  },
  "这里粘贴的是密钥,已帮你移到「API 密钥」。服务地址请粘到「服务根地址」。\u0000That looks like an API key — moved it to API key. Paste the address into Base URL.": {
    "en-US": "That looks like an API key — moved it to API key. Paste the address into Base URL.",
    "es-ES": "Eso parece una API key: la movimos a API key. Pega la dirección en Base URL.",
    "fr-FR": "Cela ressemble à une clé API : déplacée vers API key. Collez l'adresse dans Base URL.",
    "de-DE": "Das sieht nach einem API-Key aus — nach API key verschoben. Die Adresse bei Base URL einfügen.",
    "ja-JP": "これは API キーのようです — API キーに移動しました。アドレスは Base URL に貼り付けてください。",
    "ko-KR": "API 키로 보입니다 — API 키로 옮겼습니다. 주소는 Base URL에 붙여넣으세요.",
    "pt-BR": "Isso parece uma API key — movida para API key. Cole o endereço em Base URL.",
  },
  "先填写服务根地址和模型，再保存连接。\u0000Add the service root and model before saving the connection.": {
    "en-US": "Add the service root and model before saving the connection.",
    "es-ES": "Add the service root and model before saving the connection.",
    "fr-FR": "Add the service root and model before saving the connection.",
    "de-DE": "Add the service root and model before saving the connection.",
    "ja-JP": "Add the service root and model before saving the connection.",
    "ko-KR": "Add the service root and model before saving the connection.",
    "pt-BR": "Add the service root and model before saving the connection.",
  },
  "当前连接已保存。\u0000This connection is already saved.": {
    "en-US": "This connection is already saved.",
    "es-ES": "Esta conexión ya está guardada.",
    "fr-FR": "Cette connexion est déjà enregistrée.",
    "de-DE": "Diese Verbindung ist bereits gespeichert.",
    "ja-JP": "この接続は保存済みです。",
    "ko-KR": "이 연결은 이미 저장되어 있습니다.",
    "pt-BR": "Esta conexão já está salva.",
  },
  "连接与默认项。\u0000Connection and defaults.": {
    "en-US": "Connection and defaults.",
    "es-ES": "Conexión y valores predeterminados.",
    "fr-FR": "Connexion et valeurs par défaut.",
    "de-DE": "Verbindung und Standards.",
    "ja-JP": "接続と既定値。",
    "ko-KR": "연결 및 기본값.",
    "pt-BR": "Conexão e padrões.",
  },
  "已可发送。\u0000Ready to send.": {
    "en-US": "Ready to send.",
    "es-ES": "Ready to send.",
    "fr-FR": "Ready to send.",
    "de-DE": "Ready to send.",
    "ja-JP": "Ready to send.",
    "ko-KR": "Ready to send.",
    "pt-BR": "Ready to send.",
  },
  "已就绪\u0000Ready": {
    "en-US": "Ready",
    "es-ES": "Ready",
    "fr-FR": "Ready",
    "de-DE": "Ready",
    "ja-JP": "Ready",
    "ko-KR": "Ready",
    "pt-BR": "Ready",
  },
  "缺少密钥\u0000Missing key": {
    "en-US": "Missing key",
    "es-ES": "Missing key",
    "fr-FR": "Missing key",
    "de-DE": "Missing key",
    "ja-JP": "Missing key",
    "ko-KR": "Missing key",
    "pt-BR": "Missing key",
  },
  "被阻塞\u0000Blocked": {
    "en-US": "Blocked",
    "es-ES": "Blocked",
    "fr-FR": "Blocked",
    "de-DE": "Blocked",
    "ja-JP": "Blocked",
    "ko-KR": "Blocked",
    "pt-BR": "Blocked",
  },
  "未开启\u0000Off": {
    "en-US": "Off",
    "es-ES": "Off",
    "fr-FR": "Off",
    "de-DE": "Off",
    "ja-JP": "Off",
    "ko-KR": "Off",
    "pt-BR": "Off",
  },
  "未验证图片输入。\u0000Image input not verified.": {
    "en-US": "Image input not verified.",
    "es-ES": "Image input not verified.",
    "fr-FR": "Image input not verified.",
    "de-DE": "Image input not verified.",
    "ja-JP": "Image input not verified.",
    "ko-KR": "Image input not verified.",
    "pt-BR": "Image input not verified.",
  },
  "草稿未生效\u0000Draft not applied": {
    "en-US": "Draft not applied",
    "es-ES": "Draft not applied",
    "fr-FR": "Draft not applied",
    "de-DE": "Draft not applied",
    "ja-JP": "Draft not applied",
    "ko-KR": "Draft not applied",
    "pt-BR": "Draft not applied",
  },
  "连接草稿未保存\u0000Connection draft not saved": {
    "en-US": "Connection draft not saved",
    "es-ES": "Connection draft not saved",
    "fr-FR": "Connection draft not saved",
    "de-DE": "Connection draft not saved",
    "ja-JP": "Connection draft not saved",
    "ko-KR": "Connection draft not saved",
    "pt-BR": "Connection draft not saved",
  },
  "模型可用\u0000Model ready": {
    "en-US": "Model ready",
    "es-ES": "Model ready",
    "fr-FR": "Model ready",
    "de-DE": "Model ready",
    "ja-JP": "Model ready",
    "ko-KR": "Model ready",
    "pt-BR": "Model ready",
  },
  "缺少 API key\u0000API key required": {
    "en-US": "API key required",
    "es-ES": "API key required",
    "fr-FR": "API key required",
    "de-DE": "API key required",
    "ja-JP": "API key required",
    "ko-KR": "API key required",
    "pt-BR": "API key required",
  },
  "连接待验证\u0000Connection needs test": {
    "en-US": "Connection needs test",
    "es-ES": "Connection needs test",
    "fr-FR": "Connection needs test",
    "de-DE": "Connection needs test",
    "ja-JP": "Connection needs test",
    "ko-KR": "Connection needs test",
    "pt-BR": "Connection needs test",
  },
  "设置模型连接\u0000Set up model access": {
    "en-US": "Set up model access",
    "es-ES": "Set up model access",
    "fr-FR": "Set up model access",
    "de-DE": "Set up model access",
    "ja-JP": "Set up model access",
    "ko-KR": "Set up model access",
    "pt-BR": "Set up model access",
  },
  "当前草稿已经可以测试。保存后会成为当前连接。\u0000This draft can be tested now. Save when you want to apply it.": {
    "en-US": "This draft can be tested now. Save when you want to apply it.",
    "es-ES": "This draft can be tested now. Save when you want to apply it.",
    "fr-FR": "This draft can be tested now. Save when you want to apply it.",
    "de-DE": "This draft can be tested now. Save when you want to apply it.",
    "ja-JP": "This draft can be tested now. Save when you want to apply it.",
    "ko-KR": "This draft can be tested now. Save when you want to apply it.",
    "pt-BR": "This draft can be tested now. Save when you want to apply it.",
  },
  "保存后测试。\u0000Save before testing.": {
    "en-US": "Save before testing.",
    "es-ES": "Save before testing.",
    "fr-FR": "Save before testing.",
    "de-DE": "Save before testing.",
    "ja-JP": "Save before testing.",
    "ko-KR": "Save before testing.",
    "pt-BR": "Save before testing.",
  },
  "对话、计划、训练使用此连接。\u0000Chat,plan,and training use this connection.": {
    "en-US": "Chat, plan, and training use this connection.",
    "es-ES": "Chat, plan, and training use this connection.",
    "fr-FR": "Chat, plan, and training use this connection.",
    "de-DE": "Chat, plan, and training use this connection.",
    "ja-JP": "Chat, plan, and training use this connection.",
    "ko-KR": "Chat, plan, and training use this connection.",
    "pt-BR": "Chat, plan, and training use this connection.",
  },
  "保存草稿\u0000Save draft": {
    "en-US": "Save draft",
    "es-ES": "Save draft",
    "fr-FR": "Save draft",
    "de-DE": "Save draft",
    "ja-JP": "Save draft",
    "ko-KR": "Save draft",
    "pt-BR": "Save draft",
  },
  "重新测试\u0000Test again": {
    "en-US": "Test again",
    "es-ES": "Test again",
    "fr-FR": "Test again",
    "de-DE": "Test again",
    "ja-JP": "Test again",
    "ko-KR": "Test again",
    "pt-BR": "Test again",
  },
  "补上 API key\u0000Add API key": {
    "en-US": "Add API key",
    "es-ES": "Add API key",
    "fr-FR": "Add API key",
    "de-DE": "Add API key",
    "ja-JP": "Add API key",
    "ko-KR": "Add API key",
    "pt-BR": "Add API key",
  },
  "测试当前连接\u0000Test current connection": {
    "en-US": "Test current connection",
    "es-ES": "Test current connection",
    "fr-FR": "Test current connection",
    "de-DE": "Test current connection",
    "ja-JP": "Test current connection",
    "ko-KR": "Test current connection",
    "pt-BR": "Test current connection",
  },
  "保存后生效\u0000Save to apply": {
    "en-US": "Save to apply",
    "es-ES": "Save to apply",
    "fr-FR": "Save to apply",
    "de-DE": "Save to apply",
    "ja-JP": "Save to apply",
    "ko-KR": "Save to apply",
    "pt-BR": "Save to apply",
  },
  "检查中\u0000Checking": {
    "en-US": "Checking",
    "es-ES": "Checking",
    "fr-FR": "Checking",
    "de-DE": "Checking",
    "ja-JP": "Checking",
    "ko-KR": "Checking",
    "pt-BR": "Checking",
  },
  "可发送\u0000Send enabled": {
    "en-US": "Send enabled",
    "es-ES": "Send enabled",
    "fr-FR": "Send enabled",
    "de-DE": "Send enabled",
    "ja-JP": "Send enabled",
    "ko-KR": "Send enabled",
    "pt-BR": "Pronto",
  },
  "待选目录\u0000No folder yet": {
    "en-US": "No folder yet",
    "es-ES": "No folder yet",
    "fr-FR": "No folder yet",
    "de-DE": "No folder yet",
    "ja-JP": "No folder yet",
    "ko-KR": "No folder yet",
    "pt-BR": "No folder yet",
  },
  "待信任\u0000Trust needed": {
    "en-US": "Trust needed",
    "es-ES": "Trust needed",
    "fr-FR": "Trust needed",
    "de-DE": "Trust needed",
    "ja-JP": "Trust needed",
    "ko-KR": "Trust needed",
    "pt-BR": "Trust needed",
  },
  "先选择工作区根目录\u0000Choose a workspace root first": {
    "en-US": "Choose a workspace root first",
    "es-ES": "Choose a workspace root first",
    "fr-FR": "Choose a workspace root first",
    "de-DE": "Choose a workspace root first",
    "ja-JP": "Choose a workspace root first",
    "ko-KR": "Choose a workspace root first",
    "pt-BR": "Choose a workspace root first",
  },
  "先信任此窗口\u0000Trust this window first": {
    "en-US": "Trust this window first",
    "es-ES": "Trust this window first",
    "fr-FR": "Trust this window first",
    "de-DE": "Trust this window first",
    "ja-JP": "Trust this window first",
    "ko-KR": "Trust this window first",
    "pt-BR": "Trust this window first",
  },
  "先应用一个已保存的 profile\u0000Apply a saved profile first": {
    "en-US": "Apply a saved profile first",
    "es-ES": "Apply a saved profile first",
    "fr-FR": "Apply a saved profile first",
    "de-DE": "Apply a saved profile first",
    "ja-JP": "Apply a saved profile first",
    "ko-KR": "Apply a saved profile first",
    "pt-BR": "Apply a saved profile first",
  },
  "先在上方选择工作区根目录，否则对话和训练无法使用。\u0000Choose a workspace root above first — Coach and Training cannot work without it.": {
    "en-US": "Choose a workspace root above first — Coach and Training cannot work without it.",
    "es-ES": "Choose a workspace root above first — Coach and Training cannot work without it.",
    "fr-FR": "Choose a workspace root above first — Coach and Training cannot work without it.",
    "de-DE": "Choose a workspace root above first — Coach and Training cannot work without it.",
    "ja-JP": "Choose a workspace root above first — Coach and Training cannot work without it.",
    "ko-KR": "Choose a workspace root above first — Coach and Training cannot work without it.",
    "pt-BR": "Choose a workspace root above first — Coach and Training cannot work without it.",
  },
  "当前工作区还没有启用中的 provider，但下面已经有可复用的 profiles。\u0000This workspace has no active provider yet,but reusable profiles are already available below.": {
    "en-US": "This workspace has no active provider yet, but reusable profiles are already available below.",
    "es-ES": "This workspace has no active provider yet, but reusable profiles are already available below.",
    "fr-FR": "This workspace has no active provider yet, but reusable profiles are already available below.",
    "de-DE": "This workspace has no active provider yet, but reusable profiles are already available below.",
    "ja-JP": "This workspace has no active provider yet, but reusable profiles are already available below.",
    "ko-KR": "This workspace has no active provider yet, but reusable profiles are already available below.",
    "pt-BR": "This workspace has no active provider yet, but reusable profiles are already available below.",
  },
  "打开 profiles\u0000Open profiles": {
    "en-US": "Open profiles",
    "es-ES": "Open profiles",
    "fr-FR": "Open profiles",
    "de-DE": "Open profiles",
    "ja-JP": "Open profiles",
    "ko-KR": "Open profiles",
    "pt-BR": "Open profiles",
  },
  "直接打开下方的 profiles。\u0000Open the saved profiles below.": {
    "en-US": "Open the saved profiles below.",
    "es-ES": "Open the saved profiles below.",
    "fr-FR": "Open the saved profiles below.",
    "de-DE": "Open the saved profiles below.",
    "ja-JP": "Open the saved profiles below.",
    "ko-KR": "Open the saved profiles below.",
    "pt-BR": "Open the saved profiles below.",
  },
  "草稿中\u0000Draft": {
    "en-US": "Draft",
    "es-ES": "Draft",
    "fr-FR": "Draft",
    "de-DE": "Draft",
    "ja-JP": "Draft",
    "ko-KR": "Draft",
    "pt-BR": "Draft",
  },
  "先完成 provider、base URL 和 model，再测试连接。\u0000Finish the provider,base URL,and model before testing the connection.": {
    "en-US": "Finish the provider, base URL, and model before testing the connection.",
    "es-ES": "Finish the provider, base URL, and model before testing the connection.",
    "fr-FR": "Finish the provider, base URL, and model before testing the connection.",
    "de-DE": "Finish the provider, base URL, and model before testing the connection.",
    "ja-JP": "Finish the provider, base URL, and model before testing the connection.",
    "ko-KR": "Finish the provider, base URL, and model before testing the connection.",
    "pt-BR": "Finish the provider, base URL, and model before testing the connection.",
  },
  "先补上 API key，再测试这组连接。\u0000Add an API key before testing this connection.": {
    "en-US": "Add an API key before testing this connection.",
    "es-ES": "Add an API key before testing this connection.",
    "fr-FR": "Add an API key before testing this connection.",
    "de-DE": "Add an API key before testing this connection.",
    "ja-JP": "Add an API key before testing this connection.",
    "ko-KR": "Add an API key before testing this connection.",
    "pt-BR": "Add an API key before testing this connection.",
  },
  "先保存当前草稿，再测试这组连接。\u0000Save the current draft before testing this connection.": {
    "en-US": "Save the current draft before testing this connection.",
    "es-ES": "Save the current draft before testing this connection.",
    "fr-FR": "Save the current draft before testing this connection.",
    "de-DE": "Save the current draft before testing this connection.",
    "ja-JP": "Save the current draft before testing this connection.",
    "ko-KR": "Save the current draft before testing this connection.",
    "pt-BR": "Save the current draft before testing this connection.",
  },
  "先启用一个已保存的 profile，再测试当前连接。\u0000Apply a saved profile before testing the current connection.": {
    "en-US": "Apply a saved profile before testing the current connection.",
    "es-ES": "Apply a saved profile before testing the current connection.",
    "fr-FR": "Apply a saved profile before testing the current connection.",
    "de-DE": "Apply a saved profile before testing the current connection.",
    "ja-JP": "Apply a saved profile before testing the current connection.",
    "ko-KR": "Apply a saved profile before testing the current connection.",
    "pt-BR": "Apply a saved profile before testing the current connection.",
  },
  "先完成 provider 配置，再测试连接。\u0000Finish the provider setup before testing the connection.": {
    "en-US": "Finish the provider setup before testing the connection.",
    "es-ES": "Finish the provider setup before testing the connection.",
    "fr-FR": "Finish the provider setup before testing the connection.",
    "de-DE": "Finish the provider setup before testing the connection.",
    "ja-JP": "Finish the provider setup before testing the connection.",
    "ko-KR": "Finish the provider setup before testing the connection.",
    "pt-BR": "Finish the provider setup before testing the connection.",
  },
  "保存时将自动获取并选择可用模型。\u0000A model will be fetched and selected automatically when you save.": {
    "en-US": "A model will be fetched and selected automatically when you save.",
    "es-ES": "A model will be fetched and selected automatically when you save.",
    "fr-FR": "A model will be fetched and selected automatically when you save.",
    "de-DE": "A model will be fetched and selected automatically when you save.",
    "ja-JP": "A model will be fetched and selected automatically when you save.",
    "ko-KR": "A model will be fetched and selected automatically when you save.",
    "pt-BR": "A model will be fetched and selected automatically when you save.",
  },
  "信任此窗口\u0000Trust this window": {
    "en-US": "Trust this window",
    "es-ES": "Trust this window",
    "fr-FR": "Trust this window",
    "de-DE": "Trust this window",
    "ja-JP": "Trust this window",
    "ko-KR": "Trust this window",
    "pt-BR": "Trust this window",
  },
  "给这组连接起个名字(可不填)\u0000Name this connection (optional)": {
    "en-US": "Name this connection (optional)",
    "es-ES": "Name this connection (optional)",
    "fr-FR": "Name this connection (optional)",
    "de-DE": "Name this connection (optional)",
    "ja-JP": "Name this connection (optional)",
    "ko-KR": "Name this connection (optional)",
    "pt-BR": "Name this connection (optional)",
  },
  "例如 localhost:1234/v1 或 api.deepseek.com/v1\u0000e.g. localhost:1234/v1 or api.deepseek.com/v1": {
    "en-US": "e.g. localhost:1234/v1 or api.deepseek.com/v1",
    "es-ES": "e.g. localhost:1234/v1 or api.deepseek.com/v1",
    "fr-FR": "e.g. localhost:1234/v1 or api.deepseek.com/v1",
    "de-DE": "e.g. localhost:1234/v1 or api.deepseek.com/v1",
    "ja-JP": "e.g. localhost:1234/v1 or api.deepseek.com/v1",
    "ko-KR": "e.g. localhost:1234/v1 or api.deepseek.com/v1",
    "pt-BR": "e.g. localhost:1234/v1 or api.deepseek.com/v1",
  },
  "⚙ 高级\u0000⚙ Advanced": {
    "en-US": "⚙ Advanced",
    "es-ES": "⚙ Advanced",
    "fr-FR": "⚙ Advanced",
    "de-DE": "⚙ Advanced",
    "ja-JP": "⚙ Advanced",
    "ko-KR": "⚙ Advanced",
    "pt-BR": "⚙ Advanced",
  },
  "端点测速 · 协议 · 连接详情\u0000Speed test · Protocol · Connection details": {
    "en-US": "Speed test · Protocol · Connection details",
    "es-ES": "Speed test · Protocol · Connection details",
    "fr-FR": "Speed test · Protocol · Connection details",
    "de-DE": "Speed test · Protocol · Connection details",
    "ja-JP": "Speed test · Protocol · Connection details",
    "ko-KR": "Speed test · Protocol · Connection details",
    "pt-BR": "Speed test · Protocol · Connection details",
  },
  "Trainer 沙箱 artifact 写入\u0000Trainer sandbox artifact writes": {
    "en-US": "Trainer sandbox artifact writes",
    "es-ES": "Trainer sandbox artifact writes",
    "fr-FR": "Trainer sandbox artifact writes",
    "de-DE": "Trainer sandbox artifact writes",
    "ja-JP": "Trainer sandbox artifact writes",
    "ko-KR": "Trainer sandbox artifact writes",
    "pt-BR": "Trainer sandbox artifact writes",
  },
  "用户源码工作区只读\u0000User source workspace is read-only": {
    "en-US": "User source workspace is read-only",
    "es-ES": "User source workspace is read-only",
    "fr-FR": "User source workspace is read-only",
    "de-DE": "User source workspace is read-only",
    "ja-JP": "User source workspace is read-only",
    "ko-KR": "User source workspace is read-only",
    "pt-BR": "User source workspace is read-only",
  },
  "等待真实写入证据\u0000Awaiting verified write evidence": {
    "en-US": "Awaiting verified write evidence",
    "es-ES": "Awaiting verified write evidence",
    "fr-FR": "Awaiting verified write evidence",
    "de-DE": "Awaiting verified write evidence",
    "ja-JP": "Awaiting verified write evidence",
    "ko-KR": "Awaiting verified write evidence",
    "pt-BR": "Awaiting verified write evidence",
  },
  "切换并重启后端\u0000Switch and restart": {
    "en-US": "Switch and restart",
    "es-ES": "Switch and restart",
    "fr-FR": "Switch and restart",
    "de-DE": "Switch and restart",
    "ja-JP": "Switch and restart",
    "ko-KR": "Switch and restart",
    "pt-BR": "Switch and restart",
  },
  "回到推荐目录\u0000Return to recommended": {
    "en-US": "Return to recommended",
    "es-ES": "Return to recommended",
    "fr-FR": "Return to recommended",
    "de-DE": "Return to recommended",
    "ja-JP": "Return to recommended",
    "ko-KR": "Return to recommended",
    "pt-BR": "Return to recommended",
  },
  "重建摘要\u0000Rebuild summary": {
    "en-US": "Rebuild summary",
    "es-ES": "Rebuild summary",
    "fr-FR": "Rebuild summary",
    "de-DE": "Rebuild summary",
    "ja-JP": "Rebuild summary",
    "ko-KR": "Rebuild summary",
    "pt-BR": "Rebuild summary",
  },
  "推荐值\u0000Recommended": {
    "en-US": "Recommended",
    "es-ES": "Recommended",
    "fr-FR": "Recommended",
    "de-DE": "Recommended",
    "ja-JP": "Recommended",
    "ko-KR": "Recommended",
    "pt-BR": "Recommended",
  },
  "Trainer 按你的问题自动选用；输入 $ 可手动触发。\u0000Trainer picks these automatically; type $ to trigger one manually.": {
    "en-US": "Trainer picks these automatically; type $ to trigger one manually.",
    "es-ES": "Trainer picks these automatically; type $ to trigger one manually.",
    "fr-FR": "Trainer picks these automatically; type $ to trigger one manually.",
    "de-DE": "Trainer picks these automatically; type $ to trigger one manually.",
    "ja-JP": "Trainer picks these automatically; type $ to trigger one manually.",
    "ko-KR": "Trainer picks these automatically; type $ to trigger one manually.",
    "pt-BR": "Trainer picks these automatically; type $ to trigger one manually.",
  },
  "内部标识\u0000Internal identifiers": {
    "en-US": "Internal identifiers",
    "es-ES": "Internal identifiers",
    "fr-FR": "Internal identifiers",
    "de-DE": "Internal identifiers",
    "ja-JP": "Internal identifiers",
    "ko-KR": "Internal identifiers",
    "pt-BR": "Internal identifiers",
  },
  "工作区 ID\u0000Workspace ID": {
    "en-US": "Workspace ID",
    "es-ES": "Workspace ID",
    "fr-FR": "Workspace ID",
    "de-DE": "Workspace ID",
    "ja-JP": "Workspace ID",
    "ko-KR": "Workspace ID",
    "pt-BR": "Workspace ID",
  },
  "配置 ID\u0000Profile ID": {
    "en-US": "Profile ID",
    "es-ES": "Profile ID",
    "fr-FR": "Profile ID",
    "de-DE": "Profile ID",
    "ja-JP": "Profile ID",
    "ko-KR": "Profile ID",
    "pt-BR": "Profile ID",
  },
  "这些标识用于问题排查；连接诊断在“连接”页。\u0000Use these identifiers when reporting issues; connection diagnostics live under Connection.": {
    "en-US": "Use these identifiers when reporting issues; connection diagnostics live under Connection.",
    "es-ES": "Use these identifiers when reporting issues; connection diagnostics live under Connection.",
    "fr-FR": "Use these identifiers when reporting issues; connection diagnostics live under Connection.",
    "de-DE": "Use these identifiers when reporting issues; connection diagnostics live under Connection.",
    "ja-JP": "Use these identifiers when reporting issues; connection diagnostics live under Connection.",
    "ko-KR": "Use these identifiers when reporting issues; connection diagnostics live under Connection.",
    "pt-BR": "Use these identifiers when reporting issues; connection diagnostics live under Connection.",
  },
};

/** Resolves the active-language text for a migrated zh/en pair. */
export function settingsText(
  language: ComposerLanguage,
  zh: string,
  en: string,
): string {
  // zh-CN resolves to the source string directly; the record keys embed the
  // zh text (`zh\u0000en` disambiguation form) and carry only the other 7
  // languages, so an entry lookup can never serve zh-CN.
  if (language === "zh-CN") {
    return zh;
  }
  const entry = SETTINGS_TEXT[`${zh}\u0000${en}`] ?? SETTINGS_TEXT[zh];
  return entry?.[language] ?? en;
}

