/** §十五: speed-test labels in eight languages (no zh/en binary). */

export const SPEED_TEST_TEXT: Record<string, Record<string, string>> = {
  "⚡ 端点测速": {
    "en-US": "⚡ Endpoint speed test",
    "es-ES": "⚡ Endpoint speed test",
    "fr-FR": "⚡ Endpoint speed test",
    "de-DE": "⚡ Endpoint speed test",
    "ja-JP": "⚡ Endpoint speed test",
    "ko-KR": "⚡ Endpoint speed test",
    "pt-BR": "⚡ Endpoint speed test",
  },
  "对服务地址做一次轻量测速(不消耗模型额度)。点结果行直接采用该地址。": {
    "en-US": "Lightweight latency test for service addresses (no model quota used). Click a row to adopt that address.",
    "es-ES": "Lightweight latency test for service addresses (no model quota used). Click a row to adopt that address.",
    "fr-FR": "Lightweight latency test for service addresses (no model quota used). Click a row to adopt that address.",
    "de-DE": "Lightweight latency test for service addresses (no model quota used). Click a row to adopt that address.",
    "ja-JP": "Lightweight latency test for service addresses (no model quota used). Click a row to adopt that address.",
    "ko-KR": "Lightweight latency test for service addresses (no model quota used). Click a row to adopt that address.",
    "pt-BR": "Lightweight latency test for service addresses (no model quota used). Click a row to adopt that address.",
  },
  "再添加一个端点地址(可选)": {
    "en-US": "Add another endpoint to test (optional)",
    "es-ES": "Add another endpoint to test (optional)",
    "fr-FR": "Add another endpoint to test (optional)",
    "de-DE": "Add another endpoint to test (optional)",
    "ja-JP": "Add another endpoint to test (optional)",
    "ko-KR": "Add another endpoint to test (optional)",
    "pt-BR": "Add another endpoint to test (optional)",
  },
  "开始测速": {
    "en-US": "Run speed test",
    "es-ES": "Run speed test",
    "fr-FR": "Run speed test",
    "de-DE": "Run speed test",
    "ja-JP": "Run speed test",
    "ko-KR": "Run speed test",
    "pt-BR": "Run speed test",
  },
  "测速中…": {
    "en-US": "Testing…",
    "es-ES": "Testing…",
    "fr-FR": "Testing…",
    "de-DE": "Testing…",
    "ja-JP": "Testing…",
    "ko-KR": "Testing…",
    "pt-BR": "Testing…",
  },
  "采用最快端点": {
    "en-US": "Use fastest",
    "es-ES": "Use fastest",
    "fr-FR": "Use fastest",
    "de-DE": "Use fastest",
    "ja-JP": "Use fastest",
    "ko-KR": "Use fastest",
    "pt-BR": "Use fastest",
  },
  "当前": {
    "en-US": "current",
    "es-ES": "current",
    "fr-FR": "current",
    "de-DE": "current",
    "ja-JP": "current",
    "ko-KR": "current",
    "pt-BR": "current",
  },
  "收起": {
    "en-US": "Collapse",
    "es-ES": "Collapse",
    "fr-FR": "Collapse",
    "de-DE": "Collapse",
    "ja-JP": "Collapse",
    "ko-KR": "Collapse",
    "pt-BR": "Collapse",
  },
};

