export const trainerCommands = {
  openWorkbench: "trainer.openWorkbench",
  configureProvider: "trainer.provider.configure",
  saveProvider: "trainer.provider.save",
  clearProvider: "trainer.provider.clear",
  testProvider: "trainer.provider.test",
  refreshProviderModels: "trainer.provider.refreshModels",
  useProviderTemplate: "trainer.provider.useTemplate",
  switchProviderProfile: "trainer.provider.switchProfile",
  switchProviderModel: "trainer.provider.switchModel",
  saveProviderProfile: "trainer.provider.saveProfile",
  refreshProviderProfiles: "trainer.provider.refreshProfiles",
  openWorkspaceConfig: "trainer.config.openWorkspace",
  restartSidecar: "trainer.sidecar.restart",
  stopSidecar: "trainer.sidecar.stop",
  sendMessage: "trainer.session.sendMessage",
  sendStreamMessage: "trainer.session.sendStreamMessage",
  cancelStreamMessage: "trainer.session.cancelStreamMessage",
  resumeLatestCoachCheckpoint: "trainer.session.resumeLatestCoachCheckpoint",
  replayLatestCoachCheckpoint: "trainer.session.replayLatestCoachCheckpoint",
  coachRemoteBoundary: "trainer.coach.remoteBoundary",
  coachDebugLoop: "trainer.coach.debugLoop",
  coachFunctionContract: "trainer.coach.functionContract",
  coachConceptMastery: "trainer.coach.conceptMastery",
  coachVocabularyRecall: "trainer.coach.vocabularyRecall",
  coachMathDerivation: "trainer.coach.mathDerivation",
  coachWritingRevision: "trainer.coach.writingRevision",
  coachReadingTransfer: "trainer.coach.readingTransfer",
  generatePlan: "trainer.plan.generate",
  updatePlan: "trainer.plan.update",
  createGlobalPlan: "trainer.plan.global.create",
  linkCurrentProjectPlan: "trainer.plan.global.linkCurrentProject",
  taskSpecify: "trainer.task.specify",
  nextTask: "trainer.task.next",
  uploadResource: "trainer.resource.upload",
  indexResources: "trainer.resource.index",
  searchResources: "trainer.resource.search",
  deleteResource: "trainer.resource.delete",
  confirmResourceOrganization: "trainer.resource.confirmOrganization",
  cancelResourceOrganization: "trainer.resource.cancelOrganization",
  restoreResource: "trainer.resource.restore",
  refreshResourceTrash: "trainer.resource.refreshTrash",
  openResource: "trainer.resource.open",
  previewSandbox: "trainer.sandbox.preview",
  createSandboxFile: "trainer.sandbox.write",
  createSandboxDirectory: "trainer.sandbox.mkdir",
  renameSandboxPath: "trainer.sandbox.rename",
  deleteSandboxPath: "trainer.sandbox.delete",
  deleteSandboxPaths: "trainer.sandbox.deleteMany",
  restoreSandboxPath: "trainer.sandbox.restore",
  refreshSandbox: "trainer.sandbox.refresh",
  revealSandboxPath: "trainer.sandbox.reveal",
  chooseSandboxRoot: "trainer.sandbox.chooseRoot",
  resetSandboxRoot: "trainer.sandbox.resetRoot",
  chooseManagedDataFolder: "trainer.resource.chooseManagedDataFolder",
  resetManagedDataFolder: "trainer.resource.resetManagedDataFolder",
  chooseTrainerWorkspaceRoot: "trainer.workspace.chooseRoot",
  migrateTrainerWorkspaceRoot: "trainer.workspace.migrateRoot",
  backupTrainerWorkspace: "trainer.workspace.backup",
  restoreTrainerWorkspaceBackup: "trainer.workspace.restore",
  adoptWorkspaceProject: "trainer.workspace.adoptProject",
  chooseWorkspaceProject: "trainer.workspace.chooseProject",
  browseWorkspaceProject: "trainer.workspace.browseProject",
  ignoreWorkspaceProject: "trainer.workspace.ignoreProject",
  deleteWorkspaceProject: "trainer.workspace.deleteProject",
  retryWorkspaceAdmission: "trainer.workspace.retryAdmission",
  continueWorkspaceAdmission: "trainer.workspace.continueAdmission",
  abandonWorkspaceAdmission: "trainer.workspace.abandonAdmission",
  evaluateCurrentFile: "trainer.evaluate.currentFile",
  evaluateSelection: "trainer.evaluate.selection",
  refreshMemory: "trainer.memory.refresh",
  recordUserFeedback: "trainer.memory.recordUserFeedback",
  refreshWorkspaceAuthority: "trainer.memory.refreshWorkspaceAuthority",
  saveCoachSettings: "trainer.memory.saveCoachSettings",
  grantMemoryShare: "trainer.memory.share.grant",
  revokeMemoryShare: "trainer.memory.share.revoke",
  evidenceEnqueue: "trainer.evidence.enqueue",
  evidenceAdopt: "trainer.evidence.adopt",
  evidenceReject: "trainer.evidence.reject",
  evidenceDefer: "trainer.evidence.defer",
  evidenceRefreshQueue: "trainer.evidence.refreshQueue",
  trainingCardStatusTransition: "trainer.trainingCard.transition",
  trainingGenerateCard: "trainer.training.generateCard",
  trainingFlashcardCreate: "trainer.flashcard.create",
  trainingFlashcardAnswer: "trainer.training.flashcardAnswer",
  trainingTheoryDrillAnswer: "trainer.training.theoryDrillAnswer",
  trainingPracticeReturn: "trainer.training.practiceReturn",
  trainingReflect: "trainer.training.reflect",
  trainingReturn: "trainer.training.return",
  trainingReliabilityControl: "trainer.training.reliabilityControl",
  trainingDependencySkillMapAction: "trainer.training.dependencySkillMapAction",
  trainingReviewQueueAction: "trainer.training.reviewQueueAction",
  trainingReviewArtifactAction: "trainer.training.reviewArtifactAction",
  trainingScenarioLabAction: "trainer.training.scenarioLabAction",
  trainingRestoreOrchestration: "trainer.trainingRestore.orchestrate",
  theoryDrillSubmitAnswer: "trainer.theoryDrill.submitAnswer",
  reviewQueueAction: "trainer.reviewQueue.action",
  scenarioLabAction: "trainer.scenarioLab.action",
  // Research commands
  createResearch: "trainer.research.create",
  addResearchTheme: "trainer.research.theme.add",
  activateResearchTheme: "trainer.research.theme.activate",
  advanceResearch: "trainer.research.advance",
  researchMessage: "trainer.research.message",
  approveResearchDecision: "trainer.research.approve",
  getResearchStatus: "trainer.research.status",
  stageMaterialGenerate: "trainer.stageMaterial.generate",
} as const;

export type TrainerCommand = (typeof trainerCommands)[keyof typeof trainerCommands];

export interface TrainerCommandCatalogItem {
  id: TrainerCommand;
  title: string;
  section:
    | "Workbench"
    | "Coaching"
    | "Plans"
    | "Tasks"
  | "Resources"
  | "Training"
  | "Reviews"
  | "Memory"
  | "Workspace"
  | "Provider"
  | "Sidecar"
  | "Research";
  detail: string;
  shortcut?: string;
  keywords: string[];
}

export const trainerCommandCatalog: TrainerCommandCatalogItem[] = [
  {
    id: trainerCommands.openWorkbench,
    title: "Open coach sidebar",
    section: "Workbench",
    detail: "Reveal the Trainer sidebar in VS Code.",
    keywords: ["open", "sidebar", "panel", "trainer", "coach"],
  },
  {
    id: trainerCommands.sendMessage,
    title: "Send message",
    section: "Workbench",
    detail: "Prompt for a coaching message and send it to the active Trainer session.",
    keywords: ["message", "chat", "session", "prompt", "coach"],
  },
  {
    id: trainerCommands.resumeLatestCoachCheckpoint,
    title: "Resume latest Coach checkpoint",
    section: "Coaching",
    detail: "Restore the latest saved point in this Coach conversation without sending a new message.",
    keywords: ["resume", "restore", "checkpoint", "coach", "conversation", "recovery"],
  },
  {
    id: trainerCommands.replayLatestCoachCheckpoint,
    title: "View latest Coach checkpoint",
    section: "Coaching",
    detail: "Open the saved Coach trace for this conversation without running it again.",
    keywords: ["view", "replay", "checkpoint", "coach", "trace", "recovery"],
  },
  {
    id: trainerCommands.coachRemoteBoundary,
    title: "Coach remote workspace boundary",
    section: "Coaching",
    detail: "Prepare a guided remote-boundary check in Coach without changing the formal plan.",
    keywords: ["remote", "ssh", "tunnels", "container", "wsl", "boundary"],
  },
  {
    id: trainerCommands.coachDebugLoop,
    title: "Coach minimal debug loop",
    section: "Coaching",
    detail: "Prepare a smallest-trustworthy debug loop in Coach without changing the formal plan.",
    keywords: ["debug", "breakpoint", "reproduce", "state", "diagnostic"],
  },
  {
    id: trainerCommands.coachFunctionContract,
    title: "Coach function contract",
    section: "Coaching",
    detail: "Prepare hover, signature, definition, and call-site guidance in Coach.",
    keywords: ["function", "hover", "signature", "definition", "call site", "intellisense"],
  },
  {
    id: trainerCommands.coachConceptMastery,
    title: "Coach concept mastery",
    section: "Coaching",
    detail: "Prepare a learn-first concept explanation and teach-back loop in Coach.",
    keywords: ["concept", "theory", "principle", "understand", "compare"],
  },
  {
    id: trainerCommands.coachVocabularyRecall,
    title: "Coach vocabulary and recall",
    section: "Coaching",
    detail: "Prepare a learn-first recall loop for words, terms, and facts in Coach.",
    keywords: ["vocabulary", "word", "memorize", "recall", "flashcard", "term"],
  },
  {
    id: trainerCommands.coachMathDerivation,
    title: "Coach mathematics derivation",
    section: "Coaching",
    detail: "Prepare a step-by-step derivation and verification loop in Coach.",
    keywords: ["math", "derivation", "proof", "physics", "calculus", "equation"],
  },
  {
    id: trainerCommands.coachWritingRevision,
    title: "Coach writing revision",
    section: "Coaching",
    detail: "Prepare a learn-first writing revision loop in Coach.",
    keywords: ["writing", "essay", "revision", "grammar", "English", "Chinese"],
  },
  {
    id: trainerCommands.coachReadingTransfer,
    title: "Coach reading and transfer",
    section: "Coaching",
    detail: "Prepare source-grounded reading, recall, and transfer in Coach.",
    keywords: ["reading", "book", "article", "comprehension", "transfer", "literature"],
  },
  {
    id: trainerCommands.generatePlan,
    title: "Generate plan",
    section: "Plans",
    detail: "Generate or regenerate the current learning plan.",
    keywords: ["generate", "plan", "learning", "cadence"],
  },
  {
    id: trainerCommands.updatePlan,
    title: "Freeze current plan",
    section: "Plans",
    detail: "Toggle the frozen state of the current plan.",
    keywords: ["freeze", "plan", "lock", "unlock"],
  },
  {
    id: trainerCommands.createGlobalPlan,
    title: "Create global plan",
    section: "Plans",
    detail: "Explicitly create a cross-project learning plan from the current profile.",
    keywords: ["global", "master", "plan", "cross-project"],
  },
  {
    id: trainerCommands.linkCurrentProjectPlan,
    title: "Link current project plan",
    section: "Plans",
    detail: "Explicitly link this workspace's formal plan to the global plan.",
    keywords: ["global", "link", "project", "plan"],
  },
  {
    id: trainerCommands.taskSpecify,
    title: "Specify task from prompt",
    section: "Tasks",
    detail: "Turn a natural-language goal into a structured task spec.",
    keywords: ["specify", "task", "prompt", "requirements", "spec"],
  },
  {
    id: trainerCommands.nextTask,
    title: "Request next task",
    section: "Tasks",
    detail: "Generate the next practice task from the current plan and memory.",
    shortcut: "Ctrl/Cmd+.",
    keywords: ["next", "task", "practice", "advance"],
  },
  {
    id: trainerCommands.evaluateCurrentFile,
    title: "Evaluate current file",
    section: "Reviews",
    detail: "Run the current file through the Trainer evaluation loop.",
    keywords: ["evaluate", "current", "file", "review", "checks"],
  },
  {
    id: trainerCommands.evaluateSelection,
    title: "Evaluate selection",
    section: "Reviews",
    detail: "Run the current editor selection through the Trainer evaluation loop.",
    keywords: ["evaluate", "selection", "snippet", "review", "checks"],
  },
  {
    id: trainerCommands.refreshMemory,
    title: "Refresh memory",
    section: "Memory",
    detail: "Reload the latest profile, plan, and reflection summary from the sidecar.",
    keywords: ["refresh", "memory", "profile", "summary"],
  },
  {
    id: trainerCommands.recordUserFeedback,
    title: "Record learning feedback",
    section: "Memory",
    detail: "Tell Trainer when a Coach response or training card needs adjustment without changing the formal plan.",
    keywords: ["feedback", "too hard", "too simple", "misunderstood", "resource", "plan", "card"],
  },
  {
    id: trainerCommands.chooseTrainerWorkspaceRoot,
    title: "Choose Trainer Workspace Root",
    section: "Workspace",
    detail: "Choose the folder where Trainer keeps managed projects and long-lived learning artifacts.",
    keywords: ["workspace", "root", "setup", "folder", "trainer"],
  },
  {
    id: trainerCommands.migrateTrainerWorkspaceRoot,
    title: "Migrate Trainer Workspace Root",
    section: "Workspace",
    detail: "Copy the current Trainer workspace into an empty folder and continue from the new root.",
    keywords: ["workspace", "root", "migrate", "move", "copy", "recover"],
  },
  {
    id: trainerCommands.backupTrainerWorkspace,
    title: "Back Up Trainer Workspace",
    section: "Workspace",
    detail: "Create a recoverable copy of the current Trainer workspace in an empty folder.",
    keywords: ["workspace", "backup", "copy", "recovery", "snapshot"],
  },
  {
    id: trainerCommands.restoreTrainerWorkspaceBackup,
    title: "Restore Trainer Workspace Backup",
    section: "Workspace",
    detail: "Restore a Trainer workspace backup into an empty folder and make it the active root.",
    keywords: ["workspace", "restore", "backup", "recovery", "resume"],
  },
  {
    id: trainerCommands.adoptWorkspaceProject,
    title: "Add current project to Trainer",
    section: "Workspace",
    detail: "Create a managed Trainer project record for the current VS Code folder.",
    keywords: ["workspace", "project", "add", "manage", "adopt"],
  },
  {
    id: trainerCommands.browseWorkspaceProject,
    title: "Browse current project with Trainer",
    section: "Workspace",
    detail: "Keep the current project read-only and do not create long-lived project memory.",
    keywords: ["workspace", "project", "browse", "read-only"],
  },
  {
    id: trainerCommands.ignoreWorkspaceProject,
    title: "Ignore current project in Trainer",
    section: "Workspace",
    detail: "Record that Trainer should not manage the current VS Code folder.",
    keywords: ["workspace", "project", "ignore"],
  },
  {
    id: trainerCommands.deleteWorkspaceProject,
    title: "Delete current project from Trainer",
    section: "Workspace",
    detail: "Remove the current managed project from Trainer. Stored records stay on that project's lane; live plan, task, and cards do not stay open.",
    keywords: ["workspace", "project", "delete", "remove"],
  },
  {
    id: trainerCommands.refreshWorkspaceAuthority,
    title: "Refresh workspace authority",
    section: "Memory",
    detail: "Reload the active workspace root, permission level, and trash boundary.",
    keywords: ["workspace", "authority", "boundary", "refresh", "permission"],
  },
  {
    id: trainerCommands.saveCoachSettings,
    title: "Save coach settings",
    section: "Memory",
    detail: "Persist the coach language, answer style, context defaults, and memory strategy.",
    keywords: ["save", "coach", "settings", "defaults", "memory", "language"],
  },
  {
    id: trainerCommands.grantMemoryShare,
    title: "Allow project memory sharing",
    section: "Memory",
    detail: "Select a managed project whose reusable preferences and mastery signals may be read here.",
    keywords: ["memory", "share", "project", "allow", "preferences", "mastery"],
  },
  {
    id: trainerCommands.revokeMemoryShare,
    title: "Revoke project memory sharing",
    section: "Memory",
    detail: "Immediately stop reading previously authorized project memory.",
    keywords: ["memory", "share", "revoke", "project", "privacy"],
  },
  {
    id: trainerCommands.uploadResource,
    title: "Upload resource",
    section: "Resources",
    detail: "Attach a new PDF, image, markdown file, text, code sample, or URL.",
    keywords: ["upload", "resource", "attach", "ingest"],
  },
  {
    id: trainerCommands.indexResources,
    title: "Index resources",
    section: "Resources",
    detail: "Run indexing over the currently attached resources.",
    keywords: ["index", "resources", "chunks", "search"],
  },
  {
    id: trainerCommands.confirmResourceOrganization,
    title: "Confirm resource organization",
    section: "Resources",
    detail: "Apply the pending organize_resources proposal after reviewing it.",
    keywords: ["organize", "confirm", "resources", "sandbox", "commit"],
  },
  {
    id: trainerCommands.cancelResourceOrganization,
    title: "Cancel resource organization",
    section: "Resources",
    detail: "Dismiss the pending organize_resources proposal without committing.",
    keywords: ["organize", "cancel", "resources", "sandbox"],
  },
  {
    id: trainerCommands.refreshResourceTrash,
    title: "Refresh resource Trash",
    section: "Resources",
    detail: "Reload deleted resources that can still be restored in this workspace.",
    keywords: ["resources", "trash", "deleted", "restore", "refresh"],
  },
  {
    id: trainerCommands.refreshSandbox,
    title: "Refresh sandbox capability",
    section: "Resources",
    detail: "Rebuild the governed sandbox capability summary for the current workspace.",
    keywords: ["sandbox", "capability", "refresh", "network", "guard"],
  },
  {
    id: trainerCommands.revealSandboxPath,
    title: "Open sandbox path",
    section: "Resources",
    detail: "Reveal the sandbox root or current sandbox path in the system file manager.",
    keywords: ["sandbox", "open", "reveal", "folder", "finder", "explorer"],
  },
  {
    id: trainerCommands.chooseSandboxRoot,
    title: "Choose sandbox root",
    section: "Resources",
    detail: "Pick the fixed workspace sandbox root used for this Trainer project layout.",
    keywords: ["sandbox", "root", "folder", "workspace", "choose", "fixed"],
  },
  {
    id: trainerCommands.resetSandboxRoot,
    title: "Use default sandbox root",
    section: "Resources",
    detail: "Return this workspace to the default Trainer-managed sandbox root.",
    keywords: ["sandbox", "root", "reset", "default", "workspace"],
  },
  {
    id: trainerCommands.createSandboxFile,
    title: "Create sandbox file",
    section: "Resources",
    detail: "Create a new file inside the managed resource sandbox.",
    keywords: ["sandbox", "file", "create", "write", "draft"],
  },
  {
    id: trainerCommands.createSandboxDirectory,
    title: "Create sandbox directory",
    section: "Resources",
    detail: "Create one or more nested folders inside the managed resource sandbox.",
    keywords: ["sandbox", "folder", "directory", "mkdir", "nested"],
  },
  {
    id: trainerCommands.renameSandboxPath,
    title: "Rename sandbox path",
    section: "Resources",
    detail: "Rename or move a sandbox file or folder without leaving the governed root.",
    keywords: ["sandbox", "rename", "move", "path", "reorganize"],
  },
  {
    id: trainerCommands.deleteSandboxPath,
    title: "Delete sandbox path",
    section: "Resources",
    detail: "Move a sandbox file or folder into governed trash for later restore.",
    keywords: ["sandbox", "delete", "trash", "remove", "restore"],
  },
  {
    id: trainerCommands.deleteSandboxPaths,
    title: "Delete selected sandbox paths",
    section: "Resources",
    detail: "Move multiple sandbox files or folders into governed trash in one run.",
    keywords: ["sandbox", "delete", "trash", "bulk", "multi-select"],
  },
  {
    id: trainerCommands.chooseManagedDataFolder,
    title: "Choose managed data folder",
    section: "Resources",
    detail: "Pick the Trainer-managed data folder used for backend state and fallback sandbox data.",
    keywords: ["resources", "managed", "data", "folder", "sandbox", "storage"],
  },
  {
    id: trainerCommands.resetManagedDataFolder,
    title: "Use recommended managed data folder",
    section: "Resources",
    detail: "Reset Trainer-managed data back to the recommended extension-owned folder.",
    keywords: ["resources", "managed", "data", "folder", "reset", "recommended"],
  },
  {
    id: trainerCommands.evidenceEnqueue,
    title: "Enqueue evidence",
    section: "Reviews",
    detail: "Add structured evidence to the governed plan queue.",
    keywords: ["evidence", "enqueue", "queue", "plan", "review"],
  },
  {
    id: trainerCommands.evidenceAdopt,
    title: "Adopt evidence",
    section: "Reviews",
    detail: "Adopt a queued evidence item into the plan.",
    keywords: ["evidence", "adopt", "plan", "review"],
  },
  {
    id: trainerCommands.evidenceReject,
    title: "Reject evidence",
    section: "Reviews",
    detail: "Reject a queued evidence item and record why.",
    keywords: ["evidence", "reject", "plan", "review"],
  },
  {
    id: trainerCommands.evidenceDefer,
    title: "Defer evidence",
    section: "Reviews",
    detail: "Defer a queued evidence item for later review.",
    keywords: ["evidence", "defer", "snooze", "review"],
  },
  {
    id: trainerCommands.evidenceRefreshQueue,
    title: "Refresh evidence queue",
    section: "Reviews",
    detail: "Reload the current plan evidence queue snapshot.",
    keywords: ["evidence", "refresh", "queue", "review"],
  },
  {
    id: trainerCommands.trainingCardStatusTransition,
    title: "Move training card",
    section: "Training",
    detail: "Transition the current training card to another governed status.",
    keywords: ["training", "card", "status", "move", "transition"],
  },
  {
    id: trainerCommands.trainingGenerateCard,
    title: "Generate training card",
    section: "Training",
    detail: "Create a fresh training card from the current project, focus area, or resource.",
    keywords: ["training", "generate", "card", "practice", "flash"],
  },
  {
    id: trainerCommands.trainingFlashcardCreate,
    title: "Create flashcard",
    section: "Training",
    detail: "Turn a learner prompt or insight into a structured flashcard.",
    keywords: ["training", "flashcard", "create", "memory"],
  },
  {
    id: trainerCommands.trainingFlashcardAnswer,
    title: "Submit flashcard answer",
    section: "Training",
    detail: "Submit a flashcard response back into the governed training loop.",
    keywords: ["training", "flashcard", "answer", "submit"],
  },
  {
    id: trainerCommands.trainingTheoryDrillAnswer,
    title: "Submit theory drill answer",
    section: "Training",
    detail: "Submit a theory-drill response back into the training loop.",
    keywords: ["training", "theory", "drill", "answer", "submit"],
  },
  {
    id: trainerCommands.trainingPracticeReturn,
    title: "Submit practice return",
    section: "Training",
    detail: "Return a verified result or blocker from the current training card back into the governed loop.",
    keywords: ["training", "practice", "return", "verify", "blocker"],
  },
  {
    id: trainerCommands.trainingReflect,
    title: "Record training reflection",
    section: "Training",
    detail: "Persist the reflection required after trusted verification and before returning a training handoff.",
    keywords: ["training", "reflect", "reflection", "verify"],
  },
  {
    id: trainerCommands.trainingReturn,
    title: "Complete training return",
    section: "Training",
    detail: "Complete the durable return after the current training handoff has been reflected.",
    keywords: ["training", "return", "handoff", "complete"],
  },
  {
    id: trainerCommands.trainingReliabilityControl,
    title: "Control training reliability",
    section: "Training",
    detail: "Cancel, expire, or recover a training save after timeout or failure.",
    keywords: ["training", "reliability", "cancel", "timeout", "recover"],
  },
  {
    id: trainerCommands.trainingDependencySkillMapAction,
    title: "Dependency skill map action",
    section: "Training",
    detail: "Apply a governed dependency-skill-map action from the training surface.",
    keywords: ["training", "dependency", "skill", "map", "action"],
  },
  {
    id: trainerCommands.trainingReviewQueueAction,
    title: "Review queue action",
    section: "Training",
    detail: "Apply an action to a queued review item from the training surface.",
    keywords: ["training", "review", "queue", "action"],
  },
  {
    id: trainerCommands.trainingScenarioLabAction,
    title: "Scenario lab action",
    section: "Training",
    detail: "Apply a governed action to the active scenario lab item.",
    keywords: ["training", "scenario", "lab", "action"],
  },
  {
    id: trainerCommands.configureProvider,
    title: "Configure provider",
    section: "Provider",
    detail: "Update OpenAI-compatible provider settings and API key references.",
    keywords: ["provider", "configure", "openai-compatible", "api key"],
  },
  {
    id: trainerCommands.saveProvider,
    title: "Save provider from sidebar",
    section: "Provider",
    detail: "Save provider settings directly from the Trainer sidebar settings panel.",
    keywords: ["provider", "save", "sidebar", "settings", "api key"],
  },
  {
    id: trainerCommands.clearProvider,
    title: "Clear provider",
    section: "Provider",
    detail: "Remove the saved provider configuration and API key reference.",
    keywords: ["provider", "clear", "reset", "api key", "settings"],
  },
  {
    id: trainerCommands.testProvider,
    title: "Test provider",
    section: "Provider",
    detail: "Run a connectivity and capability smoke test against the configured provider.",
    keywords: ["provider", "test", "connectivity", "capabilities"],
  },
  {
    id: trainerCommands.refreshProviderModels,
    title: "Refresh provider models",
    section: "Provider",
    detail: "Force-refresh the model list for the configured provider.",
    keywords: ["provider", "models", "refresh", "list", "cache"],
  },
  {
    id: trainerCommands.switchProviderModel,
    title: "Switch provider model",
    section: "Provider",
    detail: "Switch the active model inside the current provider connection.",
    keywords: ["provider", "model", "switch", "composer", "sidebar"],
  },
  {
    id: trainerCommands.saveProviderProfile,
    title: "Save provider as profile",
    section: "Provider",
    detail: "Store the current provider draft as a reusable profile and activate it.",
    keywords: ["provider", "profile", "save", "draft", "settings"],
  },
  {
    id: trainerCommands.openWorkspaceConfig,
    title: "Open workspace config",
    section: "Provider",
    detail: "Open the workspace-level Trainer config file for direct editing.",
    keywords: ["config", "workspace", "json", "provider", "settings"],
  },
  {
    id: trainerCommands.restartSidecar,
    title: "Restart sidecar",
    section: "Sidecar",
    detail: "Restart the local FastAPI sidecar process.",
    keywords: ["restart", "sidecar", "server", "fastapi"],
  },
  {
    id: trainerCommands.stopSidecar,
    title: "Stop sidecar",
    section: "Sidecar",
    detail: "Stop the local FastAPI sidecar process.",
    keywords: ["stop", "sidecar", "server", "fastapi"],
  },
] as const;

export const researchCompatibilityCommandCatalog: TrainerCommandCatalogItem[] = [
  {
    id: trainerCommands.createResearch,
    title: "Create research project",
    section: "Research",
    detail: "Start a new multi-theme research project with time-based orchestration.",
    keywords: ["research", "create", "project", "theme", "orchestration"],
  },
  {
    id: trainerCommands.addResearchTheme,
    title: "Add research theme",
    section: "Research",
    detail: "Add a new research theme with configurable duration and cadence.",
    keywords: ["research", "theme", "add", "duration"],
  },
  {
    id: trainerCommands.activateResearchTheme,
    title: "Activate research theme",
    section: "Research",
    detail: "Activate a research theme to begin agent-driven research.",
    keywords: ["research", "theme", "activate", "start"],
  },
  {
    id: trainerCommands.advanceResearch,
    title: "Advance research",
    section: "Research",
    detail: "Advance the research agent to the next iteration or checkpoint.",
    keywords: ["research", "advance", "iterate", "checkpoint"],
  },
  {
    id: trainerCommands.researchMessage,
    title: "Send research message",
    section: "Research",
    detail: "Send a message to the research agent through the workbench gate.",
    keywords: ["research", "message", "chat", "agent"],
  },
  {
    id: trainerCommands.approveResearchDecision,
    title: "Approve research decision",
    section: "Research",
    detail: "Approve or reject a pending research agent decision.",
    keywords: ["research", "approve", "decision", "review"],
  },
  {
    id: trainerCommands.getResearchStatus,
    title: "Get research status",
    section: "Research",
    detail: "View current research project status, schedule, and agent state.",
    keywords: ["research", "status", "schedule", "progress"],
  },
] as const;
