export const ORIENTATION_LOCALES = [
  "zh-CN",
  "en-US",
  "es-ES",
  "fr-FR",
  "de-DE",
  "ja-JP",
  "ko-KR",
  "pt-BR",
] as const;

export type OrientationLocale = (typeof ORIENTATION_LOCALES)[number];

export function resolveOrientationLocale(language?: string): OrientationLocale {
  for (const locale of ORIENTATION_LOCALES) {
    if (locale === language) {
      return locale;
    }
  }
  return "en-US";
}

export interface CoachOrientationCopy {
  runtime: string;
  sidecarUnavailable: string;
  openSettings: string;
  restoreSidecar: string;
  settingsRuntime: string;
  sidecarStarting: string;
  wait: string;
  waitUntilReady: string;
  provider: string;
  noProvider: string;
  saveAndTestProvider: string;
  settingsProvider: string;
  workspace: string;
  workspaceBlocked: string;
  openWorkspace: string;
  resolveWorkspace: string;
  settingsWorkspace: string;
  thisTurn: string;
  turnInterrupted: string;
  resume: string;
  resumeCheckpoint: string;
  coachCheckpoint: string;
  coachWorking: string;
  waitReply: string;
  waitTurnEnd: string;
  conversation: string;
  currentTrainingCard: string;
  trainingAwaitingAck: string;
  waitAck: string;
  waitSnapshot: string;
  trainingSaveStatus: string;
  trainingSaveUnacked: string;
  retryTraining: string;
  resubmitTraining: string;
  returnDue: string;
  completeReturn: string;
  completeReturnInTraining: string;
  trainingReturn: string;
  reflectionMissing: string;
  openReflect: string;
  writeEvidence: string;
  trainingReflect: string;
  verifyWaiting: string;
  openVerify: string;
  verifyThenReflect: string;
  trainingVerify: string;
  currentPlan: string;
  openPlan: string;
  clearBlocker: string;
  planEvidenceBlockers: string;
  learnStep: string;
  openTraining: string;
  readThenStart: string;
  tryStep: string;
  smallestChange: string;
  trainingCurrentCard: string;
  currentThread: string;
  continueSpeak: string;
  continueOrCheckPlan: string;
  planCurrentStep: string;
  coachDetailsInPlan: string;
  coachConversation: string;
  noCurrentTurn: string;
  startSpeak: string;
  sayWhatToLearn: string;
  planTrainingAfterObject: string;
  thisConversation: string;
  currentIsConversation: string;
  askOrReturn: string;
  planTraining: string;
  firstLookProject: string;
  firstLookWhy: string;
  firstLookWhere: string;
}

export interface PlanOrientationCopy {
  learningPlan: string;
  noFormalPlan: string;
  generatePlan: string;
  generateMainline: string;
  continueWithoutPlan: string;
  continueWithoutPlanWhy: string;
  planFirstLook: string;
  planEmpty: string;
  currentPlan: string;
  clearBlocker: string;
  clearBlockerThenReturn: (step: string) => string;
  clearThisBlocker: string;
  planEvidenceBlockers: string;
  frozenPlan: string;
  planFrozen: string;
  unfreeze: string;
  frozenReviewOnly: string;
  planFrozenWhere: string;
  pendingEvidence: (count: number) => string;
  reviewEvidence: string;
  confirmEvidence: (binding: string) => string;
  confirmEvidenceThenStep: string;
  planEvidenceQueue: string;
  waitForStep: string;
  wait: string;
  noAuthoritativeStep: string;
  waitRuntimeStep: string;
  planRuntime: string;
  currentMainlineStep: string;
  continueThisStep: string;
  thenVerify: (method: string) => string;
  finishThenVerify: string;
  planCurrentStep: string;
}

export interface ResourcesOrientationCopy {
  resourceLibrary: string;
  libraryEmpty: string;
  importResource: string;
  importThenIndex: string;
  resourcesEmptyLibrary: string;
  currentResource: string;
  indexFailed: string;
  retryIndex: string;
  fixIndexFirst: string;
  resourcesFailedIndex: string;
  sourceUntrusted: string;
  refreshSource: string;
  confirmSourceFirst: string;
  resourcesTrust: string;
  stillIndexing: string;
  wait: string;
  waitIndexThenBind: string;
  resourcesIndexing: string;
  resourceStale: string;
  refreshIndex: string;
  refreshThenBind: string;
  resourcesStale: string;
  resourceSearch: string;
  noHits: (query: string) => string;
  changeQueryOrImport: string;
  resourcesSearch: string;
  hitsFound: (count: number) => string;
  chooseOne: string;
  selectThenPreview: string;
  resourcesSearchHits: string;
  libraryHasItems: (count: number) => string;
  selectBeforePreview: string;
  resourcesList: string;
  boundToPlan: (id: string) => string;
  openPlan: string;
  reviewOnPlan: string;
  resourcesPlanBinding: string;
  boundToCard: (id: string) => string;
  openTraining: string;
  continueCard: string;
  resourcesTrainingBinding: string;
  indexedNoPreview: string;
  preview: string;
  previewBeforeBind: string;
  resourcesPreview: string;
  indexedReadable: string;
  keepReading: string;
  readThenBindWhenLinked: string;
  resourcesCurrentItem: string;
  materialSimpler: string;
  materialCurrent: string;
  materialTransfer: string;
  materialTransferBlocked: string;
}

const COACH_COPY: Record<OrientationLocale, CoachOrientationCopy> = {
  "zh-CN": {
    runtime: "运行时",
    sidecarUnavailable: "Sidecar 当前不可用。",
    openSettings: "查看设置",
    restoreSidecar: "先恢复 sidecar，再继续对话。",
    settingsRuntime: "设置 · 运行状态",
    sidecarStarting: "Sidecar 还在启动或状态未确认。",
    wait: "等待就绪",
    waitUntilReady: "等运行时就绪后再发送。",
    provider: "模型连接",
    noProvider: "还没有可用的模型连接。",
    saveAndTestProvider: "先保存并测试模型连接。",
    settingsProvider: "设置 · 模型连接",
    workspace: "当前工作区",
    workspaceBlocked: "当前工作区还不能开始教练回合。",
    openWorkspace: "查看工作区",
    resolveWorkspace: "先处理工作区限制。",
    settingsWorkspace: "设置 · 工作区",
    thisTurn: "本轮对话",
    turnInterrupted: "这一轮已中断，但进度已保存。",
    resume: "恢复进度",
    resumeCheckpoint: "从已保存进度继续，或查看记录。",
    coachCheckpoint: "对话 · checkpoint",
    coachWorking: "教练正在处理这一轮。",
    waitReply: "等待回复",
    waitTurnEnd: "等这轮结束后再决定下一步。",
    conversation: "对话流",
    currentTrainingCard: "当前训练卡",
    trainingAwaitingAck: "训练步骤还在等待 sidecar 确认。",
    waitAck: "等待确认",
    waitSnapshot: "先等快照回来，不要重复提交。",
    trainingSaveStatus: "训练 · 保存状态",
    trainingSaveUnacked: "这次训练保存还没有被权威快照确认。",
    retryTraining: "去训练重试",
    resubmitTraining: "回到训练再提交一次。",
    returnDue: "验证和复盘已在卡上，还差回流转正。",
    completeReturn: "去完成回落",
    completeReturnInTraining: "在训练里完成 Return。",
    trainingReturn: "训练 · 回落",
    reflectionMissing: "可信验证已在，还差一条复盘。",
    openReflect: "去复盘",
    writeEvidence: "先写下这条证据说明了什么。",
    trainingReflect: "训练 · 复盘",
    verifyWaiting: "这张卡还在等可信验证。",
    openVerify: "去验证",
    verifyThenReflect: "先验证当前结果，再复盘。",
    trainingVerify: "训练 · 验证",
    currentPlan: "当前计划",
    openPlan: "查看计划",
    clearBlocker: "先处理这个 blocker。",
    planEvidenceBlockers: "计划 · 证据与阻碍",
    learnStep: "当前对象是这张训练卡的学习步骤。",
    openTraining: "打开训练",
    readThenStart: "先看清任务，再开始做。",
    tryStep: "当前对象是这张训练卡的尝试步骤。",
    smallestChange: "做最小改动，然后验证。",
    trainingCurrentCard: "训练 · 当前卡",
    currentThread: "这是当前主线。",
    continueSpeak: "继续说",
    continueOrCheckPlan: "围绕这个对象继续，或先核对计划。",
    planCurrentStep: "计划 · 当前步骤",
    coachDetailsInPlan: "对话；细节在计划",
    coachConversation: "教练对话",
    noCurrentTurn: "还没有当前回合。",
    startSpeak: "开始说",
    sayWhatToLearn: "在下方输入你现在想学或想做的事。",
    planTrainingAfterObject: "计划 / 训练会在有对象后出现",
    thisConversation: "本轮对话",
    currentIsConversation: "当前对象是这场教练对话。",
    askOrReturn: "接着问，或把结果带回计划 / 训练。",
    planTraining: "计划 / 训练",
    firstLookProject: "当前项目",
    firstLookWhy: "这是对这个工作区的第一眼判断。",
    firstLookWhere: "对话 · 第一眼",
  },
  "en-US": {
    runtime: "Runtime",
    sidecarUnavailable: "The sidecar is not available.",
    openSettings: "Open Settings",
    restoreSidecar: "Restore the sidecar, then continue.",
    settingsRuntime: "Settings · runtime",
    sidecarStarting: "The sidecar is still starting or unconfirmed.",
    wait: "Wait",
    waitUntilReady: "Wait until runtime is ready before sending.",
    provider: "Provider",
    noProvider: "No usable model connection is available.",
    saveAndTestProvider: "Save and test a model connection first.",
    settingsProvider: "Settings · provider",
    workspace: "Workspace",
    workspaceBlocked: "This workspace cannot start a coaching turn yet.",
    openWorkspace: "Open Settings",
    resolveWorkspace: "Resolve the workspace restriction first.",
    settingsWorkspace: "Settings · workspace",
    thisTurn: "This turn",
    turnInterrupted: "This turn was interrupted, and progress was saved.",
    resume: "Resume",
    resumeCheckpoint: "Resume the saved progress, or review the record.",
    coachCheckpoint: "Coach · checkpoint",
    coachWorking: "The coach is working on this turn.",
    waitReply: "Wait",
    waitTurnEnd: "Wait for this turn to finish before the next move.",
    conversation: "Conversation",
    currentTrainingCard: "Current training card",
    trainingAwaitingAck: "The training step is waiting for sidecar acknowledgement.",
    waitAck: "Wait",
    waitSnapshot: "Wait for the snapshot. Do not submit again yet.",
    trainingSaveStatus: "Training · save status",
    trainingSaveUnacked: "This training save was not accepted by the snapshot.",
    retryTraining: "Retry in Training",
    resubmitTraining: "Return to Training and submit again.",
    returnDue: "Verification and reflection are on the card; return is still due.",
    completeReturn: "Complete return",
    completeReturnInTraining: "Complete Return in Training.",
    trainingReturn: "Training · return",
    reflectionMissing: "Trusted verification is in; reflection is still missing.",
    openReflect: "Open Training",
    writeEvidence: "Write what this evidence proves.",
    trainingReflect: "Training · reflect",
    verifyWaiting: "This card is still waiting for trusted verification.",
    openVerify: "Open Training",
    verifyThenReflect: "Verify the current result, then reflect.",
    trainingVerify: "Training · verify",
    currentPlan: "Current plan",
    openPlan: "Open Plan",
    clearBlocker: "Clear this blocker first.",
    planEvidenceBlockers: "Plan · evidence and blockers",
    learnStep: "The current object is this card's learn step.",
    openTraining: "Open Training",
    readThenStart: "Read the task, then start.",
    tryStep: "The current object is this card's try step.",
    smallestChange: "Make the smallest change, then verify.",
    trainingCurrentCard: "Training · current card",
    currentThread: "This is the current thread.",
    continueSpeak: "Continue",
    continueOrCheckPlan: "Continue on this object, or check Plan.",
    planCurrentStep: "Plan · current step",
    coachDetailsInPlan: "Coach; details in Plan",
    coachConversation: "Coach conversation",
    noCurrentTurn: "There is no current turn yet.",
    startSpeak: "Start",
    sayWhatToLearn: "Say what you want to learn or do next.",
    planTrainingAfterObject: "Plan / Training appear after there is an object",
    thisConversation: "This conversation",
    currentIsConversation: "The current object is this coaching conversation.",
    askOrReturn: "Ask the next question, or return a result to Plan / Training.",
    planTraining: "Plan / Training",
    firstLookProject: "This project",
    firstLookWhy: "This is the first-look next for this workspace.",
    firstLookWhere: "Coach · first look",
  },
  "es-ES": {
    runtime: "Runtime",
    sidecarUnavailable: "El sidecar no está disponible.",
    openSettings: "Abrir Ajustes",
    restoreSidecar: "Recupera el sidecar y luego continúa.",
    settingsRuntime: "Ajustes · runtime",
    sidecarStarting: "El sidecar aún arranca o no está confirmado.",
    wait: "Esperar",
    waitUntilReady: "Espera a que el runtime esté listo antes de enviar.",
    provider: "Conexión",
    noProvider: "No hay una conexión de modelo usable.",
    saveAndTestProvider: "Guarda y prueba una conexión de modelo primero.",
    settingsProvider: "Ajustes · provider",
    workspace: "Espacio",
    workspaceBlocked: "Este espacio aún no puede empezar un turno.",
    openWorkspace: "Abrir Ajustes",
    resolveWorkspace: "Resuelve primero la restricción del espacio.",
    settingsWorkspace: "Ajustes · espacio",
    thisTurn: "Este turno",
    turnInterrupted: "Este turno se interrumpió y el progreso quedó guardado.",
    resume: "Reanudar",
    resumeCheckpoint: "Reanuda el progreso guardado o revisa el registro.",
    coachCheckpoint: "Coach · checkpoint",
    coachWorking: "El coach está trabajando este turno.",
    waitReply: "Esperar",
    waitTurnEnd: "Espera a que termine este turno antes del siguiente paso.",
    conversation: "Conversación",
    currentTrainingCard: "Tarjeta actual",
    trainingAwaitingAck: "El paso de entrenamiento espera confirmación del sidecar.",
    waitAck: "Esperar",
    waitSnapshot: "Espera la instantánea. No vuelvas a enviar aún.",
    trainingSaveStatus: "Entrenamiento · guardado",
    trainingSaveUnacked: "Este guardado no fue aceptado por la instantánea.",
    retryTraining: "Reintentar en Entrenamiento",
    resubmitTraining: "Vuelve a Entrenamiento y envía otra vez.",
    returnDue: "La verificación y la reflexión ya están; falta el retorno.",
    completeReturn: "Completar retorno",
    completeReturnInTraining: "Completa el retorno en Entrenamiento.",
    trainingReturn: "Entrenamiento · retorno",
    reflectionMissing: "Hay verificación fiable; falta la reflexión.",
    openReflect: "Abrir Entrenamiento",
    writeEvidence: "Escribe qué demuestra esta evidencia.",
    trainingReflect: "Entrenamiento · reflexión",
    verifyWaiting: "Esta tarjeta aún espera una verificación fiable.",
    openVerify: "Abrir Entrenamiento",
    verifyThenReflect: "Verifica el resultado y luego reflexiona.",
    trainingVerify: "Entrenamiento · verificar",
    currentPlan: "Plan actual",
    openPlan: "Abrir Plan",
    clearBlocker: "Quita primero este bloqueo.",
    planEvidenceBlockers: "Plan · evidencia y bloqueos",
    learnStep: "El objeto actual es el paso de aprendizaje de esta tarjeta.",
    openTraining: "Abrir Entrenamiento",
    readThenStart: "Lee la tarea y luego empieza.",
    tryStep: "El objeto actual es el paso de intento de esta tarjeta.",
    smallestChange: "Haz el cambio más pequeño y verifica.",
    trainingCurrentCard: "Entrenamiento · tarjeta actual",
    currentThread: "Esta es la línea actual.",
    continueSpeak: "Continuar",
    continueOrCheckPlan: "Sigue con este objeto o revisa el Plan.",
    planCurrentStep: "Plan · paso actual",
    coachDetailsInPlan: "Coach; detalles en Plan",
    coachConversation: "Conversación",
    noCurrentTurn: "Aún no hay un turno actual.",
    startSpeak: "Empezar",
    sayWhatToLearn: "Di qué quieres aprender o hacer ahora.",
    planTrainingAfterObject: "Plan / Entrenamiento aparecen cuando hay un objeto",
    thisConversation: "Esta conversación",
    currentIsConversation: "El objeto actual es esta conversación.",
    askOrReturn: "Haz la siguiente pregunta o lleva el resultado a Plan / Entrenamiento.",
    planTraining: "Plan / Entrenamiento",
    firstLookProject: "Este proyecto",
    firstLookWhy: "Este es el siguiente paso del primer vistazo.",
    firstLookWhere: "Chat · primer vistazo",
  },
  "fr-FR": {
    runtime: "Runtime",
    sidecarUnavailable: "Le sidecar n'est pas disponible.",
    openSettings: "Ouvrir Réglages",
    restoreSidecar: "Rétablissez le sidecar, puis continuez.",
    settingsRuntime: "Réglages · runtime",
    sidecarStarting: "Le sidecar démarre encore ou n'est pas confirmé.",
    wait: "Attendre",
    waitUntilReady: "Attendez que le runtime soit prêt avant d'envoyer.",
    provider: "Connexion",
    noProvider: "Aucune connexion de modèle n'est utilisable.",
    saveAndTestProvider: "Enregistrez et testez d'abord une connexion de modèle.",
    settingsProvider: "Réglages · provider",
    workspace: "Espace",
    workspaceBlocked: "Cet espace ne peut pas encore lancer un tour.",
    openWorkspace: "Ouvrir Réglages",
    resolveWorkspace: "Levez d'abord la restriction de l'espace.",
    settingsWorkspace: "Réglages · espace",
    thisTurn: "Ce tour",
    turnInterrupted: "Ce tour a été interrompu, et la progression est enregistrée.",
    resume: "Reprendre",
    resumeCheckpoint: "Reprenez la progression enregistrée, ou relisez le journal.",
    coachCheckpoint: "Coach · checkpoint",
    coachWorking: "Le coach traite ce tour.",
    waitReply: "Attendre",
    waitTurnEnd: "Attendez la fin de ce tour avant le prochain pas.",
    conversation: "Conversation",
    currentTrainingCard: "Carte actuelle",
    trainingAwaitingAck: "L'étape d'entraînement attend la confirmation du sidecar.",
    waitAck: "Attendre",
    waitSnapshot: "Attendez l'instantané. Ne renvoyez pas encore.",
    trainingSaveStatus: "Entraînement · enregistrement",
    trainingSaveUnacked: "Cet enregistrement n'a pas été accepté par l'instantané.",
    retryTraining: "Réessayer dans Entraînement",
    resubmitTraining: "Revenez à Entraînement et renvoyez.",
    returnDue: "Vérification et réflexion sont là ; le retour reste dû.",
    completeReturn: "Terminer le retour",
    completeReturnInTraining: "Terminez le retour dans Entraînement.",
    trainingReturn: "Entraînement · retour",
    reflectionMissing: "La vérification fiable est là ; la réflexion manque.",
    openReflect: "Ouvrir Entraînement",
    writeEvidence: "Écrivez ce que cette preuve montre.",
    trainingReflect: "Entraînement · réflexion",
    verifyWaiting: "Cette carte attend encore une vérification fiable.",
    openVerify: "Ouvrir Entraînement",
    verifyThenReflect: "Vérifiez le résultat, puis réfléchissez.",
    trainingVerify: "Entraînement · vérifier",
    currentPlan: "Plan actuel",
    openPlan: "Ouvrir Plan",
    clearBlocker: "Levez d'abord ce blocage.",
    planEvidenceBlockers: "Plan · preuves et blocages",
    learnStep: "L'objet actuel est l'étape d'apprentissage de cette carte.",
    openTraining: "Ouvrir Entraînement",
    readThenStart: "Lisez la tâche, puis commencez.",
    tryStep: "L'objet actuel est l'étape d'essai de cette carte.",
    smallestChange: "Faites le plus petit changement, puis vérifiez.",
    trainingCurrentCard: "Entraînement · carte actuelle",
    currentThread: "C'est le fil actuel.",
    continueSpeak: "Continuer",
    continueOrCheckPlan: "Continuez sur cet objet, ou vérifiez le Plan.",
    planCurrentStep: "Plan · étape actuelle",
    coachDetailsInPlan: "Coach ; détails dans Plan",
    coachConversation: "Conversation",
    noCurrentTurn: "Il n'y a pas encore de tour actuel.",
    startSpeak: "Commencer",
    sayWhatToLearn: "Dites ce que vous voulez apprendre ou faire.",
    planTrainingAfterObject: "Plan / Entraînement apparaissent quand un objet existe",
    thisConversation: "Cette conversation",
    currentIsConversation: "L'objet actuel est cette conversation.",
    askOrReturn: "Posez la suite, ou ramenez un résultat vers Plan / Entraînement.",
    planTraining: "Plan / Entraînement",
    firstLookProject: "Ce projet",
    firstLookWhy: "C'est la prochaine étape du premier regard.",
    firstLookWhere: "Coach · premier regard",
  },
  "de-DE": {
    runtime: "Runtime",
    sidecarUnavailable: "Der Sidecar ist nicht verfügbar.",
    openSettings: "Einstellungen öffnen",
    restoreSidecar: "Stelle den Sidecar wieder her und mach dann weiter.",
    settingsRuntime: "Einstellungen · Runtime",
    sidecarStarting: "Der Sidecar startet noch oder ist unbestätigt.",
    wait: "Warten",
    waitUntilReady: "Warte, bis die Runtime bereit ist, bevor du sendest.",
    provider: "Verbindung",
    noProvider: "Es gibt keine nutzbare Modellverbindung.",
    saveAndTestProvider: "Speichere und teste zuerst eine Modellverbindung.",
    settingsProvider: "Einstellungen · Provider",
    workspace: "Arbeitsbereich",
    workspaceBlocked: "Dieser Arbeitsbereich kann noch keinen Coach-Zug starten.",
    openWorkspace: "Einstellungen öffnen",
    resolveWorkspace: "Hebe zuerst die Einschränkung des Arbeitsbereichs auf.",
    settingsWorkspace: "Einstellungen · Arbeitsbereich",
    thisTurn: "Dieser Zug",
    turnInterrupted: "Dieser Zug wurde unterbrochen, der Stand ist gespeichert.",
    resume: "Fortsetzen",
    resumeCheckpoint: "Setze den gespeicherten Stand fort oder prüfe den Verlauf.",
    coachCheckpoint: "Coach · Checkpoint",
    coachWorking: "Der Coach arbeitet an diesem Zug.",
    waitReply: "Warten",
    waitTurnEnd: "Warte, bis dieser Zug endet, bevor der nächste Schritt kommt.",
    conversation: "Gespräch",
    currentTrainingCard: "Aktuelle Karte",
    trainingAwaitingAck: "Der Trainingsschritt wartet auf Sidecar-Bestätigung.",
    waitAck: "Warten",
    waitSnapshot: "Warte auf den Snapshot. Sende noch nicht erneut.",
    trainingSaveStatus: "Training · Speichern",
    trainingSaveUnacked: "Dieses Speichern wurde vom Snapshot nicht bestätigt.",
    retryTraining: "Im Training erneut versuchen",
    resubmitTraining: "Geh zurück zum Training und sende erneut.",
    returnDue: "Prüfung und Reflexion sind da; die Rückkehr steht noch aus.",
    completeReturn: "Rückkehr abschließen",
    completeReturnInTraining: "Schließe die Rückkehr im Training ab.",
    trainingReturn: "Training · Rückkehr",
    reflectionMissing: "Die Prüfung ist da; die Reflexion fehlt noch.",
    openReflect: "Training öffnen",
    writeEvidence: "Schreib auf, was diese Evidenz belegt.",
    trainingReflect: "Training · Reflexion",
    verifyWaiting: "Diese Karte wartet noch auf eine verlässliche Prüfung.",
    openVerify: "Training öffnen",
    verifyThenReflect: "Prüfe das Ergebnis, dann reflektiere.",
    trainingVerify: "Training · prüfen",
    currentPlan: "Aktueller Plan",
    openPlan: "Plan öffnen",
    clearBlocker: "Räume zuerst diesen Blocker.",
    planEvidenceBlockers: "Plan · Evidenz und Blocker",
    learnStep: "Das aktuelle Objekt ist der Lernschritt dieser Karte.",
    openTraining: "Training öffnen",
    readThenStart: "Lies die Aufgabe, dann starte.",
    tryStep: "Das aktuelle Objekt ist der Versuchsschritt dieser Karte.",
    smallestChange: "Mach die kleinste Änderung, dann prüfe.",
    trainingCurrentCard: "Training · aktuelle Karte",
    currentThread: "Das ist der aktuelle Faden.",
    continueSpeak: "Weiter",
    continueOrCheckPlan: "Mach an diesem Objekt weiter oder prüfe den Plan.",
    planCurrentStep: "Plan · aktueller Schritt",
    coachDetailsInPlan: "Coach; Details im Plan",
    coachConversation: "Coach-Gespräch",
    noCurrentTurn: "Es gibt noch keinen aktuellen Zug.",
    startSpeak: "Starten",
    sayWhatToLearn: "Sag, was du jetzt lernen oder tun willst.",
    planTrainingAfterObject: "Plan / Training erscheinen, sobald es ein Objekt gibt",
    thisConversation: "Dieses Gespräch",
    currentIsConversation: "Das aktuelle Objekt ist dieses Coach-Gespräch.",
    askOrReturn: "Frag weiter oder bring ein Ergebnis zu Plan / Training.",
    planTraining: "Plan / Training",
    firstLookProject: "Dieses Projekt",
    firstLookWhy: "Das ist der nächste Schritt aus dem ersten Blick.",
    firstLookWhere: "Coach · erster Blick",
  },
  "ja-JP": {
    runtime: "ランタイム",
    sidecarUnavailable: "Sidecar は今使えません。",
    openSettings: "設定を開く",
    restoreSidecar: "先に Sidecar を戻してから続けてください。",
    settingsRuntime: "設定 · ランタイム",
    sidecarStarting: "Sidecar は起動中か、まだ確認されていません。",
    wait: "待つ",
    waitUntilReady: "ランタイムの準備ができてから送ってください。",
    provider: "モデル接続",
    noProvider: "使えるモデル接続がまだありません。",
    saveAndTestProvider: "先にモデル接続を保存してテストしてください。",
    settingsProvider: "設定 · Provider",
    workspace: "ワークスペース",
    workspaceBlocked: "このワークスペースでは、まだコーチのターンを始められません。",
    openWorkspace: "設定を開く",
    resolveWorkspace: "先にワークスペースの制限を解消してください。",
    settingsWorkspace: "設定 · ワークスペース",
    thisTurn: "このターン",
    turnInterrupted: "このターンは中断されましたが、進捗は保存されています。",
    resume: "再開",
    resumeCheckpoint: "保存した進捗から続けるか、記録を見てください。",
    coachCheckpoint: "対話 · checkpoint",
    coachWorking: "コーチがこのターンを処理しています。",
    waitReply: "待つ",
    waitTurnEnd: "このターンが終わってから次を決めてください。",
    conversation: "会話",
    currentTrainingCard: "現在の訓練カード",
    trainingAwaitingAck: "訓練の手順は Sidecar の確認待ちです。",
    waitAck: "待つ",
    waitSnapshot: "スナップショットを待ってください。まだ再送信しないでください。",
    trainingSaveStatus: "訓練 · 保存状態",
    trainingSaveUnacked: "この訓練の保存はスナップショットで確認されていません。",
    retryTraining: "訓練で再試行",
    resubmitTraining: "訓練に戻ってもう一度送ってください。",
    returnDue: "検証と振り返りはカードにあります。戻りが残っています。",
    completeReturn: "戻りを完了",
    completeReturnInTraining: "訓練で Return を完了してください。",
    trainingReturn: "訓練 · 戻り",
    reflectionMissing: "信頼できる検証はあります。振り返りが残っています。",
    openReflect: "訓練を開く",
    writeEvidence: "この証拠が何を示すかを書いてください。",
    trainingReflect: "訓練 · 振り返り",
    verifyWaiting: "このカードは信頼できる検証待ちです。",
    openVerify: "訓練を開く",
    verifyThenReflect: "先に結果を検証し、それから振り返ってください。",
    trainingVerify: "訓練 · 検証",
    currentPlan: "現在の計画",
    openPlan: "計画を開く",
    clearBlocker: "先にこの阻害を解消してください。",
    planEvidenceBlockers: "計画 · 証拠と阻害",
    learnStep: "現在の対象は、このカードの学習ステップです。",
    openTraining: "訓練を開く",
    readThenStart: "課題を把握してから始めてください。",
    tryStep: "現在の対象は、このカードの試行ステップです。",
    smallestChange: "最小の変更をしてから検証してください。",
    trainingCurrentCard: "訓練 · 現在のカード",
    currentThread: "これが現在の本線です。",
    continueSpeak: "続ける",
    continueOrCheckPlan: "この対象で続けるか、先に計画を確認してください。",
    planCurrentStep: "計画 · 現在の手順",
    coachDetailsInPlan: "対話。詳細は計画",
    coachConversation: "コーチ対話",
    noCurrentTurn: "現在のターンはまだありません。",
    startSpeak: "始める",
    sayWhatToLearn: "今学びたいこと、やりたいことを書いてください。",
    planTrainingAfterObject: "対象ができてから計画 / 訓練が出ます",
    thisConversation: "この対話",
    currentIsConversation: "現在の対象はこのコーチ対話です。",
    askOrReturn: "次を聞くか、結果を計画 / 訓練に戻してください。",
    planTraining: "計画 / 訓練",
    firstLookProject: "このプロジェクト",
    firstLookWhy: "これはこのワークスペースの第一印象の次の一歩です。",
    firstLookWhere: "対話 · 第一印象",
  },
  "ko-KR": {
    runtime: "런타임",
    sidecarUnavailable: "Sidecar를 지금은 쓸 수 없습니다.",
    openSettings: "설정 열기",
    restoreSidecar: "Sidecar를 복구한 뒤 이어가세요.",
    settingsRuntime: "설정 · 런타임",
    sidecarStarting: "Sidecar가 아직 시작 중이거나 확인되지 않았습니다.",
    wait: "기다리기",
    waitUntilReady: "런타임이 준비된 뒤에 보내세요.",
    provider: "모델 연결",
    noProvider: "쓸 수 있는 모델 연결이 없습니다.",
    saveAndTestProvider: "먼저 모델 연결을 저장하고 테스트하세요.",
    settingsProvider: "설정 · Provider",
    workspace: "작업 영역",
    workspaceBlocked: "이 작업 영역에서는 아직 코치 턴을 시작할 수 없습니다.",
    openWorkspace: "설정 열기",
    resolveWorkspace: "먼저 작업 영역 제한을 해결하세요.",
    settingsWorkspace: "설정 · 작업 영역",
    thisTurn: "이번 턴",
    turnInterrupted: "이번 턴이 중단되었지만 진행은 저장되었습니다.",
    resume: "이어가기",
    resumeCheckpoint: "저장한 진행을 이어가거나 기록을 확인하세요.",
    coachCheckpoint: "대화 · checkpoint",
    coachWorking: "코치가 이번 턴을 처리하고 있습니다.",
    waitReply: "기다리기",
    waitTurnEnd: "이번 턴이 끝난 뒤에 다음을 정하세요.",
    conversation: "대화",
    currentTrainingCard: "현재 훈련 카드",
    trainingAwaitingAck: "훈련 단계가 sidecar 확인을 기다리는 중입니다.",
    waitAck: "기다리기",
    waitSnapshot: "스냅샷을 기다리세요. 아직 다시 제출하지 마세요.",
    trainingSaveStatus: "훈련 · 저장 상태",
    trainingSaveUnacked: "이 훈련 저장은 스냅샷에서 확인되지 않았습니다.",
    retryTraining: "훈련에서 다시 시도",
    resubmitTraining: "훈련으로 돌아가 다시 제출하세요.",
    returnDue: "검증과 성찰은 카드에 있습니다. 복귀가 남아 있습니다.",
    completeReturn: "복귀 완료",
    completeReturnInTraining: "훈련에서 Return을 완료하세요.",
    trainingReturn: "훈련 · 복귀",
    reflectionMissing: "신뢰할 검증은 있습니다. 성찰이 남아 있습니다.",
    openReflect: "훈련 열기",
    writeEvidence: "이 증거가 무엇을 보여 주는지 적으세요.",
    trainingReflect: "훈련 · 성찰",
    verifyWaiting: "이 카드는 아직 신뢰할 검증을 기다립니다.",
    openVerify: "훈련 열기",
    verifyThenReflect: "결과를 검증한 뒤 성찰하세요.",
    trainingVerify: "훈련 · 검증",
    currentPlan: "현재 계획",
    openPlan: "계획 열기",
    clearBlocker: "먼저 이 차단을 해결하세요.",
    planEvidenceBlockers: "계획 · 증거와 차단",
    learnStep: "현재 대상은 이 카드의 학습 단계입니다.",
    openTraining: "훈련 열기",
    readThenStart: "과제를 파악한 뒤 시작하세요.",
    tryStep: "현재 대상은 이 카드의 시도 단계입니다.",
    smallestChange: "가장 작은 변경을 한 뒤 검증하세요.",
    trainingCurrentCard: "훈련 · 현재 카드",
    currentThread: "이것이 현재 본선입니다.",
    continueSpeak: "이어가기",
    continueOrCheckPlan: "이 대상에서 이어가거나 먼저 계획을 확인하세요.",
    planCurrentStep: "계획 · 현재 단계",
    coachDetailsInPlan: "대화. 세부 사항은 계획",
    coachConversation: "코치 대화",
    noCurrentTurn: "현재 턴이 아직 없습니다.",
    startSpeak: "시작",
    sayWhatToLearn: "지금 배우고 싶거나 하고 싶은 일을 말하세요.",
    planTrainingAfterObject: "대상이 생긴 뒤에 계획 / 훈련이 나타납니다",
    thisConversation: "이 대화",
    currentIsConversation: "현재 대상은 이 코치 대화입니다.",
    askOrReturn: "다음을 묻거나 결과를 계획 / 훈련으로 되돌리세요.",
    planTraining: "계획 / 훈련",
    firstLookProject: "이 프로젝트",
    firstLookWhy: "이 작업 공간의 첫인상에서 나온 다음 단계입니다.",
    firstLookWhere: "대화 · 첫인상",
  },
  "pt-BR": {
    runtime: "Runtime",
    sidecarUnavailable: "O sidecar não está disponível.",
    openSettings: "Abrir Configurações",
    restoreSidecar: "Recupere o sidecar e depois continue.",
    settingsRuntime: "Configurações · runtime",
    sidecarStarting: "O sidecar ainda está iniciando ou não foi confirmado.",
    wait: "Esperar",
    waitUntilReady: "Espere o runtime ficar pronto antes de enviar.",
    provider: "Conexão",
    noProvider: "Não há uma conexão de modelo usável.",
    saveAndTestProvider: "Salve e teste uma conexão de modelo primeiro.",
    settingsProvider: "Configurações · provider",
    workspace: "Espaço",
    workspaceBlocked: "Este espaço ainda não pode iniciar um turno.",
    openWorkspace: "Abrir Configurações",
    resolveWorkspace: "Resolva primeiro a restrição do espaço.",
    settingsWorkspace: "Configurações · espaço",
    thisTurn: "Este turno",
    turnInterrupted: "Este turno foi interrompido, e o progresso foi salvo.",
    resume: "Retomar",
    resumeCheckpoint: "Retome o progresso salvo ou revise o registro.",
    coachCheckpoint: "Coach · checkpoint",
    coachWorking: "O coach está trabalhando neste turno.",
    waitReply: "Esperar",
    waitTurnEnd: "Espere este turno terminar antes do próximo passo.",
    conversation: "Conversa",
    currentTrainingCard: "Cartão atual",
    trainingAwaitingAck: "A etapa de treino espera a confirmação do sidecar.",
    waitAck: "Esperar",
    waitSnapshot: "Espere o snapshot. Não envie de novo ainda.",
    trainingSaveStatus: "Treino · salvamento",
    trainingSaveUnacked: "Este salvamento não foi aceito pelo snapshot.",
    retryTraining: "Tentar de novo no Treino",
    resubmitTraining: "Volte ao Treino e envie outra vez.",
    returnDue: "Verificação e reflexão já estão no cartão; falta o retorno.",
    completeReturn: "Concluir retorno",
    completeReturnInTraining: "Conclua o Return no Treino.",
    trainingReturn: "Treino · retorno",
    reflectionMissing: "A verificação confiável está feita; falta a reflexão.",
    openReflect: "Abrir Treino",
    writeEvidence: "Escreva o que esta evidência prova.",
    trainingReflect: "Treino · reflexão",
    verifyWaiting: "Este cartão ainda espera uma verificação confiável.",
    openVerify: "Abrir Treino",
    verifyThenReflect: "Verifique o resultado e depois reflita.",
    trainingVerify: "Treino · verificar",
    currentPlan: "Plano atual",
    openPlan: "Abrir Plano",
    clearBlocker: "Resolva primeiro este bloqueio.",
    planEvidenceBlockers: "Plano · evidência e bloqueios",
    learnStep: "O objeto atual é o passo de aprendizado deste cartão.",
    openTraining: "Abrir Treino",
    readThenStart: "Leia a tarefa e depois comece.",
    tryStep: "O objeto atual é o passo de tentativa deste cartão.",
    smallestChange: "Faça a menor mudança e depois verifique.",
    trainingCurrentCard: "Treino · cartão atual",
    currentThread: "Esta é a linha atual.",
    continueSpeak: "Continuar",
    continueOrCheckPlan: "Continue neste objeto ou confira o Plano.",
    planCurrentStep: "Plano · passo atual",
    coachDetailsInPlan: "Coach; detalhes no Plano",
    coachConversation: "Conversa",
    noCurrentTurn: "Ainda não há um turno atual.",
    startSpeak: "Começar",
    sayWhatToLearn: "Diga o que você quer aprender ou fazer agora.",
    planTrainingAfterObject: "Plano / Treino aparecem quando houver um objeto",
    thisConversation: "Esta conversa",
    currentIsConversation: "O objeto atual é esta conversa.",
    askOrReturn: "Pergunte o próximo passo ou leve o resultado ao Plano / Treino.",
    planTraining: "Plano / Treino",
    firstLookProject: "Este projeto",
    firstLookWhy: "Este é o próximo passo do primeiro olhar.",
    firstLookWhere: "Coach · primeiro olhar",
  },
};

const PLAN_COPY: Record<OrientationLocale, PlanOrientationCopy> = {
  "zh-CN": {
    learningPlan: "学习计划",
    noFormalPlan: "还没有可执行的正式计划。",
    generatePlan: "生成计划",
    generateMainline: "先生成一条主线，再决定当前步骤。",
    continueWithoutPlan: "先不生成计划",
    continueWithoutPlanWhy: "这个工作区已有第一眼下一步，先不要发明计划。",
    planFirstLook: "计划 · 第一眼",
    planEmpty: "计划 · 空状态",
    currentPlan: "当前计划",
    clearBlocker: "处理卡点",
    clearBlockerThenReturn: (step) => `先处理卡点，再回到：${step}`,
    clearThisBlocker: "先处理这个 blocker。",
    planEvidenceBlockers: "计划 · 证据与阻碍",
    frozenPlan: "已锁定计划",
    planFrozen: "正式计划已锁定，对话不会默默改写它。",
    unfreeze: "解除锁定",
    frozenReviewOnly: "锁定期间只核对证据，不改主线。",
    planFrozenWhere: "计划 · 锁定",
    pendingEvidence: (count) => `有 ${count} 条证据还没被采纳，计划尚未改写。`,
    reviewEvidence: "核对证据",
    confirmEvidence: (binding) => `先确认：${binding}`,
    confirmEvidenceThenStep: "先确认证据，再推进当前步骤。",
    planEvidenceQueue: "计划 · 证据队列",
    waitForStep: "等待步骤",
    wait: "等待步骤",
    noAuthoritativeStep: "计划在，但还没有权威的当前步骤。",
    waitRuntimeStep: "等计划运行时写出当前步骤，再继续。",
    planRuntime: "计划 · 运行时",
    currentMainlineStep: "这是当前主线步骤。",
    continueThisStep: "继续这一步",
    thenVerify: (method) => `做完后验证：${method}`,
    finishThenVerify: "完成这一步，再带回验证结果。",
    planCurrentStep: "计划 · 当前步骤",
  },
  "en-US": {
    learningPlan: "Learning plan",
    noFormalPlan: "There is no formal plan to follow yet.",
    generatePlan: "Generate plan",
    generateMainline: "Generate a mainline before choosing the current step.",
    continueWithoutPlan: "Continue without a plan",
    continueWithoutPlanWhy: "This workspace already has a first-look next. Do not invent a plan yet.",
    planFirstLook: "Plan · first look",
    planEmpty: "Plan · empty",
    currentPlan: "Current plan",
    clearBlocker: "Clear blocker",
    clearBlockerThenReturn: (step) => `Clear the blocker, then return to: ${step}`,
    clearThisBlocker: "Clear this blocker first.",
    planEvidenceBlockers: "Plan · evidence and blockers",
    frozenPlan: "Frozen plan",
    planFrozen: "The formal plan is frozen. Chat will not silently rewrite it.",
    unfreeze: "Unfreeze",
    frozenReviewOnly: "While frozen, review evidence without changing the mainline.",
    planFrozenWhere: "Plan · frozen",
    pendingEvidence: (count) => `${count} evidence item(s) are waiting. The plan has not changed.`,
    reviewEvidence: "Review evidence",
    confirmEvidence: (binding) => `Confirm: ${binding}`,
    confirmEvidenceThenStep: "Confirm evidence before moving the current step.",
    planEvidenceQueue: "Plan · evidence queue",
    waitForStep: "Wait",
    wait: "Wait",
    noAuthoritativeStep: "A plan exists, but no authoritative current step is persisted.",
    waitRuntimeStep: "Wait for plan runtime to persist the current step.",
    planRuntime: "Plan · runtime",
    currentMainlineStep: "This is the current mainline step.",
    continueThisStep: "Continue this step",
    thenVerify: (method) => `Then verify: ${method}`,
    finishThenVerify: "Finish this step, then return with verification.",
    planCurrentStep: "Plan · current step",
  },
  "es-ES": {
    learningPlan: "Plan de aprendizaje",
    noFormalPlan: "Aún no hay un plan formal que seguir.",
    generatePlan: "Generar plan",
    generateMainline: "Genera una línea principal antes de elegir el paso actual.",
    continueWithoutPlan: "Continuar sin un plan",
    continueWithoutPlanWhy: "Este espacio ya tiene un siguiente paso del primer vistazo. No inventes un plan todavía.",
    planFirstLook: "Plan · primer vistazo",
    planEmpty: "Plan · vacío",
    currentPlan: "Plan actual",
    clearBlocker: "Quitar bloqueo",
    clearBlockerThenReturn: (step) => `Quita el bloqueo y vuelve a: ${step}`,
    clearThisBlocker: "Quita primero este bloqueo.",
    planEvidenceBlockers: "Plan · evidencia y bloqueos",
    frozenPlan: "Plan bloqueado",
    planFrozen: "El plan formal está bloqueado. El chat no lo reescribe en silencio.",
    unfreeze: "Desbloquear",
    frozenReviewOnly: "Mientras esté bloqueado, revisa evidencia sin cambiar la línea.",
    planFrozenWhere: "Plan · bloqueado",
    pendingEvidence: (count) => `Hay ${count} evidencia(s) en espera. El plan no ha cambiado.`,
    reviewEvidence: "Revisar evidencia",
    confirmEvidence: (binding) => `Confirma: ${binding}`,
    confirmEvidenceThenStep: "Confirma la evidencia antes de avanzar el paso.",
    planEvidenceQueue: "Plan · cola de evidencia",
    waitForStep: "Esperar",
    wait: "Esperar",
    noAuthoritativeStep: "Hay un plan, pero no hay un paso actual persistido.",
    waitRuntimeStep: "Espera a que el runtime del plan persista el paso actual.",
    planRuntime: "Plan · runtime",
    currentMainlineStep: "Este es el paso actual de la línea.",
    continueThisStep: "Continuar este paso",
    thenVerify: (method) => `Luego verifica: ${method}`,
    finishThenVerify: "Termina este paso y vuelve con la verificación.",
    planCurrentStep: "Plan · paso actual",
  },
  "fr-FR": {
    learningPlan: "Plan d'apprentissage",
    noFormalPlan: "Il n'y a pas encore de plan formel à suivre.",
    generatePlan: "Générer le plan",
    generateMainline: "Générez une ligne principale avant de choisir l'étape actuelle.",
    continueWithoutPlan: "Continuer sans plan",
    continueWithoutPlanWhy: "Cet espace a déjà une suite du premier regard. N'inventez pas encore un plan.",
    planFirstLook: "Plan · premier regard",
    planEmpty: "Plan · vide",
    currentPlan: "Plan actuel",
    clearBlocker: "Lever le blocage",
    clearBlockerThenReturn: (step) => `Levez le blocage, puis revenez à : ${step}`,
    clearThisBlocker: "Levez d'abord ce blocage.",
    planEvidenceBlockers: "Plan · preuves et blocages",
    frozenPlan: "Plan figé",
    planFrozen: "Le plan formel est figé. Le chat ne le réécrit pas en silence.",
    unfreeze: "Dégeler",
    frozenReviewOnly: "Tant qu'il est figé, relisez les preuves sans changer la ligne.",
    planFrozenWhere: "Plan · figé",
    pendingEvidence: (count) => `${count} preuve(s) attendent. Le plan n'a pas changé.`,
    reviewEvidence: "Relire les preuves",
    confirmEvidence: (binding) => `Confirmez : ${binding}`,
    confirmEvidenceThenStep: "Confirmez les preuves avant d'avancer l'étape.",
    planEvidenceQueue: "Plan · file de preuves",
    waitForStep: "Attendre",
    wait: "Attendre",
    noAuthoritativeStep: "Un plan existe, mais aucune étape actuelle n'est persistée.",
    waitRuntimeStep: "Attendez que le runtime du plan persiste l'étape actuelle.",
    planRuntime: "Plan · runtime",
    currentMainlineStep: "C'est l'étape actuelle de la ligne.",
    continueThisStep: "Continuer cette étape",
    thenVerify: (method) => `Puis vérifiez : ${method}`,
    finishThenVerify: "Terminez cette étape, puis revenez avec la vérification.",
    planCurrentStep: "Plan · étape actuelle",
  },
  "de-DE": {
    learningPlan: "Lernplan",
    noFormalPlan: "Es gibt noch keinen formalen Plan zum Folgen.",
    generatePlan: "Plan erzeugen",
    generateMainline: "Erzeuge zuerst eine Hauptlinie, dann wähle den aktuellen Schritt.",
    continueWithoutPlan: "Ohne Plan weitermachen",
    continueWithoutPlanWhy: "Dieser Workspace hat schon einen First-Look-Nächsten Schritt. Erfinde noch keinen Plan.",
    planFirstLook: "Plan · erster Blick",
    planEmpty: "Plan · leer",
    currentPlan: "Aktueller Plan",
    clearBlocker: "Blocker räumen",
    clearBlockerThenReturn: (step) => `Räume den Blocker, dann zurück zu: ${step}`,
    clearThisBlocker: "Räume zuerst diesen Blocker.",
    planEvidenceBlockers: "Plan · Evidenz und Blocker",
    frozenPlan: "Gesperrter Plan",
    planFrozen: "Der formale Plan ist gesperrt. Der Chat schreibt ihn nicht still um.",
    unfreeze: "Entsperren",
    frozenReviewOnly: "Solange er gesperrt ist, prüfe Evidenz ohne die Linie zu ändern.",
    planFrozenWhere: "Plan · gesperrt",
    pendingEvidence: (count) => `${count} Evidenzstück(e) warten. Der Plan hat sich nicht geändert.`,
    reviewEvidence: "Evidenz prüfen",
    confirmEvidence: (binding) => `Bestätige: ${binding}`,
    confirmEvidenceThenStep: "Bestätige die Evidenz, bevor der Schritt weitergeht.",
    planEvidenceQueue: "Plan · Evidenzwarteschlange",
    waitForStep: "Warten",
    wait: "Warten",
    noAuthoritativeStep: "Ein Plan existiert, aber kein aktueller Schritt ist gespeichert.",
    waitRuntimeStep: "Warte, bis die Plan-Runtime den aktuellen Schritt speichert.",
    planRuntime: "Plan · Runtime",
    currentMainlineStep: "Das ist der aktuelle Hauptschritt.",
    continueThisStep: "Diesen Schritt fortsetzen",
    thenVerify: (method) => `Dann prüfen: ${method}`,
    finishThenVerify: "Beende diesen Schritt und komm mit der Prüfung zurück.",
    planCurrentStep: "Plan · aktueller Schritt",
  },
  "ja-JP": {
    learningPlan: "学習計画",
    noFormalPlan: "まだ従える正式な計画がありません。",
    generatePlan: "計画を生成",
    generateMainline: "本線を作ってから、現在の手順を決めてください。",
    continueWithoutPlan: "計画を作らず進む",
    continueWithoutPlanWhy: "このワークスペースには第一印象の次の一歩がすでにある。計画を発明しない。",
    planFirstLook: "計画 · 第一印象",
    planEmpty: "計画 · 空",
    currentPlan: "現在の計画",
    clearBlocker: "阻害を解消",
    clearBlockerThenReturn: (step) => `先に阻害を解消し、戻る：${step}`,
    clearThisBlocker: "先にこの阻害を解消してください。",
    planEvidenceBlockers: "計画 · 証拠と阻害",
    frozenPlan: "ロック中の計画",
    planFrozen: "正式計画はロックされています。対話は黙って書き換えません。",
    unfreeze: "ロック解除",
    frozenReviewOnly: "ロック中は証拠だけ確認し、本線は変えません。",
    planFrozenWhere: "計画 · ロック",
    pendingEvidence: (count) => `証拠が ${count} 件まだ未採用です。計画は変わっていません。`,
    reviewEvidence: "証拠を確認",
    confirmEvidence: (binding) => `先に確認：${binding}`,
    confirmEvidenceThenStep: "証拠を確認してから、現在の手順を進めてください。",
    planEvidenceQueue: "計画 · 証拠キュー",
    waitForStep: "待つ",
    wait: "待つ",
    noAuthoritativeStep: "計画はありますが、権威ある現在の手順はまだありません。",
    waitRuntimeStep: "計画ランタイムが現在の手順を書いてから続けてください。",
    planRuntime: "計画 · ランタイム",
    currentMainlineStep: "これが現在の本線手順です。",
    continueThisStep: "この手順を続ける",
    thenVerify: (method) => `終わったら検証：${method}`,
    finishThenVerify: "この手順を終えてから、検証結果を戻してください。",
    planCurrentStep: "計画 · 現在の手順",
  },
  "ko-KR": {
    learningPlan: "학습 계획",
    noFormalPlan: "아직 따를 수 있는 정식 계획이 없습니다.",
    generatePlan: "계획 만들기",
    generateMainline: "본선을 만든 뒤에 현재 단계를 정하세요.",
    continueWithoutPlan: "계획 없이 계속",
    continueWithoutPlanWhy: "이 작업공간에는 이미 첫인상 다음 단계가 있다. 계획을 만들지 마세요.",
    planFirstLook: "계획 · 첫인상",
    planEmpty: "계획 · 비어 있음",
    currentPlan: "현재 계획",
    clearBlocker: "차단 해제",
    clearBlockerThenReturn: (step) => `먼저 차단을 해제한 뒤 돌아가기: ${step}`,
    clearThisBlocker: "먼저 이 차단을 해결하세요.",
    planEvidenceBlockers: "계획 · 증거와 차단",
    frozenPlan: "잠긴 계획",
    planFrozen: "정식 계획이 잠겨 있습니다. 대화가 몰래 바꾸지 않습니다.",
    unfreeze: "잠금 해제",
    frozenReviewOnly: "잠겨 있는 동안 증거만 확인하고 본선은 바꾸지 마세요.",
    planFrozenWhere: "계획 · 잠김",
    pendingEvidence: (count) => `증거 ${count}개가 아직 채택되지 않았습니다. 계획은 바뀌지 않았습니다.`,
    reviewEvidence: "증거 확인",
    confirmEvidence: (binding) => `먼저 확인: ${binding}`,
    confirmEvidenceThenStep: "증거를 확인한 뒤에 현재 단계를 진행하세요.",
    planEvidenceQueue: "계획 · 증거 대기열",
    waitForStep: "기다리기",
    wait: "기다리기",
    noAuthoritativeStep: "계획은 있지만 권위 있는 현재 단계는 아직 없습니다.",
    waitRuntimeStep: "계획 런타임이 현재 단계를 기록할 때까지 기다리세요.",
    planRuntime: "계획 · 런타임",
    currentMainlineStep: "이것이 현재 본선 단계입니다.",
    continueThisStep: "이 단계 이어가기",
    thenVerify: (method) => `끝난 뒤 검증: ${method}`,
    finishThenVerify: "이 단계를 끝낸 뒤 검증 결과를 가져오세요.",
    planCurrentStep: "계획 · 현재 단계",
  },
  "pt-BR": {
    learningPlan: "Plano de aprendizado",
    noFormalPlan: "Ainda não há um plano formal para seguir.",
    generatePlan: "Gerar plano",
    generateMainline: "Gere uma linha principal antes de escolher o passo atual.",
    continueWithoutPlan: "Continuar sem um plano",
    continueWithoutPlanWhy: "Este espaço já tem o próximo passo do primeiro olhar. Não invente um plano ainda.",
    planFirstLook: "Plano · primeiro olhar",
    planEmpty: "Plano · vazio",
    currentPlan: "Plano atual",
    clearBlocker: "Resolver bloqueio",
    clearBlockerThenReturn: (step) => `Resolva o bloqueio e volte para: ${step}`,
    clearThisBlocker: "Resolva primeiro este bloqueio.",
    planEvidenceBlockers: "Plano · evidência e bloqueios",
    frozenPlan: "Plano congelado",
    planFrozen: "O plano formal está congelado. O chat não o reescreve em silêncio.",
    unfreeze: "Descongelar",
    frozenReviewOnly: "Enquanto estiver congelado, revise evidência sem mudar a linha.",
    planFrozenWhere: "Plano · congelado",
    pendingEvidence: (count) => `${count} evidência(s) aguardam. O plano não mudou.`,
    reviewEvidence: "Revisar evidência",
    confirmEvidence: (binding) => `Confirme: ${binding}`,
    confirmEvidenceThenStep: "Confirme a evidência antes de avançar o passo.",
    planEvidenceQueue: "Plano · fila de evidência",
    waitForStep: "Esperar",
    wait: "Esperar",
    noAuthoritativeStep: "Há um plano, mas nenhum passo atual persistido.",
    waitRuntimeStep: "Espere o runtime do plano persistir o passo atual.",
    planRuntime: "Plano · runtime",
    currentMainlineStep: "Este é o passo atual da linha.",
    continueThisStep: "Continuar este passo",
    thenVerify: (method) => `Depois verifique: ${method}`,
    finishThenVerify: "Termine este passo e volte com a verificação.",
    planCurrentStep: "Plano · passo atual",
  },
};

const RESOURCES_COPY: Record<OrientationLocale, ResourcesOrientationCopy> = {
  "zh-CN": {
    resourceLibrary: "资料库",
    libraryEmpty: "资料库是空的，还不能检索或绑定。",
    importResource: "导入资料",
    importThenIndex: "先导入文件、文件夹或网页，再建立索引。",
    resourcesEmptyLibrary: "资料 · 空库",
    currentResource: "当前资料",
    indexFailed: "这份资料的索引失败了，还不能当成功来用。",
    retryIndex: "重试索引",
    fixIndexFirst: "先修好索引，再预览或绑定。",
    resourcesFailedIndex: "资料 · 索引失败",
    sourceUntrusted: "来源不可信或抓取失败，不能当成已绑定的学习材料。",
    refreshSource: "刷新来源",
    confirmSourceFirst: "先确认来源可用，再考虑计划和训练绑定。",
    resourcesTrust: "资料 · 来源与信任",
    stillIndexing: "资料还在建立索引，不能当成已就绪。",
    wait: "等待索引",
    waitIndexThenBind: "等索引完成后再预览或绑定。",
    resourcesIndexing: "资料 · 索引进度",
    resourceStale: "这份资料已经过期，当前快照不能当新内容用。",
    refreshIndex: "刷新索引",
    refreshThenBind: "刷新后再决定是否绑定到计划或训练。",
    resourcesStale: "资料 · 过期",
    resourceSearch: "资料检索",
    noHits: (query) => `没有命中「${query}」。`,
    changeQueryOrImport: "换关键词，或导入更相关的资料。",
    resourcesSearch: "资料 · 检索",
    hitsFound: (count) => `检索到 ${count} 条，还没有选定对象。`,
    chooseOne: "选定资料",
    selectThenPreview: "先选定一条，再预览或绑定。",
    resourcesSearchHits: "资料 · 检索结果",
    libraryHasItems: (count) => `库里有 ${count} 条资料，还没有当前对象。`,
    selectBeforePreview: "选定一条资料，再看预览和绑定。",
    resourcesList: "资料 · 列表",
    boundToPlan: (id) => `已绑定到计划 ${id}。`,
    openPlan: "打开计划",
    reviewOnPlan: "到计划里核对此条证据。",
    resourcesPlanBinding: "资料 · 计划绑定",
    boundToCard: (id) => `已绑定到训练卡 ${id}。`,
    openTraining: "打开训练",
    continueCard: "到训练里继续这张卡。",
    resourcesTrainingBinding: "资料 · 训练绑定",
    indexedNoPreview: "资料已索引，但还没有当前预览。",
    preview: "打开预览",
    previewBeforeBind: "先预览内容，再决定是否绑定。",
    resourcesPreview: "资料 · 预览",
    indexedReadable: "当前资料已索引，可以阅读。",
    keepReading: "继续阅读",
    readThenBindWhenLinked: "阅读后如需绑定，要等计划或训练出现真实链接。",
    resourcesCurrentItem: "资料 · 当前条目",
    materialSimpler: "优先用当前项目里更简单的恢复资料。",
    materialCurrent: "继续用当前项目、当前场景的资料。",
    materialTransfer: "第二个场景已有证据，迁移资料可用。",
    materialTransferBlocked: "只有一个场景，不能选全局或迁移掌握资料。",
  },
  "en-US": {
    resourceLibrary: "Resource library",
    libraryEmpty: "The library is empty. Nothing is ready to search or bind.",
    importResource: "Import",
    importThenIndex: "Import a file, folder, or page, then index it.",
    resourcesEmptyLibrary: "Resources · empty library",
    currentResource: "Current resource",
    indexFailed: "Indexing failed. This resource is not a successful source.",
    retryIndex: "Retry index",
    fixIndexFirst: "Fix the index before preview or binding.",
    resourcesFailedIndex: "Resources · failed index",
    sourceUntrusted: "The source is untrusted or failed. It is not a bound learning item.",
    refreshSource: "Refresh source",
    confirmSourceFirst: "Confirm the source before any plan or training binding.",
    resourcesTrust: "Resources · trust",
    stillIndexing: "This resource is still indexing and is not ready.",
    wait: "Wait",
    waitIndexThenBind: "Wait for indexing before preview or binding.",
    resourcesIndexing: "Resources · indexing",
    resourceStale: "This resource is stale. The current snapshot is not fresh.",
    refreshIndex: "Refresh index",
    refreshThenBind: "Refresh before deciding on plan or training binding.",
    resourcesStale: "Resources · stale",
    resourceSearch: "Resource search",
    noHits: (query) => `No hits for “${query}”.`,
    changeQueryOrImport: "Change the query, or import a more relevant source.",
    resourcesSearch: "Resources · search",
    hitsFound: (count) => `${count} hit(s) found. Nothing is selected.`,
    chooseOne: "Choose one",
    selectThenPreview: "Select one hit before preview or binding.",
    resourcesSearchHits: "Resources · search hits",
    libraryHasItems: (count) => `${count} item(s) are in the library. Nothing is current.`,
    selectBeforePreview: "Select a resource before preview or binding.",
    resourcesList: "Resources · list",
    boundToPlan: (id) => `Bound to plan ${id}.`,
    openPlan: "Open plan",
    reviewOnPlan: "Review this evidence on the plan.",
    resourcesPlanBinding: "Resources · plan binding",
    boundToCard: (id) => `Bound to training card ${id}.`,
    openTraining: "Open training",
    continueCard: "Continue this card in Training.",
    resourcesTrainingBinding: "Resources · training binding",
    indexedNoPreview: "The resource is indexed, but no preview is current.",
    preview: "Preview",
    previewBeforeBind: "Preview the content before any binding.",
    resourcesPreview: "Resources · preview",
    indexedReadable: "The current resource is indexed and readable.",
    keepReading: "Keep reading",
    readThenBindWhenLinked: "Read first. Bind only when a real plan or training link exists.",
    resourcesCurrentItem: "Resources · current item",
    materialSimpler: "Prefer easier recovery sources in this project.",
    materialCurrent: "Stay with this project's current-scene sources.",
    materialTransfer: "A second scene is evidenced, so transfer sources are eligible.",
    materialTransferBlocked: "One scene cannot pick global or transfer mastery sources.",
  },
  "es-ES": {
    resourceLibrary: "Biblioteca",
    libraryEmpty: "La biblioteca está vacía. Nada está listo para buscar o vincular.",
    importResource: "Importar",
    importThenIndex: "Importa un archivo, carpeta o página y luego indízalo.",
    resourcesEmptyLibrary: "Recursos · biblioteca vacía",
    currentResource: "Recurso actual",
    indexFailed: "La indexación falló. Este recurso no es una fuente exitosa.",
    retryIndex: "Reintentar índice",
    fixIndexFirst: "Repara el índice antes de previsualizar o vincular.",
    resourcesFailedIndex: "Recursos · índice fallido",
    sourceUntrusted: "La fuente no es de confianza o falló. No es un material vinculado.",
    refreshSource: "Actualizar fuente",
    confirmSourceFirst: "Confirma la fuente antes de vincular a plan o entrenamiento.",
    resourcesTrust: "Recursos · confianza",
    stillIndexing: "Este recurso aún se indexa y no está listo.",
    wait: "Esperar",
    waitIndexThenBind: "Espera el índice antes de previsualizar o vincular.",
    resourcesIndexing: "Recursos · indexación",
    resourceStale: "Este recurso está caducado. La instantánea no es reciente.",
    refreshIndex: "Actualizar índice",
    refreshThenBind: "Actualiza antes de decidir un vínculo a plan o entrenamiento.",
    resourcesStale: "Recursos · caducado",
    resourceSearch: "Búsqueda",
    noHits: (query) => `No hay resultados para “${query}”.`,
    changeQueryOrImport: "Cambia la consulta o importa una fuente más relevante.",
    resourcesSearch: "Recursos · búsqueda",
    hitsFound: (count) => `${count} resultado(s). Nada está seleccionado.`,
    chooseOne: "Elegir uno",
    selectThenPreview: "Elige un resultado antes de previsualizar o vincular.",
    resourcesSearchHits: "Recursos · resultados",
    libraryHasItems: (count) => `Hay ${count} ítem(s) en la biblioteca. Nada es actual.`,
    selectBeforePreview: "Elige un recurso antes de previsualizar o vincular.",
    resourcesList: "Recursos · lista",
    boundToPlan: (id) => `Vinculado al plan ${id}.`,
    openPlan: "Abrir plan",
    reviewOnPlan: "Revisa esta evidencia en el plan.",
    resourcesPlanBinding: "Recursos · vínculo al plan",
    boundToCard: (id) => `Vinculado a la tarjeta ${id}.`,
    openTraining: "Abrir entrenamiento",
    continueCard: "Continúa esta tarjeta en Entrenamiento.",
    resourcesTrainingBinding: "Recursos · vínculo al entrenamiento",
    indexedNoPreview: "El recurso está indexado, pero no hay vista previa actual.",
    preview: "Vista previa",
    previewBeforeBind: "Previsualiza el contenido antes de vincular.",
    resourcesPreview: "Recursos · vista previa",
    indexedReadable: "El recurso actual está indexado y se puede leer.",
    keepReading: "Seguir leyendo",
    readThenBindWhenLinked: "Lee primero. Vincula solo cuando exista un enlace real.",
    resourcesCurrentItem: "Recursos · ítem actual",
    materialSimpler: "Prefiere fuentes de recuperación más fáciles en este proyecto.",
    materialCurrent: "Quédate con las fuentes de la escena actual de este proyecto.",
    materialTransfer: "Hay evidencia en una segunda escena; las fuentes de transferencia valen.",
    materialTransferBlocked: "Una sola escena no puede elegir fuentes globales o de dominio transferible.",
  },
  "fr-FR": {
    resourceLibrary: "Bibliothèque",
    libraryEmpty: "La bibliothèque est vide. Rien n'est prêt à chercher ou lier.",
    importResource: "Importer",
    importThenIndex: "Importez un fichier, un dossier ou une page, puis indexez-le.",
    resourcesEmptyLibrary: "Ressources · bibliothèque vide",
    currentResource: "Ressource actuelle",
    indexFailed: "L'indexation a échoué. Cette ressource n'est pas une source réussie.",
    retryIndex: "Réessayer l'index",
    fixIndexFirst: "Réparez l'index avant l'aperçu ou la liaison.",
    resourcesFailedIndex: "Ressources · index échoué",
    sourceUntrusted: "La source n'est pas fiable ou a échoué. Ce n'est pas un item lié.",
    refreshSource: "Actualiser la source",
    confirmSourceFirst: "Confirmez la source avant toute liaison au plan ou à l'entraînement.",
    resourcesTrust: "Ressources · confiance",
    stillIndexing: "Cette ressource s'indexe encore et n'est pas prête.",
    wait: "Attendre",
    waitIndexThenBind: "Attendez l'index avant l'aperçu ou la liaison.",
    resourcesIndexing: "Ressources · indexation",
    resourceStale: "Cette ressource est périmée. L'instantané n'est pas frais.",
    refreshIndex: "Actualiser l'index",
    refreshThenBind: "Actualisez avant de décider une liaison plan ou entraînement.",
    resourcesStale: "Ressources · périmé",
    resourceSearch: "Recherche",
    noHits: (query) => `Aucun résultat pour « ${query} ».`,
    changeQueryOrImport: "Changez la requête, ou importez une source plus pertinente.",
    resourcesSearch: "Ressources · recherche",
    hitsFound: (count) => `${count} résultat(s). Rien n'est sélectionné.`,
    chooseOne: "Choisir",
    selectThenPreview: "Sélectionnez un résultat avant l'aperçu ou la liaison.",
    resourcesSearchHits: "Ressources · résultats",
    libraryHasItems: (count) => `${count} élément(s) sont dans la bibliothèque. Rien n'est actuel.`,
    selectBeforePreview: "Sélectionnez une ressource avant l'aperçu ou la liaison.",
    resourcesList: "Ressources · liste",
    boundToPlan: (id) => `Liée au plan ${id}.`,
    openPlan: "Ouvrir le plan",
    reviewOnPlan: "Relisez cette preuve sur le plan.",
    resourcesPlanBinding: "Ressources · liaison plan",
    boundToCard: (id) => `Liée à la carte ${id}.`,
    openTraining: "Ouvrir l'entraînement",
    continueCard: "Continuez cette carte dans Entraînement.",
    resourcesTrainingBinding: "Ressources · liaison entraînement",
    indexedNoPreview: "La ressource est indexée, mais aucun aperçu n'est actuel.",
    preview: "Aperçu",
    previewBeforeBind: "Prévisualisez le contenu avant toute liaison.",
    resourcesPreview: "Ressources · aperçu",
    indexedReadable: "La ressource actuelle est indexée et lisible.",
    keepReading: "Continuer la lecture",
    readThenBindWhenLinked: "Lisez d'abord. Ne liez que si un vrai lien plan ou entraînement existe.",
    resourcesCurrentItem: "Ressources · élément actuel",
    materialSimpler: "Préférez des sources de récupération plus simples dans ce projet.",
    materialCurrent: "Restez sur les sources de la scène actuelle de ce projet.",
    materialTransfer: "Une deuxième scène est prouvée ; les sources de transfert sont éligibles.",
    materialTransferBlocked: "Une seule scène ne peut pas choisir des sources globales ou de maîtrise transférable.",
  },
  "de-DE": {
    resourceLibrary: "Bibliothek",
    libraryEmpty: "Die Bibliothek ist leer. Nichts ist bereit zum Suchen oder Binden.",
    importResource: "Importieren",
    importThenIndex: "Importiere Datei, Ordner oder Seite und indexiere sie.",
    resourcesEmptyLibrary: "Ressourcen · leere Bibliothek",
    currentResource: "Aktuelle Ressource",
    indexFailed: "Die Indexierung ist fehlgeschlagen. Das ist keine erfolgreiche Quelle.",
    retryIndex: "Index erneut",
    fixIndexFirst: "Repariere den Index vor Vorschau oder Bindung.",
    resourcesFailedIndex: "Ressourcen · fehlgeschlagener Index",
    sourceUntrusted: "Die Quelle ist untrusted oder fehlgeschlagen. Kein gebundenes Lernitem.",
    refreshSource: "Quelle aktualisieren",
    confirmSourceFirst: "Bestätige die Quelle, bevor Plan oder Training gebunden wird.",
    resourcesTrust: "Ressourcen · Vertrauen",
    stillIndexing: "Diese Ressource wird noch indexiert und ist nicht bereit.",
    wait: "Warten",
    waitIndexThenBind: "Warte auf den Index vor Vorschau oder Bindung.",
    resourcesIndexing: "Ressourcen · Indexierung",
    resourceStale: "Diese Ressource ist veraltet. Der Snapshot ist nicht frisch.",
    refreshIndex: "Index aktualisieren",
    refreshThenBind: "Aktualisiere, bevor du Plan- oder Training-Bindung entscheidest.",
    resourcesStale: "Ressourcen · veraltet",
    resourceSearch: "Suche",
    noHits: (query) => `Keine Treffer für „${query}“.`,
    changeQueryOrImport: "Ändere die Suche oder importiere eine passendere Quelle.",
    resourcesSearch: "Ressourcen · Suche",
    hitsFound: (count) => `${count} Treffer. Nichts ist ausgewählt.`,
    chooseOne: "Eine wählen",
    selectThenPreview: "Wähle einen Treffer vor Vorschau oder Bindung.",
    resourcesSearchHits: "Ressourcen · Treffer",
    libraryHasItems: (count) => `${count} Eintrag/Einträge in der Bibliothek. Nichts ist aktuell.`,
    selectBeforePreview: "Wähle eine Ressource vor Vorschau oder Bindung.",
    resourcesList: "Ressourcen · Liste",
    boundToPlan: (id) => `An Plan ${id} gebunden.`,
    openPlan: "Plan öffnen",
    reviewOnPlan: "Prüfe diese Evidenz im Plan.",
    resourcesPlanBinding: "Ressourcen · Planbindung",
    boundToCard: (id) => `An Trainingskarte ${id} gebunden.`,
    openTraining: "Training öffnen",
    continueCard: "Setze diese Karte im Training fort.",
    resourcesTrainingBinding: "Ressourcen · Trainingsbindung",
    indexedNoPreview: "Die Ressource ist indexiert, aber keine Vorschau ist aktuell.",
    preview: "Vorschau",
    previewBeforeBind: "Sieh den Inhalt an, bevor du bindest.",
    resourcesPreview: "Ressourcen · Vorschau",
    indexedReadable: "Die aktuelle Ressource ist indexiert und lesbar.",
    keepReading: "Weiterlesen",
    readThenBindWhenLinked: "Lies zuerst. Binde nur, wenn ein echter Plan- oder Trainingslink existiert.",
    resourcesCurrentItem: "Ressourcen · aktueller Eintrag",
    materialSimpler: "Bevorzuge einfachere Erholungsquellen in diesem Projekt.",
    materialCurrent: "Bleib bei den Quellen der aktuellen Szene dieses Projekts.",
    materialTransfer: "Eine zweite Szene ist belegt; Transferquellen sind zulässig.",
    materialTransferBlocked: "Eine Szene darf keine globalen oder Transfer-Meisterschaftsquellen wählen.",
  },
  "ja-JP": {
    resourceLibrary: "資料ライブラリ",
    libraryEmpty: "資料ライブラリは空です。検索もバインドもまだできません。",
    importResource: "資料を取り込む",
    importThenIndex: "ファイル、フォルダ、ページを取り込んでから索引してください。",
    resourcesEmptyLibrary: "資料 · 空の庫",
    currentResource: "現在の資料",
    indexFailed: "索引に失敗しました。この資料は成功した出典ではありません。",
    retryIndex: "索引を再試行",
    fixIndexFirst: "先に索引を直してから、プレビューやバインドをしてください。",
    resourcesFailedIndex: "資料 · 索引失敗",
    sourceUntrusted: "出典が信頼できないか取得に失敗しています。学習材料ではありません。",
    refreshSource: "出典を更新",
    confirmSourceFirst: "出典を確認してから、計画や訓練へバインドしてください。",
    resourcesTrust: "資料 · 信頼",
    stillIndexing: "この資料はまだ索引中で、準備できていません。",
    wait: "待つ",
    waitIndexThenBind: "索引が終わってからプレビューやバインドをしてください。",
    resourcesIndexing: "資料 · 索引",
    resourceStale: "この資料は古く、現在のスナップショットは新しくありません。",
    refreshIndex: "索引を更新",
    refreshThenBind: "更新してから、計画や訓練へのバインドを決めてください。",
    resourcesStale: "資料 · 期限切れ",
    resourceSearch: "資料検索",
    noHits: (query) => `「${query}」に一致はありません。`,
    changeQueryOrImport: "語を変えるか、より関連する資料を取り込んでください。",
    resourcesSearch: "資料 · 検索",
    hitsFound: (count) => `${count} 件あります。対象はまだ選んでいません。`,
    chooseOne: "資料を選ぶ",
    selectThenPreview: "1 件選んでから、プレビューやバインドをしてください。",
    resourcesSearchHits: "資料 · 検索結果",
    libraryHasItems: (count) => `庫に ${count} 件あります。現在の対象はありません。`,
    selectBeforePreview: "資料を選んでから、プレビューとバインドを見てください。",
    resourcesList: "資料 · 一覧",
    boundToPlan: (id) => `計画 ${id} にバインド済みです。`,
    openPlan: "計画を開く",
    reviewOnPlan: "計画でこの証拠を確認してください。",
    resourcesPlanBinding: "資料 · 計画バインド",
    boundToCard: (id) => `訓練カード ${id} にバインド済みです。`,
    openTraining: "訓練を開く",
    continueCard: "訓練でこのカードを続けてください。",
    resourcesTrainingBinding: "資料 · 訓練バインド",
    indexedNoPreview: "索引は済みましたが、現在のプレビューはありません。",
    preview: "プレビュー",
    previewBeforeBind: "先に内容を見てから、バインドを決めてください。",
    resourcesPreview: "資料 · プレビュー",
    indexedReadable: "現在の資料は索引済みで読めます。",
    keepReading: "読み続ける",
    readThenBindWhenLinked: "先に読んでください。本物の計画や訓練リンクがあるときだけバインドします。",
    resourcesCurrentItem: "資料 · 現在の項目",
    materialSimpler: "このプロジェクトのより簡単な回復資料を優先します。",
    materialCurrent: "このプロジェクトの現在シーンの資料を使い続けます。",
    materialTransfer: "第二の場面に証拠があるので、移行資料を使えます。",
    materialTransferBlocked: "一つの場面だけでは、グローバルや移行習熟の資料は選べません。",
  },
  "ko-KR": {
    resourceLibrary: "자료실",
    libraryEmpty: "자료실이 비어 있습니다. 검색하거나 바인딩할 수 없습니다.",
    importResource: "자료 가져오기",
    importThenIndex: "파일, 폴더 또는 페이지를 가져온 뒤 색인하세요.",
    resourcesEmptyLibrary: "자료 · 빈 자료실",
    currentResource: "현재 자료",
    indexFailed: "색인이 실패했습니다. 이 자료는 성공한 출처가 아닙니다.",
    retryIndex: "색인 다시 시도",
    fixIndexFirst: "색인을 고친 뒤에 미리보기나 바인딩을 하세요.",
    resourcesFailedIndex: "자료 · 색인 실패",
    sourceUntrusted: "출처를 신뢰할 수 없거나 가져오기에 실패했습니다. 학습 자료가 아닙니다.",
    refreshSource: "출처 새로고침",
    confirmSourceFirst: "출처를 확인한 뒤에 계획이나 훈련에 바인딩하세요.",
    resourcesTrust: "자료 · 신뢰",
    stillIndexing: "이 자료는 아직 색인 중이며 준비되지 않았습니다.",
    wait: "기다리기",
    waitIndexThenBind: "색인이 끝난 뒤에 미리보기나 바인딩을 하세요.",
    resourcesIndexing: "자료 · 색인",
    resourceStale: "이 자료는 오래되었습니다. 현재 스냅샷은 최신이 아닙니다.",
    refreshIndex: "색인 새로고침",
    refreshThenBind: "새로고친 뒤에 계획이나 훈련 바인딩을 결정하세요.",
    resourcesStale: "자료 · 만료",
    resourceSearch: "자료 검색",
    noHits: (query) => `「${query}」에 대한 결과가 없습니다.`,
    changeQueryOrImport: "검색어를 바꾸거나 더 관련 있는 자료를 가져오세요.",
    resourcesSearch: "자료 · 검색",
    hitsFound: (count) => `${count}건이 있습니다. 선택된 대상은 없습니다.`,
    chooseOne: "하나 고르기",
    selectThenPreview: "하나를 고른 뒤에 미리보기나 바인딩을 하세요.",
    resourcesSearchHits: "자료 · 검색 결과",
    libraryHasItems: (count) => `자료실에 ${count}개가 있습니다. 현재 대상은 없습니다.`,
    selectBeforePreview: "자료를 고른 뒤에 미리보기와 바인딩을 보세요.",
    resourcesList: "자료 · 목록",
    boundToPlan: (id) => `계획 ${id}에 바인딩되었습니다.`,
    openPlan: "계획 열기",
    reviewOnPlan: "계획에서 이 증거를 확인하세요.",
    resourcesPlanBinding: "자료 · 계획 바인딩",
    boundToCard: (id) => `훈련 카드 ${id}에 바인딩되었습니다.`,
    openTraining: "훈련 열기",
    continueCard: "훈련에서 이 카드를 이어가세요.",
    resourcesTrainingBinding: "자료 · 훈련 바인딩",
    indexedNoPreview: "색인은 되었지만 현재 미리보기는 없습니다.",
    preview: "미리보기",
    previewBeforeBind: "내용을 미리 본 뒤에 바인딩을 결정하세요.",
    resourcesPreview: "자료 · 미리보기",
    indexedReadable: "현재 자료는 색인되어 읽을 수 있습니다.",
    keepReading: "계속 읽기",
    readThenBindWhenLinked: "먼저 읽으세요. 실제 계획이나 훈련 링크가 있을 때만 바인딩합니다.",
    resourcesCurrentItem: "자료 · 현재 항목",
    materialSimpler: "이 프로젝트의 더 쉬운 회복 자료를 우선합니다.",
    materialCurrent: "이 프로젝트의 현재 장면 자료를 유지합니다.",
    materialTransfer: "두 번째 장면 증거가 있어 전이 자료를 쓸 수 있습니다.",
    materialTransferBlocked: "장면이 하나면 전역이나 전이 숙달 자료를 고를 수 없습니다.",
  },
  "pt-BR": {
    resourceLibrary: "Biblioteca",
    libraryEmpty: "A biblioteca está vazia. Nada está pronto para buscar ou vincular.",
    importResource: "Importar",
    importThenIndex: "Importe um arquivo, pasta ou página e depois indexe.",
    resourcesEmptyLibrary: "Recursos · biblioteca vazia",
    currentResource: "Recurso atual",
    indexFailed: "A indexação falhou. Este recurso não é uma fonte bem-sucedida.",
    retryIndex: "Tentar índice de novo",
    fixIndexFirst: "Conserte o índice antes de pré-visualizar ou vincular.",
    resourcesFailedIndex: "Recursos · índice falhou",
    sourceUntrusted: "A fonte não é confiável ou falhou. Não é um item de aprendizado vinculado.",
    refreshSource: "Atualizar fonte",
    confirmSourceFirst: "Confirme a fonte antes de vincular a plano ou treino.",
    resourcesTrust: "Recursos · confiança",
    stillIndexing: "Este recurso ainda está indexando e não está pronto.",
    wait: "Esperar",
    waitIndexThenBind: "Espere a indexação antes de pré-visualizar ou vincular.",
    resourcesIndexing: "Recursos · indexação",
    resourceStale: "Este recurso está velho. O snapshot atual não é fresco.",
    refreshIndex: "Atualizar índice",
    refreshThenBind: "Atualize antes de decidir um vínculo com plano ou treino.",
    resourcesStale: "Recursos · velho",
    resourceSearch: "Busca",
    noHits: (query) => `Nenhum resultado para “${query}”.`,
    changeQueryOrImport: "Mude a busca ou importe uma fonte mais relevante.",
    resourcesSearch: "Recursos · busca",
    hitsFound: (count) => `${count} resultado(s). Nada está selecionado.`,
    chooseOne: "Escolher um",
    selectThenPreview: "Escolha um resultado antes de pré-visualizar ou vincular.",
    resourcesSearchHits: "Recursos · resultados",
    libraryHasItems: (count) => `Há ${count} item(ns) na biblioteca. Nada é atual.`,
    selectBeforePreview: "Escolha um recurso antes de pré-visualizar ou vincular.",
    resourcesList: "Recursos · lista",
    boundToPlan: (id) => `Vinculado ao plano ${id}.`,
    openPlan: "Abrir plano",
    reviewOnPlan: "Revise esta evidência no plano.",
    resourcesPlanBinding: "Recursos · vínculo ao plano",
    boundToCard: (id) => `Vinculado ao cartão ${id}.`,
    openTraining: "Abrir treino",
    continueCard: "Continue este cartão no Treino.",
    resourcesTrainingBinding: "Recursos · vínculo ao treino",
    indexedNoPreview: "O recurso está indexado, mas não há pré-visualização atual.",
    preview: "Pré-visualizar",
    previewBeforeBind: "Pré-visualize o conteúdo antes de qualquer vínculo.",
    resourcesPreview: "Recursos · pré-visualização",
    indexedReadable: "O recurso atual está indexado e pode ser lido.",
    keepReading: "Continuar lendo",
    readThenBindWhenLinked: "Leia primeiro. Vincule só quando existir um link real de plano ou treino.",
    resourcesCurrentItem: "Recursos · item atual",
    materialSimpler: "Prefira fontes de recuperação mais simples neste projeto.",
    materialCurrent: "Fique com as fontes da cena atual deste projeto.",
    materialTransfer: "Há evidência numa segunda cena; fontes de transferência valem.",
    materialTransferBlocked: "Uma só cena não pode escolher fontes globais ou de domínio transferível.",
  },
};

export function coachOrientationCopy(language?: string): CoachOrientationCopy {
  return COACH_COPY[resolveOrientationLocale(language)];
}

export function planOrientationCopy(language?: string): PlanOrientationCopy {
  return PLAN_COPY[resolveOrientationLocale(language)];
}

export function resourcesOrientationCopy(language?: string): ResourcesOrientationCopy {
  return RESOURCES_COPY[resolveOrientationLocale(language)];
}
