import fs from 'fs';

const path = 'copy.ts';
let content = fs.readFileSync(path, 'utf8');

const translations = {
  // Coach Action Status
  coachActionCheckingResources: "正在检查资料",
  coachActionAligningPlan: "正在对齐计划",
  coachActionSchedulingTraining: "正在安排训练",
  coachActionEvaluatingResult: "正在评估结果",
  coachActionGeneratingCard: "正在生成卡片",
  coachActionReviewingEvidence: "正在审阅证据",
  coachActionIdle: "等待中",

  // Conversation Candidates
  candidateFlash: "闪记卡片",
  candidatePractice: "实战卡片",
  candidateEvidence: "证据",
  candidateResourceImport: "资料导入",
  candidatePlanChange: "计划变更",
  continueInChat: "继续对话",
  continueInTraining: "继续训练",
  continueInPlan: "继续计划",
  continueInResources: "继续资料",
  dismiss: "忽略",
  autoGenerated: "自动生成",
  targetSkill: "目标技能",

  // Boundary Notes
  boundaryNotePlan: "边界说明：这是计划层面的建议，不是实现层面的代码。",
  boundaryNoteCode: "边界说明：Trainer 只负责教练，不会替你改代码。",

  // Misc
  expand: "展开",
  errorTitle: "出错了",

  // Flash/Practice Labels
  rubricLabel: "评分规则",
  commonMistakesLabel: "常见错误",
  correctLabel: "答对",
  needsWorkLabel: "待加强",
  typeYourAnswer: "输入你的答案",
  dependencyMasteryLabel: "依赖掌握",
  needsMoreReinforcement: "需要继续用真实场景巩固。",
  referencePrefix: "参考答案：",
  yourAnswerPrefix: "你的回答：",
  hintPrefix: "提示 ",
  useAnswersToSteerTraining: "用回答来引导训练",
  submissionLoading: "提交中…",

  // Plan Stage Status
  planStageDone: "已完成",
  planStageActive: "进行中",
  planStageNotStarted: "未开始",
  planLastStage: "最后阶段",
  planQueuedStageCount: "个后续阶段",
  planQueuedStageCount_plural: "个后续阶段",
  planNoReviewItems: "没有待复习项",
  planReviewItemCount: "个待复习项",
  planReviewItemCount_plural: "个待复习项",

  // Review Modes
  planSurfaceModeAhead: "提前复习",
  planSurfaceModeDigest: "合并复习",
  planSurfaceModeDue: "到期复习",

  // Plan Misc
  planMasteryLabel: "掌握度",
  planIntervalLabel: "间隔",
  planReviewLaneFallback: "复习通道",
  planEyebrow: "计划",
  planEmptyTitle: "还没有计划",
  planCurrentStageLabel: "当前阶段",
  planGoalLabel: "当前目标",
  planNowLabel: "现在",
  planNowHint: "先只做这一小步。",
  planStagesLabel: "阶段",
  planFreezeState: "已冻结",
  planLiveState: "进行中",
  planMemoryLabel: "记忆",
  planWinsLabel: "进步",
  planWeakSpotsLabel: "薄弱点",
  planReviewLabel: "回看",
  planReviewFocusHint: "回看重点",
  planCoachingStateLabel: "教练状态",
  planSupportSummaryLabel: "教练为什么这样带",
  planNotesLabel: "补充说明",
  planSupportHint: "先别被这些分心。把当前这一步做稳后，再回来看完整路径、回看点和教练判断。",
  planWhyNowLabel: "为什么现在做",
  planVerifyLabel: "做完怎么验",
  planReviewWindowLabel: "做完后再回看",
  planActionsLabel: "计划动作",
  planLaterLabel: "后面",
  planDetailsSummaryLabel: "详情摘要",
  planLinearOverviewLabel: "线性概览",
  planMainlineLabel: "主线",
  planRevisitSummaryLabel: "回看点",
  planRememberedLabel: "教练已记住",

  // Plan Preview
  planLaterPreviewDetail: "后续预览",
  planLaterContinuationNote: "后续继续说明",
  planVerifyFallback: "验证方式",
  planStageProgress: "阶段推进",
  planNowDigest: "当前合并",
  planVerifyDigest: "验证合并",
  planLaterDigest: "后续合并",

  // Plan Detail Summaries
  planDetailsSummaryAll: "全部详情",
  planDetailsSummaryStagesReview: "阶段和回看",
  planDetailsSummaryStagesBackground: "阶段和背景",
  planDetailsSummaryReviewBackground: "回看和背景",
  planDetailsSummaryStagesOnly: "仅阶段",
  planDetailsSummaryReviewOnly: "仅回看",
  planDetailsSummaryBackgroundOnly: "仅背景",

  // Teaching Observations (duplicate key)
  planTeachingObservationsLabel: "教学观察",

  // Compact Toolbar
  compactRefreshTask: "刷新训练题",
  compactCoach: "教练",
  compactFlash: "闪记",
  cardProcessing: "处理中",

  // Practice Meta
  whyNowLabel: "为什么现在",
  difficultyLabel: "难度",
  stuckAskCoach: "卡住了，问教练",
  produceReviewableSlice: "先做一个可评审的切片",
  emptyVerifyHint: "先跑最小相关检查，再解释为什么这一步成立。",
  validationMethodTitle: "验证方式",
  expectedAnswerShapeTitle: "预期答案形态",
  coachReviewInputTitle: "教练评审输入",
  sourceChainTitle: "来源链",
  whereToStartInProject: "从当前工程哪里下手",
  dependencyMasteryEmpty: "继续训练后，这里会显示当前最该刷的库和 API。",
  recentPracticeHistoryEmpty: "答过题后，这里会沉淀你最近的薄弱点反馈，并继续反作用回教练主线。",
  returnToCoach: "带回教练",
  sendToCoach: "发送给教练",
  verifyPrefix: "验证：",
  stuckBridgePrompt: "我在做「...」时卡住了。具体问题是：",
  pendingCardStatus: "卡片处理中",
  skillsCoveredLabel: "覆盖技能",
  upcomingCardLabel: "下一题",
};

for (const [key, value] of Object.entries(translations)) {
  const regex = new RegExp(`(${key}: ")([^"]+)("),`);
  content = content.replace(regex, `$1${value}$3,`);
}

fs.writeFileSync(path, content);
console.log('Localized', Object.keys(translations).length, 'additional keys in zh-CN block');
