import type { ComposerLanguage } from "../lib/types";

export const templateCopy: Record<ComposerLanguage, { nextAction: string; builtinSkills: string; currentLearning: string; growth: string; evidence: string; complete: string; askCoach: string; coach: string; joinLearning: string; generatePractice: string; adjustPlan: string; startReview: string; submitAnswer: string; recordReflection: string; reviewRecorded: string }> = {
  "zh-CN": { nextAction: "下一步", builtinSkills: "内置技能", submitAnswer: "提交回答", recordReflection: "记录训练复盘", reviewRecorded: "复习已记录", startReview: "开始复习", adjustPlan: "调整计划", joinLearning: "加入当前学习", generatePractice: "生成练习", coach: "教练", currentLearning: "当前学习", growth: "成长", evidence: "查看证据", complete: "完成标准", askCoach: "问教练" },
  "en-US": { nextAction: "Next step", builtinSkills: "Built-in skills", submitAnswer: "Submit answer", recordReflection: "Record training reflection", reviewRecorded: "Review recorded", startReview: "Start review", adjustPlan: "Adjust plan", joinLearning: "Add to current learning", generatePractice: "Generate practice", coach: "Coach", currentLearning: "Current learning", growth: "Growth", evidence: "View evidence", complete: "Done when", askCoach: "Ask Coach" },
  "es-ES": { nextAction: "Siguiente paso", builtinSkills: "Habilidades integradas", submitAnswer: "Enviar respuesta", recordReflection: "Registrar reflexión", reviewRecorded: "Repaso registrado", startReview: "Empezar repaso", adjustPlan: "Ajustar el plan", joinLearning: "Añadir al aprendizaje actual", generatePractice: "Generar práctica", coach: "Coach", currentLearning: "Aprendizaje actual", growth: "Crecimiento", evidence: "Ver evidencia", complete: "Completado cuando", askCoach: "Preguntar al coach" },
  "fr-FR": { nextAction: "Prochaine étape", builtinSkills: "Compétences intégrées", submitAnswer: "Envoyer la réponse", recordReflection: "Enregistrer la réflexion", reviewRecorded: "Révision enregistrée", startReview: "Commencer la révision", adjustPlan: "Adapter le plan", joinLearning: "Ajouter à l’apprentissage actuel", generatePractice: "Créer un exercice", coach: "Coach", currentLearning: "Apprentissage en cours", growth: "Progression", evidence: "Voir les preuves", complete: "Terminé quand", askCoach: "Demander au coach" },
  "de-DE": { nextAction: "Nächster Schritt", builtinSkills: "Integrierte Skills", submitAnswer: "Antwort senden", recordReflection: "Reflexion speichern", reviewRecorded: "Wiederholung gespeichert", startReview: "Wiederholung starten", adjustPlan: "Plan anpassen", joinLearning: "Zum aktuellen Lernen hinzufügen", generatePractice: "Übung erstellen", coach: "Coach", currentLearning: "Aktuelles Lernen", growth: "Entwicklung", evidence: "Nachweise ansehen", complete: "Fertig, wenn", askCoach: "Coach fragen" },
  "ja-JP": { nextAction: "次のステップ", builtinSkills: "組み込みスキル", submitAnswer: "回答を送信", recordReflection: "振り返りを記録", reviewRecorded: "復習を記録しました", startReview: "復習を開始", adjustPlan: "計画を調整", joinLearning: "現在の学習に追加", generatePractice: "練習を生成", coach: "コーチ", currentLearning: "現在の学習", growth: "成長", evidence: "証拠を見る", complete: "完了条件", askCoach: "コーチに聞く" },
  "ko-KR": { nextAction: "다음 단계", builtinSkills: "기본 스킬", submitAnswer: "답변 제출", recordReflection: "회고 기록", reviewRecorded: "복습 기록 완료", startReview: "복습 시작", adjustPlan: "계획 조정", joinLearning: "현재 학습에 추가", generatePractice: "연습 생성", coach: "코치", currentLearning: "현재 학습", growth: "성장", evidence: "증거 보기", complete: "완료 기준", askCoach: "코치에게 질문" },
  "pt-BR": { nextAction: "Próximo passo", builtinSkills: "Habilidades integradas", submitAnswer: "Enviar resposta", recordReflection: "Registrar reflexão", reviewRecorded: "Revisão registrada", startReview: "Iniciar revisão", adjustPlan: "Ajustar plano", joinLearning: "Adicionar ao aprendizado atual", generatePractice: "Gerar prática", coach: "Coach", currentLearning: "Aprendizado atual", growth: "Crescimento", evidence: "Ver evidências", complete: "Concluído quando", askCoach: "Perguntar ao coach" },
};
